// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! Declare routing-context source `node_id` (P4 routing, linkstate port step
//! c3c-3 atom3a) — the control-plane forward seam naming the tree-root a
//! linkstate-peer floods a SOURCED subscription declaration along. The
//! Declare twin of [`push_routing_context`](crate::push_routing_context).
//!
//! zenoh carries a sourced `DeclareSubscriber`'s routing SOURCE as the
//! Declare `ext_nodeid` extension — the SAME `zextz64!(0x3, true)` mandatory
//! `Z64` extension Push uses (`commons/zenoh-protocol/src/network/declare.rs`
//! `pub type NodeId = zextz64!(0x3, true)`, identical id to `push.rs`).
//! `node_id == 0` is the DEFAULT ("generated by the sending node itself",
//! omitted on the wire); a non-zero id names the source peer's `psid` in the
//! receiver's link space, resolved on receipt exactly as `forward_push`
//! resolves a Push's source. The subscription-propagation driver (c3c-3
//! atom3b) reads this to register the interested peer and re-flood the
//! declaration along the source's tree; this module is the read/build seam
//! for that one field.
//!
//! Wire: zenoh writes the Declare extensions BETWEEN the optional
//! `interest_id` and the declaration body (`commons/zenoh-codec/src/network/
//! declare.rs:117-132` — exts before body, unlike most network messages),
//! gated by the Declare header `Z` bit (`declare::flag::Z = 0x80`). The wz
//! codec mirrors that order, so a stamped `ext_nodeid` SURVIVES the codec
//! encode -> decode round-trip (the `set_then_read_round_trips_through_the_wire`
//! test pins that the value comes back, exercising the Declare extension path
//! the build helpers never did). Note that is value-survival, not byte-parity
//! against a zenoh golden vector — that golden-vector compare is a tracked gap,
//! the same as on the Push side. The ext header itself is identical to Push's
//! `ext_nodeid`: `id(0x3) | M(0x10) | Z64(0x20) = 0x33` terminal, `FLAG_Z(0x80)`
//! when another ext follows.
//!
//! The `ext_nodeid` id / flags / chain edit + `node_id` read/build live in the
//! shared [`ext_nodeid`](crate::ext_nodeid) SSOT (R311ru consolidated the prior
//! triplication across `push_build` / `push_routing_context` / this module).
//! This module keeps ONLY the Declare-level header `Z` sync — the one field
//! that differs from the Push twin.

use wz_codecs::declare::DeclareOwned;

use crate::ext_nodeid;

/// Read the routing-context source `node_id` from a Declare's `ext_nodeid`
/// extension. Returns `0` when absent — zenoh's self-originated DEFAULT, so a
/// forwarder treats `0` as "the inbound neighbour is the source". Delegates to
/// the shared [`ext_nodeid::read_source`](crate::ext_nodeid::read_source).
pub fn read_declare_source(declare: &DeclareOwned) -> u16 {
    ext_nodeid::read_source(declare.extensions.as_ref())
}

/// Set the routing-context source `node_id` on a Declare's `ext_nodeid`
/// extension (`node_id == 0` removes it — zenoh's omit-on-DEFAULT). The shared
/// [`ext_nodeid::set_source`](crate::ext_nodeid::set_source) owns the chain
/// edit (replace / remove / per-entry `Z` normalisation); this only syncs the
/// Declare-level header `Z` flag to the resulting chain.
pub fn set_declare_source(declare: &mut DeclareOwned, node_id: u16) {
    let present = ext_nodeid::set_source(&mut declare.extensions, node_id);
    ext_nodeid::sync_header_z(&mut declare.header, present);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::declare_build::build_declare_subscriber;
    use crate::ext_nodeid::{EXT_ENC_Z64, EXT_FLAG_Z, MESSAGE_FLAG_Z};
    use alloc::vec;
    use wz_codecs::ext_entry::{ExtEntryOwned, ExtEntryOwnedVariant};
    use wz_codecs::ext_zint::ExtZint;

    /// A sourced literal-keyexpr DeclareSubscriber (`id == 0`, the zenoh
    /// sourced-subscription sentinel; literal keyexpr via mapping id 0).
    fn declare_sub() -> DeclareOwned {
        build_declare_subscriber(0, 0, Some("demo/sub")).expect("build declare sub")
    }

    /// A non-nodeid ext (id 0x1, Z64) to exercise chain coexistence — a
    /// stand-in for the QoS/timestamp exts that ride alongside ext_nodeid.
    fn other_ext() -> ExtEntryOwned {
        ExtEntryOwned {
            header: 0x01 | EXT_ENC_Z64,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value: 5 }),
        }
    }

    #[test]
    fn absent_ext_reads_as_self_originated_zero() {
        let d = declare_sub();
        // R311y801 — the builder now emits ONE Declare-level ext, the `ext_qos`
        // zenoh stamps on every Declare. What this test gates is unchanged: no
        // ext_nodeid means self-originated, and the reader must not be confused
        // by a chain that exists but holds someone else's extension.
        assert_eq!(d.extensions.as_ref().map(|e| e.len()), Some(1));
        assert_eq!(read_declare_source(&d), 0);
    }

    #[test]
    fn set_then_read_round_trips() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        assert_eq!(read_declare_source(&d), 7);
    }

    #[test]
    fn nodeid_header_is_id_mandatory_z64_terminal() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        let exts = d.extensions.as_ref().expect("ext present after set");
        assert_eq!(exts.len(), 2, "the builder's ext_qos, then the nodeid");
        // 0x03 (id) | 0x10 (M) | 0x20 (Z64), Z clear (last entry).
        assert_eq!(exts[1].header, 0x33);
        // Declare-level Z bit set because a chain is now present.
        assert_eq!(d.header & MESSAGE_FLAG_Z, MESSAGE_FLAG_Z);
    }

    #[test]
    fn set_zero_removes_the_ext() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        set_declare_source(&mut d, 0);
        assert_eq!(read_declare_source(&d), 0);
        // R311y801 — the nodeid entry is dropped, the builder's ext_qos stays,
        // so the chain (and the header Z bit) survive. Removing one ext must
        // not silently take the rest of the chain with it.
        assert_eq!(d.extensions.as_ref().map(|e| e.len()), Some(1));
        assert_eq!(
            crate::declare_ext_qos::read_declare_qos(&d),
            crate::declare_ext_qos::QOS_DECLARE,
        );
        assert_eq!(
            d.header & MESSAGE_FLAG_Z,
            MESSAGE_FLAG_Z,
            "Declare Z bit still set — a chain remains"
        );
    }

    #[test]
    fn set_replaces_an_existing_nodeid() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        set_declare_source(&mut d, 9);
        assert_eq!(read_declare_source(&d), 9);
        let exts = d.extensions.as_ref().expect("ext present");
        assert_eq!(exts.len(), 2, "replaced, not duplicated (ext_qos + nodeid)");
    }

    #[test]
    fn coexists_with_another_ext_and_fixes_chain_z_bits() {
        let mut d = declare_sub();
        // Seed a pre-existing (non-nodeid) extension.
        d.extensions = Some(vec![other_ext()]);
        d.header |= MESSAGE_FLAG_Z;

        set_declare_source(&mut d, 7);
        let exts = d.extensions.as_ref().expect("chain present");
        assert_eq!(exts.len(), 2, "other ext kept, nodeid appended");
        // The non-last entry carries the continuation bit; nodeid terminates.
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64 | EXT_FLAG_Z);
        assert_eq!(exts[1].header, 0x33);
        assert_eq!(read_declare_source(&d), 7);

        // Removing the nodeid leaves the other ext as a terminal entry.
        set_declare_source(&mut d, 0);
        let exts = d.extensions.as_ref().expect("other ext remains");
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64, "Z bit cleared (last)");
        assert_eq!(
            d.header & MESSAGE_FLAG_Z,
            MESSAGE_FLAG_Z,
            "chain still present"
        );
    }

    #[test]
    fn set_then_read_round_trips_through_the_wire() {
        // The new verification rg did not need (Push exts were wire-tested via
        // the data-forward path): prove the stamped ext_nodeid survives the
        // Declare codec encode -> decode. The Declare extension path was never
        // exercised before (every build_declare_* used extensions: None), so
        // this pins that the generated codec round-trips it byte-faithfully and
        // in zenoh's exts-before-body order.
        use sce_forge_runtime::codec::SceCursor;
        use wz_codecs::declare::Declare;
        use wz_codecs_test_support::TestWire;

        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        let bytes = d.wire();

        let mut cursor = SceCursor::new(&bytes);
        let decoded = Declare::decode(&mut cursor)
            .and_then(|x| x.try_into_owned())
            .expect("decode declare");
        assert_eq!(
            read_declare_source(&decoded),
            7,
            "ext_nodeid survived the wire round-trip"
        );
        // The declaration body survived intact alongside the ext.
        assert!(
            matches!(
                decoded.body,
                wz_codecs::declare::DeclareOwnedVariant::CodecZenohDeclSubscriber(_)
            ),
            "the DeclareSubscriber body is preserved"
        );
    }

    /// c3c-3 debt C2 — golden-vector byte-parity: a sourced
    /// `Declare(DeclareSubscriber)` with a Declare-level `ext_nodeid` encodes to
    /// the EXACT zenoh wire. Pins the `zextz64!(0x3)` ext header (`0x33`) + its
    /// VLE body and its placement (the Declare-level ext chain, between the
    /// header and the body), where the prior round-trip test checked only that
    /// the value survives. The ext encode is DERIVED from the zenoh-pico encoder
    /// source `_z_msg_ext_encode_zint` (`src/protocol/codec/ext.c`: header byte
    /// then a VLE `node_id`) — not captured from a live peer, the capture-based
    /// cross-check being the tracked interop gap — the field order from
    /// `commons/zenoh-codec/src/network/declare.rs` (exts before body), and the
    /// DeclSubscriber body from the `build_declare_subscriber` literal golden in
    /// `declare_build`. Unlike the Push twin, this asserts a FULL literal vector.
    #[test]
    fn declare_with_nodeid_matches_zenoh_golden_bytes() {
        use crate::declare_build::build_declare_subscriber;
        use wz_codecs_test_support::TestWire;

        let mut d = build_declare_subscriber(0, 0, Some("demo/sub")).expect("build declare sub");
        set_declare_source(&mut d, 7);
        let mut expected = vec![
            0x9E, // Declare header: N_MID_DECLARE 0x1E | Z 0x80 (ext chain present)
            // R311y801 — the builder's ext_qos leads the chain, which is also
            // zenoh's write order (qos, tstamp, nodeid — zenoh-codec
            // declare.rs:118-129), so this vector gained two bytes rather than
            // changing shape.
            0xA1, // ext_qos header: id 0x01 | ENC_Z64 0x20 | Z 0x80 (more follows)
            0x08, // QoSType::DECLARE -> Priority::Control | nodrop -> VLE(8)
            0x33, // ext_nodeid header: id 0x3 | M 0x10 | ENC_Z64 0x20 (terminal, Z clear)
            0x07, // node_id 7 -> VLE(7)
            0x62, // DeclSubscriber header: MID 0x02 | N 0x20 | M 0x40 (derived)
            0x00, // subscriber_id 0 -> VLE
            0x00, // wireexpr mapping id 0 -> VLE (literal sentinel)
            0x08, // wireexpr suffix_len 8 -> VLE
        ];
        expected.extend_from_slice(b"demo/sub");
        assert_eq!(
            d.wire(),
            expected,
            "Declare + ext_nodeid wire must match the zenoh golden byte-for-byte",
        );
    }
}
