// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! Declare routing-context source `node_id` (P4 routing, linkstate port step
//! c3c-3 atom3a) — the control-plane forward seam naming the tree-root a
//! linkstate-peer floods a SOURCED subscription declaration along. The
//! Declare twin of [`push_routing_context`](crate::push_routing_context).
//!
//! zenoh carries a sourced `DeclareSubscriber`'s routing SOURCE as the
//! Declare `ext_nodeid` extension — the SAME `zextz64!(0x3, true)` mandatory
//! `Z64` extension Push uses (`commons/zenoh-protocol/src/network/declare.rs`
//! `pub type NodeId = zextz64!(0x3, true)`, identical id to `push.rs`).
//! `node_id == 0` is the DEFAULT ("generated by the sending node itself",
//! omitted on the wire); a non-zero id names the source peer's `psid` in the
//! receiver's link space, resolved on receipt exactly as `forward_push`
//! resolves a Push's source. The subscription-propagation driver (c3c-3
//! atom3b) reads this to register the interested peer and re-flood the
//! declaration along the source's tree; this module is the read/build seam
//! for that one field.
//!
//! Wire: zenoh writes the Declare extensions BETWEEN the optional
//! `interest_id` and the declaration body (`commons/zenoh-codec/src/network/
//! declare.rs:117-132` — exts before body, unlike most network messages),
//! gated by the Declare header `Z` bit (`declare::flag::Z = 0x80`). The wz
//! codec mirrors that order, so a stamped `ext_nodeid` round-trips
//! byte-faithfully (the `set_then_read_round_trips_through_the_wire` test
//! pins it). The ext header itself is identical to Push's `ext_nodeid`:
//! `id(0x3) | M(0x10) | Z64(0x20) = 0x33` terminal, `FLAG_Z(0x80)` when
//! another ext follows.
//!
//! The `ext_nodeid` id / flags / chain edit + `node_id` read/build live in the
//! shared [`ext_nodeid`](crate::ext_nodeid) SSOT (R311ru consolidated the prior
//! triplication across `push_build` / `push_routing_context` / this module).
//! This module keeps ONLY the Declare-level header `Z` sync — the one field
//! that differs from the Push twin.

use wz_codecs::declare::DeclareOwned;

use crate::ext_nodeid;

/// The Declare-level header `Z` bit (zenoh `declare::flag::Z = 1 << 7`): the
/// extension chain is present. Identical bit to Push's header `Z`, but on the
/// Declare struct — the ONE field that differs from the Push twin; every other
/// part of the edit lives in the shared [`ext_nodeid`](crate::ext_nodeid) SSOT.
const DECLARE_FLAG_Z: u8 = 0x80;

/// Read the routing-context source `node_id` from a Declare's `ext_nodeid`
/// extension. Returns `0` when absent — zenoh's self-originated DEFAULT, so a
/// forwarder treats `0` as "the inbound neighbour is the source". Delegates to
/// the shared [`ext_nodeid::read_source`](crate::ext_nodeid::read_source).
pub fn read_declare_source(declare: &DeclareOwned) -> u16 {
    ext_nodeid::read_source(declare.extensions.as_ref())
}

/// Set the routing-context source `node_id` on a Declare's `ext_nodeid`
/// extension (`node_id == 0` removes it — zenoh's omit-on-DEFAULT). The shared
/// [`ext_nodeid::set_source`](crate::ext_nodeid::set_source) owns the chain
/// edit (replace / remove / per-entry `Z` normalisation); this only syncs the
/// Declare-level header `Z` flag to the resulting chain.
pub fn set_declare_source(declare: &mut DeclareOwned, node_id: u16) {
    if ext_nodeid::set_source(&mut declare.extensions, node_id) {
        declare.header |= DECLARE_FLAG_Z;
    } else {
        declare.header &= !DECLARE_FLAG_Z;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::declare_build::build_declare_subscriber;
    use crate::ext_nodeid::{EXT_ENC_Z64, EXT_FLAG_Z};
    use alloc::vec;
    use wz_codecs::ext_entry::{ExtEntryOwned, ExtEntryOwnedVariant};
    use wz_codecs::ext_zint::ExtZint;

    /// A sourced literal-keyexpr DeclareSubscriber (`id == 0`, the zenoh
    /// sourced-subscription sentinel; literal keyexpr via mapping id 0).
    fn declare_sub() -> DeclareOwned {
        build_declare_subscriber(0, 0, Some("demo/sub")).expect("build declare sub")
    }

    /// A non-nodeid ext (id 0x1, Z64) to exercise chain coexistence — a
    /// stand-in for the QoS/timestamp exts that ride alongside ext_nodeid.
    fn other_ext() -> ExtEntryOwned {
        ExtEntryOwned {
            header: 0x01 | EXT_ENC_Z64,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value: 5 }),
        }
    }

    #[test]
    fn absent_ext_reads_as_self_originated_zero() {
        let d = declare_sub();
        assert!(
            d.extensions.is_none(),
            "builder emits no Declare-level exts"
        );
        assert_eq!(read_declare_source(&d), 0);
    }

    #[test]
    fn set_then_read_round_trips() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        assert_eq!(read_declare_source(&d), 7);
    }

    #[test]
    fn nodeid_header_is_id_mandatory_z64_terminal() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        let exts = d.extensions.as_ref().expect("ext present after set");
        assert_eq!(exts.len(), 1, "only the nodeid ext");
        // 0x03 (id) | 0x10 (M) | 0x20 (Z64), Z clear (sole / last entry).
        assert_eq!(exts[0].header, 0x33);
        // Declare-level Z bit set because a chain is now present.
        assert_eq!(d.header & DECLARE_FLAG_Z, DECLARE_FLAG_Z);
    }

    #[test]
    fn set_zero_removes_the_ext() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        set_declare_source(&mut d, 0);
        assert_eq!(read_declare_source(&d), 0);
        assert!(d.extensions.is_none(), "the sole ext is dropped to None");
        assert_eq!(d.header & DECLARE_FLAG_Z, 0, "Declare Z bit cleared");
    }

    #[test]
    fn set_replaces_an_existing_nodeid() {
        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        set_declare_source(&mut d, 9);
        assert_eq!(read_declare_source(&d), 9);
        let exts = d.extensions.as_ref().expect("ext present");
        assert_eq!(exts.len(), 1, "replaced, not duplicated");
    }

    #[test]
    fn coexists_with_another_ext_and_fixes_chain_z_bits() {
        let mut d = declare_sub();
        // Seed a pre-existing (non-nodeid) extension.
        d.extensions = Some(vec![other_ext()]);
        d.header |= DECLARE_FLAG_Z;

        set_declare_source(&mut d, 7);
        let exts = d.extensions.as_ref().expect("chain present");
        assert_eq!(exts.len(), 2, "other ext kept, nodeid appended");
        // The non-last entry carries the continuation bit; nodeid terminates.
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64 | EXT_FLAG_Z);
        assert_eq!(exts[1].header, 0x33);
        assert_eq!(read_declare_source(&d), 7);

        // Removing the nodeid leaves the other ext as a terminal entry.
        set_declare_source(&mut d, 0);
        let exts = d.extensions.as_ref().expect("other ext remains");
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64, "Z bit cleared (last)");
        assert_eq!(
            d.header & DECLARE_FLAG_Z,
            DECLARE_FLAG_Z,
            "chain still present"
        );
    }

    #[test]
    fn set_then_read_round_trips_through_the_wire() {
        // The new verification rg did not need (Push exts were wire-tested via
        // the data-forward path): prove the stamped ext_nodeid survives the
        // Declare codec encode -> decode. The Declare extension path was never
        // exercised before (every build_declare_* used extensions: None), so
        // this pins that the generated codec round-trips it byte-faithfully and
        // in zenoh's exts-before-body order.
        use sce_forge_runtime::codec::SceCursor;
        use wz_codecs::declare::Declare;
        use wz_codecs_test_support::TestWire;

        let mut d = declare_sub();
        set_declare_source(&mut d, 7);
        let bytes = d.wire();

        let mut cursor = SceCursor::new(&bytes);
        let decoded = Declare::decode(&mut cursor)
            .and_then(|x| x.try_into_owned())
            .expect("decode declare");
        assert_eq!(
            read_declare_source(&decoded),
            7,
            "ext_nodeid survived the wire round-trip"
        );
        // The declaration body survived intact alongside the ext.
        assert!(
            matches!(
                decoded.body,
                wz_codecs::declare::DeclareOwnedVariant::CodecZenohDeclSubscriber(_)
            ),
            "the DeclareSubscriber body is preserved"
        );
    }
}
