// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! Shared `ext_nodeid` routing-context chain codec — the SINGLE source of
//! truth for the `zextz64!(0x3, true)` NodeId extension that BOTH Push and
//! Declare carry (P4 routing), and for the per-entry chain-continuation
//! `Z`-bit invariant any owned extension chain re-encodes under.
//!
//! Consolidates what were three byte-identical copies of this logic
//! (`push_build`'s chain-Z helper, [`push_routing_context`](crate::push_routing_context),
//! [`declare_routing_context`](crate::declare_routing_context)). The carrier
//! modules keep ONLY the one-line message-header `Z` sync, because that header
//! field is the one thing that genuinely differs per message type (the Push
//! header `Z` vs the Declare header `Z` live at the same bit but on different
//! structs). Everything else — the ext id / flags, the `node_id` read/build,
//! and the chain-bit normalisation — lives here once.
//!
//! Wire (zenoh ext header `iext`): the `ext_nodeid` header byte is
//! `id (0x3) | FLAG_M (0x10) | ENC_Z64 (0x20) = 0x33` for a terminal entry,
//! plus `FLAG_Z (0x80)` when another extension follows. The body is the
//! `Z64`-encoded `node_id` (u16). `node_id == 0` is zenoh's DEFAULT
//! ("generated by the sending node itself") and is OMITTED on the wire.

use alloc::vec::Vec;

use wz_codecs::ext_entry::{ExtEntryOwned, ExtEntryOwnedVariant};
use wz_codecs::ext_zint::ExtZint;

/// The `ext_nodeid` extension id — zenoh Push/Declare `NodeId`,
/// `zextz64!(0x3, true)` (the id is identical for both messages).
pub const NODEID_EXT_ID: u8 = 0x03;
/// Mandatory flag, zenoh `iext::FLAG_M` (bit 4).
pub const EXT_FLAG_M: u8 = 0x10;
/// `Z64` encoding, zenoh `iext::ENC_Z64` (bits 5-6) — the `node_id` rides a
/// zint body.
pub const EXT_ENC_Z64: u8 = 0x20;
/// Chain-continuation flag, zenoh `iext::FLAG_Z` (bit 7): another extension
/// follows this one.
pub const EXT_FLAG_Z: u8 = 0x80;
/// The `ext_nodeid` header with no further extension following: `id | M |
/// Z64` = `0x33`.
pub const NODEID_EXT_HEADER: u8 = NODEID_EXT_ID | EXT_FLAG_M | EXT_ENC_Z64;

/// The extension id field (bits 0-3) of a header byte — zenoh `iext::mid`,
/// dropping the mandatory / encoding / chain flags.
fn ext_id(header: u8) -> u8 {
    header & 0x0F
}

/// Set the chain-continuation `Z` bit on every entry except the last (which
/// terminates the chain) — zenoh's per-entry `FLAG_Z` invariant. The single
/// owner of this normalisation for every owned ext chain.
pub fn apply_chain_z_bits(entries: &mut [ExtEntryOwned]) {
    if entries.is_empty() {
        return;
    }
    let last = entries.len() - 1;
    for (i, entry) in entries.iter_mut().enumerate() {
        entry.header = if i == last {
            entry.header & !EXT_FLAG_Z
        } else {
            entry.header | EXT_FLAG_Z
        };
    }
}

/// Read the routing-context source `node_id` from an extension chain. Returns
/// `0` when the `ext_nodeid` is absent — zenoh's DEFAULT, meaning the message
/// was originated by the SENDING node itself, so a forwarder treats `0` as
/// "the inbound neighbour is the source".
pub fn read_source(exts: Option<&Vec<ExtEntryOwned>>) -> u16 {
    let Some(exts) = exts else {
        return 0;
    };
    for ext in exts {
        if ext_id(ext.header) == NODEID_EXT_ID {
            if let ExtEntryOwnedVariant::CodecZenohExtZint(z) = &ext.body {
                return z.value as u16;
            }
        }
    }
    0
}

/// Set / replace / remove the `ext_nodeid` in an extension chain, mirroring
/// zenoh's omit-on-DEFAULT encoding: `node_id == 0` (the "self-originated"
/// default) REMOVES it, a non-zero id inserts or replaces it. The per-entry
/// chain-continuation `Z` bits are normalised, and an emptied chain collapses
/// to `None`. Returns whether the chain is now NON-EMPTY, so the caller can
/// sync its message-level header `Z` flag (the one field that differs per
/// message type — Push header vs Declare header).
pub fn set_source(exts: &mut Option<Vec<ExtEntryOwned>>, node_id: u16) -> bool {
    // Replace semantics: drop any existing ext_nodeid before (maybe) re-adding.
    if let Some(list) = exts.as_mut() {
        list.retain(|e| ext_id(e.header) != NODEID_EXT_ID);
    }
    if node_id != 0 {
        let entry = ExtEntryOwned {
            header: NODEID_EXT_HEADER,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint {
                value: node_id as u64,
            }),
        };
        exts.get_or_insert_with(Vec::new).push(entry);
    }
    let empty = exts.as_ref().map(|l| l.is_empty()).unwrap_or(true);
    if empty {
        *exts = None;
        false
    } else {
        apply_chain_z_bits(exts.as_mut().expect("non-empty => Some"));
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    fn nodeid_ext(value: u64) -> ExtEntryOwned {
        ExtEntryOwned {
            header: NODEID_EXT_HEADER,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value }),
        }
    }

    fn other_ext() -> ExtEntryOwned {
        ExtEntryOwned {
            header: 0x01 | EXT_ENC_Z64,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value: 5 }),
        }
    }

    #[test]
    fn read_absent_is_zero() {
        assert_eq!(read_source(None), 0);
        assert_eq!(read_source(Some(&vec![other_ext()])), 0);
    }

    #[test]
    fn set_inserts_terminal_nodeid_and_reports_present() {
        let mut exts = None;
        assert!(set_source(&mut exts, 7), "chain now non-empty");
        let list = exts.as_ref().expect("ext present");
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].header, 0x33, "id | M | Z64, Z clear (terminal)");
        assert_eq!(read_source(exts.as_ref()), 7);
    }

    #[test]
    fn set_zero_removes_and_reports_empty() {
        let mut exts = Some(vec![nodeid_ext(7)]);
        assert!(!set_source(&mut exts, 0), "chain now empty");
        assert!(exts.is_none());
        assert_eq!(read_source(exts.as_ref()), 0);
    }

    #[test]
    fn set_replaces_existing_nodeid() {
        let mut exts = Some(vec![nodeid_ext(7)]);
        assert!(set_source(&mut exts, 9));
        let list = exts.as_ref().expect("present");
        assert_eq!(list.len(), 1, "replaced, not duplicated");
        assert_eq!(read_source(exts.as_ref()), 9);
    }

    #[test]
    fn coexists_with_another_ext_and_normalises_chain_bits() {
        let mut exts = Some(vec![other_ext()]);
        assert!(set_source(&mut exts, 7));
        let list = exts.as_ref().expect("chain present");
        assert_eq!(list.len(), 2, "other ext kept, nodeid appended");
        assert_eq!(
            list[0].header,
            0x01 | EXT_ENC_Z64 | EXT_FLAG_Z,
            "non-last Z set"
        );
        assert_eq!(list[1].header, 0x33, "nodeid terminal");

        assert!(
            set_source(&mut exts, 0),
            "still non-empty (other ext remains)"
        );
        let list = exts.as_ref().expect("other ext remains");
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].header, 0x01 | EXT_ENC_Z64, "Z cleared (now last)");
    }
}
