// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! Push routing-context source `node_id` (P4 routing, linkstate port step
//! c3c-1) — the data-plane forward seam for the tree-root a linkstate-peer
//! floods a message along.
//!
//! zenoh carries the data-plane routing SOURCE as the Push `ext_nodeid`
//! extension (`commons/zenoh-protocol/src/network/push.rs:64`,
//! `zextz64!(0x3, true)`): a MANDATORY `Z64` extension whose `node_id` (u16)
//! names the source node — the root of the spanning tree the message floods
//! along. `node_id == 0` is the DEFAULT and means "generated by the sending
//! node itself" (`network/mod.rs:576`): an originator stamps 0, and each
//! transit hop remaps it into the next link's `psid` space. A peer forwarding
//! a Push reads this to pick `tree_children_of(source)` (the loop-free flood,
//! the c3c-2 atom); this module is the read/build seam for that one field.
//!
//! Wire (zenoh ext header, `commons/zenoh-protocol/src/common/extension.rs`
//! `iext`): the header byte is `id (bits 0-3) | FLAG_M (1<<4) | ENC_Z64
//! (0b01<<5)`, plus `FLAG_Z (1<<7)` when another extension follows in the
//! chain. So a terminal `ext_nodeid` header is `0x03 | 0x10 | 0x20 = 0x33`,
//! and the body is the `Z64`-encoded `node_id`. The Push-level header `Z`
//! bit (`push.rs:21`, `0x80`) signals that the extension chain is present.

use wz_codecs::push::PushOwned;

use crate::ext_nodeid;

/// The Push-level header `Z` bit (zenoh `push.rs` `Z = 1 << 7`): the extension
/// chain is present. The ONE field that differs from the Declare twin — every
/// other part of the `ext_nodeid` edit lives in the shared
/// [`ext_nodeid`](crate::ext_nodeid) SSOT.
const PUSH_FLAG_Z: u8 = 0x80;

/// Read the routing-context source `node_id` from a Push's `ext_nodeid`
/// extension. Returns `0` when absent — zenoh's self-originated DEFAULT, so a
/// forwarder treats `0` as "the inbound neighbour is the source". Delegates to
/// the shared [`ext_nodeid::read_source`](crate::ext_nodeid::read_source).
pub fn read_push_source(push: &PushOwned) -> u16 {
    ext_nodeid::read_source(push.extensions.as_ref())
}

/// Set the routing-context source `node_id` on a Push's `ext_nodeid` extension
/// (`node_id == 0` removes it — zenoh's omit-on-DEFAULT). The shared
/// [`ext_nodeid::set_source`](crate::ext_nodeid::set_source) owns the chain
/// edit (replace / remove / per-entry `Z` normalisation); this only syncs the
/// Push-level header `Z` flag to the resulting chain.
pub fn set_push_source(push: &mut PushOwned, node_id: u16) {
    if ext_nodeid::set_source(&mut push.extensions, node_id) {
        push.header |= PUSH_FLAG_Z;
    } else {
        push.header &= !PUSH_FLAG_Z;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ext_nodeid::{EXT_ENC_Z64, EXT_FLAG_Z};
    use crate::push_build::build_push_literal;
    use alloc::vec;
    use wz_codecs::ext_entry::{ExtEntryOwned, ExtEntryOwnedVariant};
    use wz_codecs::ext_zint::ExtZint;

    fn push() -> PushOwned {
        build_push_literal("demo/c3c", b"v").expect("build push")
    }

    /// A non-nodeid ext (id 0x1, Z64) to exercise chain coexistence — a
    /// stand-in for the QoS/timestamp exts that ride alongside ext_nodeid.
    fn other_ext() -> ExtEntryOwned {
        ExtEntryOwned {
            header: 0x01 | EXT_ENC_Z64,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value: 5 }),
        }
    }

    #[test]
    fn absent_ext_reads_as_self_originated_zero() {
        let p = push();
        assert!(p.extensions.is_none(), "builder emits no Push-level exts");
        assert_eq!(read_push_source(&p), 0);
    }

    #[test]
    fn set_then_read_round_trips() {
        let mut p = push();
        set_push_source(&mut p, 7);
        assert_eq!(read_push_source(&p), 7);
    }

    #[test]
    fn nodeid_header_is_id_mandatory_z64_terminal() {
        let mut p = push();
        set_push_source(&mut p, 7);
        let exts = p.extensions.as_ref().expect("ext present after set");
        assert_eq!(exts.len(), 1, "only the nodeid ext");
        // 0x03 (id) | 0x10 (M) | 0x20 (Z64), Z clear (sole / last entry).
        assert_eq!(exts[0].header, 0x33);
        // Push-level Z bit set because a chain is now present.
        assert_eq!(p.header & PUSH_FLAG_Z, PUSH_FLAG_Z);
    }

    #[test]
    fn set_zero_removes_the_ext() {
        let mut p = push();
        set_push_source(&mut p, 7);
        set_push_source(&mut p, 0);
        assert_eq!(read_push_source(&p), 0);
        assert!(p.extensions.is_none(), "the sole ext is dropped to None");
        assert_eq!(p.header & PUSH_FLAG_Z, 0, "Push Z bit cleared");
    }

    #[test]
    fn set_replaces_an_existing_nodeid() {
        let mut p = push();
        set_push_source(&mut p, 7);
        set_push_source(&mut p, 9);
        assert_eq!(read_push_source(&p), 9);
        let exts = p.extensions.as_ref().expect("ext present");
        assert_eq!(exts.len(), 1, "replaced, not duplicated");
    }

    #[test]
    fn coexists_with_another_ext_and_fixes_chain_z_bits() {
        let mut p = push();
        // Seed a pre-existing (non-nodeid) extension.
        p.extensions = Some(vec![other_ext()]);
        p.header |= PUSH_FLAG_Z;

        set_push_source(&mut p, 7);
        let exts = p.extensions.as_ref().expect("chain present");
        assert_eq!(exts.len(), 2, "other ext kept, nodeid appended");
        // The non-last entry carries the continuation bit; nodeid terminates.
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64 | EXT_FLAG_Z);
        assert_eq!(exts[1].header, 0x33);
        assert_eq!(read_push_source(&p), 7);

        // Removing the nodeid leaves the other ext as a terminal entry.
        set_push_source(&mut p, 0);
        let exts = p.extensions.as_ref().expect("other ext remains");
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64, "Z bit cleared (last)");
        assert_eq!(p.header & PUSH_FLAG_Z, PUSH_FLAG_Z, "chain still present");
    }

    /// c3c-3 debt C2 — golden-vector byte-parity: a Push with an `ext_nodeid`
    /// encodes to the EXACT zenoh wire. Differenced against the SAME Push with no
    /// ext, so the body (`msg_put`) bytes are derived (not hand-rolled): adding
    /// `ext_nodeid` must set the Push header `Z` bit and insert the `[0x33, VLE]`
    /// ext chain AFTER the wireexpr, leaving the body byte-identical (just
    /// shifted). Pins the `zextz64!(0x3)` ext encoding (confirmed vs zenoh-pico
    /// `_z_msg_ext_encode_zint`) and its Push placement (the Push-level ext chain
    /// sits between the wireexpr and the body, per `push.rs` field order). The
    /// prior `set_then_read_round_trips` checked only value-survival.
    #[test]
    fn push_with_nodeid_matches_zenoh_golden_bytes() {
        use wz_codecs_test_support::TestWire;

        let base_wire = build_push_literal("demo/c3c", b"v").expect("build").wire();
        let mut p = build_push_literal("demo/c3c", b"v").expect("build");
        set_push_source(&mut p, 7);
        let wire = p.wire();

        // header(1) + literal wireexpr "demo/c3c" (mapping-id VLE + suffix_len VLE
        // + 8 suffix bytes = 10) -> the ext chain begins at byte 11.
        const EXT_OFFSET: usize = 1 + 10;
        assert_eq!(
            base_wire[0] & 0x80,
            0,
            "base Push carries no ext chain (Z clear)"
        );
        assert_eq!(
            wire[0],
            base_wire[0] | 0x80,
            "ext_nodeid sets the Push header Z bit"
        );
        assert_eq!(
            &wire[EXT_OFFSET..EXT_OFFSET + 2],
            &[0x33, 0x07],
            "ext_nodeid header 0x33 (id 0x3 | M | ENC_Z64) + VLE(7), after the wireexpr",
        );
        assert_eq!(
            &wire[EXT_OFFSET + 2..],
            &base_wire[EXT_OFFSET..],
            "the msg_put body is byte-identical, shifted past the inserted ext",
        );
    }
}
