// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! Push routing-context source `node_id` (P4 routing, linkstate port step
//! c3c-1) — the data-plane forward seam for the tree-root a linkstate-peer
//! floods a message along.
//!
//! zenoh carries the data-plane routing SOURCE as the Push `ext_nodeid`
//! extension (`commons/zenoh-protocol/src/network/push.rs:64`,
//! `zextz64!(0x3, true)`): a MANDATORY `Z64` extension whose `node_id` (u16)
//! names the source node — the root of the spanning tree the message floods
//! along. `node_id == 0` is the DEFAULT and means "generated by the sending
//! node itself" (`network/mod.rs:576`): an originator stamps 0, and each
//! transit hop remaps it into the next link's `psid` space. A peer forwarding
//! a Push reads this to pick `tree_children_of(source)` (the loop-free flood,
//! the c3c-2 atom); this module is the read/build seam for that one field.
//!
//! Wire (zenoh ext header, `commons/zenoh-protocol/src/common/extension.rs`
//! `iext`): the header byte is `id (bits 0-3) | FLAG_M (1<<4) | ENC_Z64
//! (0b01<<5)`, plus `FLAG_Z (1<<7)` when another extension follows in the
//! chain. So a terminal `ext_nodeid` header is `0x03 | 0x10 | 0x20 = 0x33`,
//! and the body is the `Z64`-encoded `node_id`. The Push-level header `Z`
//! bit (`push.rs:21`, `0x80`) signals that the extension chain is present.

use alloc::vec::Vec;

use wz_codecs::ext_entry::{ExtEntryOwned, ExtEntryOwnedVariant};
use wz_codecs::ext_zint::ExtZint;
use wz_codecs::push::PushOwned;

/// The `ext_nodeid` extension id (zenoh `Push::ext::NodeId`,
/// `zextz64!(0x3, true)`) — bits 0-3 of the extension header.
const NODEID_EXT_ID: u8 = 0x03;
/// Mandatory flag, zenoh `iext::FLAG_M` (bit 4): a receiver that does not
/// understand the extension must reject the message.
const EXT_FLAG_M: u8 = 0x10;
/// `Z64` encoding, zenoh `iext::ENC_Z64` (bits 5-6) — the `node_id` rides a
/// zint body.
const EXT_ENC_Z64: u8 = 0x20;
/// Chain-continuation flag, zenoh `iext::FLAG_Z` (bit 7): another extension
/// follows this one in the chain.
const EXT_FLAG_Z: u8 = 0x80;
/// The `ext_nodeid` header with no further extension following: `id | M |
/// Z64` = `0x33`. `apply_chain_z_bits` re-adds `FLAG_Z` when it is not last.
const NODEID_EXT_HEADER: u8 = NODEID_EXT_ID | EXT_FLAG_M | EXT_ENC_Z64;
/// The Push-level header `Z` bit (zenoh `push.rs` `Z = 1 << 7`): the
/// extension chain is present.
const PUSH_FLAG_Z: u8 = 0x80;

/// The extension id field (bits 0-3) of a header byte — zenoh `iext::mid`,
/// dropping the mandatory / encoding / chain flags.
fn ext_id(header: u8) -> u8 {
    header & 0x0F
}

/// Set the chain-continuation `Z` bit on every entry except the last (which
/// terminates the chain) — zenoh's per-entry `FLAG_Z` invariant
/// (`push_build::apply_chain_z_bits`, replicated so this module is the
/// self-contained owner of the `ext_nodeid` chain edits).
fn apply_chain_z_bits(entries: &mut [ExtEntryOwned]) {
    if entries.is_empty() {
        return;
    }
    let last = entries.len() - 1;
    for (i, entry) in entries.iter_mut().enumerate() {
        if i == last {
            entry.header &= !EXT_FLAG_Z;
        } else {
            entry.header |= EXT_FLAG_Z;
        }
    }
}

/// Read the routing-context source `node_id` from a Push's `ext_nodeid`
/// extension. Returns `0` when the extension is absent — zenoh's DEFAULT,
/// meaning the message was originated by the SENDING node itself — so a
/// forwarder treats `0` as "the inbound neighbour is the source".
pub fn read_push_source(push: &PushOwned) -> u16 {
    let Some(exts) = push.extensions.as_ref() else {
        return 0;
    };
    for ext in exts {
        if ext_id(ext.header) == NODEID_EXT_ID {
            if let ExtEntryOwnedVariant::CodecZenohExtZint(z) = &ext.body {
                return z.value as u16;
            }
        }
    }
    0
}

/// Set the routing-context source `node_id` on a Push's `ext_nodeid`
/// extension, mirroring zenoh's omit-on-DEFAULT encoding: `node_id == 0`
/// (the "self-originated" default) REMOVES the extension, a non-zero id
/// inserts or replaces it. The per-entry chain-continuation `Z` bits and the
/// Push-level header `Z` flag are kept consistent with the resulting chain,
/// so the carrier re-encodes correctly whether or not other extensions
/// (QoS, timestamp) coexist.
pub fn set_push_source(push: &mut PushOwned, node_id: u16) {
    // Replace semantics: drop any existing ext_nodeid before (maybe) re-adding.
    if let Some(exts) = push.extensions.as_mut() {
        exts.retain(|e| ext_id(e.header) != NODEID_EXT_ID);
    }
    if node_id != 0 {
        let entry = ExtEntryOwned {
            header: NODEID_EXT_HEADER,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint {
                value: node_id as u64,
            }),
        };
        push.extensions.get_or_insert_with(Vec::new).push(entry);
    }
    // Normalise the chain: an empty list collapses to `None` (Push `Z` clear);
    // a non-empty list fixes the per-entry continuation bits and sets Push `Z`.
    let empty = match push.extensions.as_ref() {
        Some(exts) => exts.is_empty(),
        None => true,
    };
    if empty {
        push.extensions = None;
        push.header &= !PUSH_FLAG_Z;
    } else {
        apply_chain_z_bits(push.extensions.as_mut().expect("non-empty => Some"));
        push.header |= PUSH_FLAG_Z;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::push_build::build_push_literal;
    use alloc::vec;

    fn push() -> PushOwned {
        build_push_literal("demo/c3c", b"v").expect("build push")
    }

    /// A non-nodeid ext (id 0x1, Z64) to exercise chain coexistence — a
    /// stand-in for the QoS/timestamp exts that ride alongside ext_nodeid.
    fn other_ext() -> ExtEntryOwned {
        ExtEntryOwned {
            header: 0x01 | EXT_ENC_Z64,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value: 5 }),
        }
    }

    #[test]
    fn absent_ext_reads_as_self_originated_zero() {
        let p = push();
        assert!(p.extensions.is_none(), "builder emits no Push-level exts");
        assert_eq!(read_push_source(&p), 0);
    }

    #[test]
    fn set_then_read_round_trips() {
        let mut p = push();
        set_push_source(&mut p, 7);
        assert_eq!(read_push_source(&p), 7);
    }

    #[test]
    fn nodeid_header_is_id_mandatory_z64_terminal() {
        let mut p = push();
        set_push_source(&mut p, 7);
        let exts = p.extensions.as_ref().expect("ext present after set");
        assert_eq!(exts.len(), 1, "only the nodeid ext");
        // 0x03 (id) | 0x10 (M) | 0x20 (Z64), Z clear (sole / last entry).
        assert_eq!(exts[0].header, 0x33);
        // Push-level Z bit set because a chain is now present.
        assert_eq!(p.header & PUSH_FLAG_Z, PUSH_FLAG_Z);
    }

    #[test]
    fn set_zero_removes_the_ext() {
        let mut p = push();
        set_push_source(&mut p, 7);
        set_push_source(&mut p, 0);
        assert_eq!(read_push_source(&p), 0);
        assert!(p.extensions.is_none(), "the sole ext is dropped to None");
        assert_eq!(p.header & PUSH_FLAG_Z, 0, "Push Z bit cleared");
    }

    #[test]
    fn set_replaces_an_existing_nodeid() {
        let mut p = push();
        set_push_source(&mut p, 7);
        set_push_source(&mut p, 9);
        assert_eq!(read_push_source(&p), 9);
        let exts = p.extensions.as_ref().expect("ext present");
        assert_eq!(exts.len(), 1, "replaced, not duplicated");
    }

    #[test]
    fn coexists_with_another_ext_and_fixes_chain_z_bits() {
        let mut p = push();
        // Seed a pre-existing (non-nodeid) extension.
        p.extensions = Some(vec![other_ext()]);
        p.header |= PUSH_FLAG_Z;

        set_push_source(&mut p, 7);
        let exts = p.extensions.as_ref().expect("chain present");
        assert_eq!(exts.len(), 2, "other ext kept, nodeid appended");
        // The non-last entry carries the continuation bit; nodeid terminates.
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64 | EXT_FLAG_Z);
        assert_eq!(exts[1].header, 0x33);
        assert_eq!(read_push_source(&p), 7);

        // Removing the nodeid leaves the other ext as a terminal entry.
        set_push_source(&mut p, 0);
        let exts = p.extensions.as_ref().expect("other ext remains");
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64, "Z bit cleared (last)");
        assert_eq!(p.header & PUSH_FLAG_Z, PUSH_FLAG_Z, "chain still present");
    }
}
