// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! Request routing-context source `node_id` (P4 routing, query-routing atom
//! 2a) — the seam naming the spanning-tree root a linkstate-peer relays a
//! ROUTED Query (`Request`) along, toward the matching queryables. The
//! `Request` twin of [`push_routing_context`](crate::push_routing_context) and
//! [`declare_routing_context`](crate::declare_routing_context).
//!
//! zenoh carries a routed Query's routing SOURCE as the Request `ext_nodeid`
//! extension — the SAME `zextz64!(0x3, true)` mandatory `Z64` extension Push
//! and Declare use (`commons/zenoh-protocol/src/network/request.rs`
//! `ext_nodeid: ext::NodeIdType`, identical id to `push.rs` / `declare.rs`).
//! `node_id == 0` is the DEFAULT ("generated by the sending node itself",
//! omitted on the wire); a non-zero id names the source (querier) peer's `psid`
//! in the receiver's link space, resolved on receipt exactly as `forward_push`
//! resolves a Push's source — so a relayed Query routes along the QUERIER's
//! tree toward the queryable, not the relaying neighbour's. The query-routing
//! driver (atom 2b) reads this to route the Request toward the interested
//! queryables; this module is the read/build seam for that one field.
//!
//! Wire: the Request extensions ride BETWEEN the `keyexpr` and the body
//! (`RequestOwned { header, rid, keyexpr, extensions, body }`), gated by the
//! Request header `Z` bit (zenoh `request::flag::Z = 1 << 7 = 0x80`,
//! `request.rs:25`). The wz codec decodes the chain only when `header & 0x80`,
//! so a stamped `ext_nodeid` SURVIVES the encode -> decode round-trip (the
//! `set_then_read_round_trips_through_the_wire` test pins it; the body survives
//! alongside). That is value-survival, not byte-parity against a zenoh golden
//! vector — the golden-vector compare is a tracked gap, the same as on the Push
//! side. The `ext_nodeid` id / flags / chain edit + `node_id` read/build live
//! in the shared [`ext_nodeid`](crate::ext_nodeid) SSOT; this module keeps ONLY
//! the Request-level header `Z` sync — the one field that differs from the Push
//! / Declare twins.

use wz_codecs::request::RequestOwned;

use crate::ext_nodeid;
use crate::query_mode::{QueryTarget, TARGET_EXT_ID};

/// Read the routing-context source `node_id` from a Request's `ext_nodeid`
/// extension. Returns `0` when absent — zenoh's self-originated DEFAULT, so a
/// forwarder treats `0` as "the inbound neighbour is the source". Delegates to
/// the shared [`ext_nodeid::read_source`](crate::ext_nodeid::read_source).
pub fn read_request_source(request: &RequestOwned) -> u16 {
    ext_nodeid::read_source(request.extensions.as_ref())
}

/// Set the routing-context source `node_id` on a Request's `ext_nodeid`
/// extension (`node_id == 0` removes it — zenoh's omit-on-DEFAULT). The shared
/// [`ext_nodeid::set_source`](crate::ext_nodeid::set_source) owns the chain
/// edit (replace / remove / per-entry `Z` normalisation); this only syncs the
/// Request-level header `Z` flag to the resulting chain.
pub fn set_request_source(request: &mut RequestOwned, node_id: u16) {
    let present = ext_nodeid::set_source(&mut request.extensions, node_id);
    ext_nodeid::sync_header_z(&mut request.header, present);
}

/// Read the [`QueryTarget`] a routed Query carries in its `ext_target`
/// extension. Returns `None` when the ext is ABSENT (or carries the
/// never-transmitted `0 = BEST_MATCHING`) — zenoh-pico's omit-on-BEST_MATCHING
/// default (`ext_target = _ext_target != Z_QUERY_TARGET_BEST_MATCHING`,
/// `network.c`), so a forwarder treats absence as `BestMatching` (route to the
/// single nearest complete queryable, else All). The target ext is a zint over
/// the SAME `Z64` body the `ext_nodeid` reader decodes, so this is a thin
/// projection of the shared [`read_z64_ext`](crate::ext_nodeid::read_z64_ext)
/// over [`TARGET_EXT_ID`], mapped through [`QueryTarget::from_wire_byte`] — no
/// target-specific decoder.
pub fn read_request_target(request: &RequestOwned) -> Option<QueryTarget> {
    ext_nodeid::read_z64_ext(request.extensions.as_ref(), TARGET_EXT_ID)
        .and_then(QueryTarget::from_wire_byte)
}

/// The Request `ext_timeout` extension id — zenoh-pico's
/// `_Z_MSG_EXT_ENC_ZINT | 0x06` timeout slot (`network.c:150-155`), the SSOT
/// const the [`RequestQueryBuilder`](crate::request_build::RequestQueryBuilder)
/// writer and [`read_request_timeout_ms`] reader both key on.
pub const TIMEOUT_EXT_ID: u8 = 0x06;

/// Read the per-query timeout (milliseconds) a routed Query carries in its
/// `ext_timeout` extension — zenoh's `msg.ext_timeout`, which EVERY relay hop
/// honors when arming its pending-entry deadline (`route_query`,
/// `dispatcher/queries.rs:514`: `ext_timeout.unwrap_or(queries_default_timeout)`).
/// `None` when absent — the relay falls back to its configured default. A zint
/// over the same `Z64` body the target ext uses, so this is a thin projection of
/// the shared [`read_z64_ext`](crate::ext_nodeid::read_z64_ext) over
/// [`TIMEOUT_EXT_ID`].
pub fn read_request_timeout_ms(request: &RequestOwned) -> Option<u64> {
    ext_nodeid::read_z64_ext(request.extensions.as_ref(), TIMEOUT_EXT_ID)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ext_nodeid::{EXT_ENC_Z64, EXT_FLAG_Z, MESSAGE_FLAG_Z};
    use crate::request_build::build_request_query;
    use alloc::vec;
    use wz_codecs::ext_entry::{ExtEntryOwned, ExtEntryOwnedVariant};
    use wz_codecs::ext_zint::ExtZint;

    /// A routed Query Request (rid 42, literal keyexpr via mapping id 0) — the
    /// minimal builder emits no Request-level extensions (Z clear).
    fn request() -> RequestOwned {
        build_request_query(42, 0, Some("demo/q")).expect("build request query")
    }

    /// A non-nodeid ext (id 0x1, Z64) to exercise chain coexistence — a stand-in
    /// for the QoS/timestamp exts that ride alongside ext_nodeid.
    fn other_ext() -> ExtEntryOwned {
        ExtEntryOwned {
            header: 0x01 | EXT_ENC_Z64,
            body: ExtEntryOwnedVariant::CodecZenohExtZint(ExtZint { value: 5 }),
        }
    }

    #[test]
    fn absent_ext_reads_as_self_originated_zero() {
        let r = request();
        assert!(
            r.extensions.is_none(),
            "builder emits no Request-level exts"
        );
        assert_eq!(
            r.header & MESSAGE_FLAG_Z,
            0,
            "Z bit clear with no ext chain"
        );
        assert_eq!(read_request_source(&r), 0);
    }

    #[test]
    fn set_then_read_round_trips() {
        let mut r = request();
        set_request_source(&mut r, 7);
        assert_eq!(read_request_source(&r), 7);
    }

    #[test]
    fn nodeid_header_is_id_mandatory_z64_terminal() {
        let mut r = request();
        set_request_source(&mut r, 7);
        let exts = r.extensions.as_ref().expect("ext present after set");
        assert_eq!(exts.len(), 1, "only the nodeid ext");
        // 0x03 (id) | 0x10 (M) | 0x20 (Z64), Z clear (sole / last entry).
        assert_eq!(exts[0].header, 0x33);
        // Request-level Z bit set because a chain is now present.
        assert_eq!(r.header & MESSAGE_FLAG_Z, MESSAGE_FLAG_Z);
    }

    #[test]
    fn read_request_target_reads_the_ext_or_defaults_to_best_matching() {
        use crate::query_mode::QueryTarget;
        use crate::request_build::build_request_query_with_target;
        // A plain Query carries NO target ext -> BestMatching (the wire default).
        assert_eq!(
            read_request_target(&request()),
            None,
            "absent ext_target = BestMatching default",
        );
        // An explicit All / AllComplete survives the build and reads back.
        for t in [QueryTarget::All, QueryTarget::AllComplete] {
            let r = build_request_query_with_target(42, 0, Some("demo/q"), t).expect("build");
            assert_eq!(
                read_request_target(&r),
                Some(t),
                "explicit target reads back through the ext chain",
            );
        }
    }

    #[test]
    fn read_request_timeout_ms_reads_the_ext_or_none_when_absent() {
        use crate::request_build::build_request_query_with_timeout_ms;
        // A plain Query carries NO timeout ext -> None (relay uses its default).
        assert_eq!(
            read_request_timeout_ms(&request()),
            None,
            "absent ext_timeout = the relay's configured default",
        );
        // An explicit timeout survives the build and reads back — the value a
        // relay hop feeds its pending-entry deadline (zenoh queries.rs:514).
        let r = build_request_query_with_timeout_ms(42, 0, Some("demo/q"), 5_000).expect("build");
        assert_eq!(read_request_timeout_ms(&r), Some(5_000));
    }

    #[test]
    fn read_request_target_coexists_with_the_nodeid_ext() {
        // forward_request reads BOTH read_request_source and read_request_target
        // on the same Request: the readers key on the ext id (0x03 / 0x04), not
        // chain position, so a routed Query carrying BOTH reads each independently.
        use crate::query_mode::QueryTarget;
        use crate::request_build::build_request_query_with_target;
        let mut r =
            build_request_query_with_target(42, 0, Some("demo/q"), QueryTarget::AllComplete)
                .expect("build");
        set_request_source(&mut r, 7); // add the nodeid ext alongside the target ext
        assert_eq!(read_request_source(&r), 7, "the nodeid still reads");
        assert_eq!(
            read_request_target(&r),
            Some(QueryTarget::AllComplete),
            "the target still reads alongside the nodeid",
        );
    }

    #[test]
    fn set_zero_removes_the_ext() {
        let mut r = request();
        set_request_source(&mut r, 7);
        set_request_source(&mut r, 0);
        assert_eq!(read_request_source(&r), 0);
        assert!(r.extensions.is_none(), "the sole ext is dropped to None");
        assert_eq!(r.header & MESSAGE_FLAG_Z, 0, "Request Z bit cleared");
    }

    #[test]
    fn set_replaces_an_existing_nodeid() {
        let mut r = request();
        set_request_source(&mut r, 7);
        set_request_source(&mut r, 9);
        assert_eq!(read_request_source(&r), 9);
        let exts = r.extensions.as_ref().expect("ext present");
        assert_eq!(exts.len(), 1, "replaced, not duplicated");
    }

    #[test]
    fn coexists_with_another_ext_and_fixes_chain_z_bits() {
        let mut r = request();
        // Seed a pre-existing (non-nodeid) extension.
        r.extensions = Some(vec![other_ext()]);
        r.header |= MESSAGE_FLAG_Z;

        set_request_source(&mut r, 7);
        let exts = r.extensions.as_ref().expect("chain present");
        assert_eq!(exts.len(), 2, "other ext kept, nodeid appended");
        // The non-last entry carries the continuation bit; nodeid terminates.
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64 | EXT_FLAG_Z);
        assert_eq!(exts[1].header, 0x33);
        assert_eq!(read_request_source(&r), 7);

        // Removing the nodeid leaves the other ext as a terminal entry.
        set_request_source(&mut r, 0);
        let exts = r.extensions.as_ref().expect("other ext remains");
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].header, 0x01 | EXT_ENC_Z64, "Z bit cleared (last)");
        assert_eq!(r.header & MESSAGE_FLAG_Z, MESSAGE_FLAG_Z, "chain present");
    }

    #[test]
    fn set_then_read_round_trips_through_the_wire() {
        // Prove the stamped ext_nodeid survives the Request codec encode ->
        // decode, in zenoh's exts-after-keyexpr / before-body order. The Request
        // extension path is otherwise unexercised (the builders emit None), so
        // this pins that the generated codec round-trips it and preserves the
        // Query body alongside the ext.
        use sce_forge_runtime::codec::SceCursor;
        use wz_codecs::request::Request;
        use wz_codecs_test_support::TestWire;

        let mut r = request();
        set_request_source(&mut r, 7);
        let bytes = r.wire();

        let mut cursor = SceCursor::new(&bytes);
        let decoded = Request::decode(&mut cursor)
            .and_then(|x| x.try_into_owned())
            .expect("decode request");
        assert_eq!(
            read_request_source(&decoded),
            7,
            "ext_nodeid survived the wire round-trip"
        );
        assert_eq!(decoded.rid, 42, "the request id survived");
        assert!(
            matches!(
                decoded.body,
                wz_codecs::request::RequestOwnedVariant::CodecZenohQuery(_)
            ),
            "the Query body is preserved alongside the ext"
        );
    }
}
