// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! R2821 — the pin's stats REGISTRY: the node-wide collection model and the
//! OpenMetrics document it encodes, which is what a zenoh node built with
//! `stats` answers on `@/<zid>/<whatami>/metrics`.
//!
//! # Why this module exists — the body wz served was a different document
//!
//! At zenoh 1.10 the metrics leg under `stats` does not render per-session
//! counters at all. It encodes one runtime-wide registry
//! (`zenoh/src/net/runtime/adminspace.rs` @ `.encode_metrics(`), built in
//! `commons/zenoh-stats/src/registry.rs` @ `pub fn encode_metrics(`, whose
//! families are keyed by a LABEL SET and partitioned by TRANSPORT and LINK:
//! `zenoh_tx_bytes_total{local_id,local_whatami,protocol}`, a
//! `…_per_transport_…` twin carrying `remote_zid` / `remote_whatami` /
//! `remote_group` / `remote_cn` / `disconnected`, a `…_per_link_…` twin
//! carrying `src_locator` / `dst_locator`, payload HISTOGRAMS, and a per-key
//! histogram family. The block wz appended until this round
//! (`tx_bytes 140`, `tx_n_msgs{medium="net"}`) was the 1.5.0-era JSON field
//! names rendered as OpenMetrics — a document no pinned zenoh node emits.
//!
//! That one structural gap is the BASE under three residuals the
//! `adminspace-metrics` atom carried separately: the four query parameters
//! upstream honours (`per_transport` / `per_link` / `disconnected` /
//! `per_key`) had nothing to select, a mesh host had no counterpart to the
//! runtime-wide aggregate, and the per-transport partitions did not exist. All
//! three are partitions OF this registry, so they are built here once rather
//! than patched onto the flat body three times.
//!
//! # What is mirrored, and how it was measured
//!
//! Everything below is read from the pin and then CHECKED AGAINST IT: the test
//! module compares this encoder's output with documents the real `zenoh-stats`
//! crate (1.10.1, `prometheus-client` 0.24.1) produced for the same event
//! sequences, kept in `stats_registry/zenoh_1_10_1.golden` and regenerated by
//! `scripts/lib/zenoh_stats_golden.py`. The comparison is per descriptor block:
//! the descriptor sequence must match exactly and each block's sample lines must
//! match as a multiset, because upstream iterates `HashMap`s and its line order
//! within a block is not a property of the format.
//!
//! The collection rules that are easy to get wrong, each taken from
//! `commons/zenoh-stats/src/family.rs` @ `fn collect(&self)`:
//!
//! - the aggregate STARTS from the retired bucket (transports garbage-collected
//!   after their disconnection), which carries no transport labels;
//! - a transport that is disconnected but not yet collected is SKIPPED from the
//!   aggregate as well as from the per-transport block unless the query asks for
//!   `disconnected=true` — so a counter can fall when a peer leaves and rise
//!   again a minute later, which is upstream's behaviour and is kept;
//! - a per-link block is written only when some transport holds a link-scoped
//!   cell, while the per-transport descriptor is written whenever it is asked
//!   for, samples or not.
//!
//! # Deliberate divergences
//!
//! - Label values are ESCAPED (`\`, `"`, newline) where `prometheus-client`
//!   writes them raw. No value this registry is given contains those bytes in
//!   practice, so the output is identical; the escape only keeps a pathological
//!   locator or version from producing an invalid document. The build-info
//!   block has made the same choice since R2414.
//! - Histogram sums are kept as integers and converted to a float when written,
//!   where upstream converts each transport's sum before adding. The two agree
//!   while the total stays below 2^53 bytes; past that the last digit may differ.
//! - The ORDER of samples inside a block is deterministic here (label order,
//!   then registration order), where upstream's is hash order.

use alloc::collections::BTreeMap;
use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write as _;

use crate::qos::Priority;
use crate::stats::StatSpace;
use crate::WhatAmI;

/// Upstream's payload-size histogram bounds, in bytes
/// (`commons/zenoh-stats/src/histogram.rs` @ `pub const PAYLOAD_SIZE_BUCKETS`).
/// A final `+Inf` bucket follows them.
pub const PAYLOAD_SIZE_BUCKETS: [u64; 7] = [0, 1 << 5, 1 << 10, 1 << 15, 1 << 20, 1 << 25, 1 << 30];

/// The number of buckets a payload histogram carries: the bounds plus `+Inf`.
const BUCKET_COUNT: usize = PAYLOAD_SIZE_BUCKETS.len() + 1;

/// How long a disconnected transport keeps its own partition before its
/// counters are folded into the retired bucket
/// (`commons/zenoh-stats/src/family.rs` @ `const GARBAGE_COLLECTION_DELAY`).
pub const GARBAGE_COLLECTION_DELAY_MS: u64 = 60_000;

/// Which way a counted message travelled.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum StatsDirection {
    /// Sent by this node.
    Tx,
    /// Received by this node.
    Rx,
}

impl StatsDirection {
    /// Both directions, in the order upstream registers their families.
    pub const ALL: [StatsDirection; 2] = [StatsDirection::Tx, StatsDirection::Rx];

    /// The family-name prefix (`tx` / `rx`).
    pub const fn label(self) -> &'static str {
        match self {
            StatsDirection::Tx => "tx",
            StatsDirection::Rx => "rx",
        }
    }

    /// The verb upstream's help strings use for this direction.
    const fn action(self) -> &'static str {
        match self {
            StatsDirection::Tx => "sent",
            StatsDirection::Rx => "received",
        }
    }

    const fn index(self) -> usize {
        self as usize
    }
}

/// The network message kind a sample counts
/// (`commons/zenoh-stats/src/labels.rs` @ `pub enum MessageLabel`).
///
/// Not [`crate::stats::StatMessage`]: that axis is the JSON `_stats` schema's
/// four payload kinds, while this one is every network body — nine of them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum MessageLabel {
    /// A `Push` carrying a `Put`.
    Put,
    /// A `Push` carrying a `Del`.
    Del,
    /// A `Request`.
    Query,
    /// A `Response` carrying a `Reply`.
    Reply,
    /// A `Response` carrying an `Err`.
    ReplyErr,
    /// A `ResponseFinal`.
    ResponseFinal,
    /// An `Interest`.
    Interest,
    /// A `Declare`.
    Declare,
    /// An `OAM`.
    Oam,
}

impl MessageLabel {
    /// Upstream's label value.
    pub const fn label(self) -> &'static str {
        match self {
            MessageLabel::Put => "put",
            MessageLabel::Del => "delete",
            MessageLabel::Query => "query",
            MessageLabel::Reply => "reply",
            MessageLabel::ReplyErr => "reply-err",
            MessageLabel::ResponseFinal => "response-final",
            MessageLabel::Interest => "interest",
            MessageLabel::Declare => "declare",
            MessageLabel::Oam => "oam",
        }
    }
}

/// Why a message was dropped
/// (`commons/zenoh-stats/src/labels.rs` @ `pub enum ReasonLabel`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ReasonLabel {
    /// Refused by an access-control rule.
    AccessControl,
    /// Refused by a full priority queue under `Drop` congestion control.
    Congestion,
    /// Refused by a downsampling interceptor.
    Downsampling,
    /// Refused by a low-pass filter.
    LowPass,
    /// No link could carry it.
    NoLink,
}

impl ReasonLabel {
    /// Upstream's label value.
    pub const fn label(self) -> &'static str {
        match self {
            ReasonLabel::AccessControl => "access-control",
            ReasonLabel::Congestion => "congestion",
            ReasonLabel::Downsampling => "downsampling",
            ReasonLabel::LowPass => "low-pass",
            ReasonLabel::NoLink => "no-link",
        }
    }
}

/// The kind of declared resource `zenoh_resources_declared` counts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ResourceLabel {
    /// A subscriber.
    Subscriber,
    /// A queryable.
    Queryable,
    /// A liveliness token.
    Token,
}

impl ResourceLabel {
    /// Upstream's label value.
    pub const fn label(self) -> &'static str {
        match self {
            ResourceLabel::Subscriber => "subscriber",
            ResourceLabel::Queryable => "queryable",
            ResourceLabel::Token => "token",
        }
    }
}

/// Whether a declared resource belongs to this node or to a remote one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum LocalityLabel {
    /// Declared by this node.
    Local,
    /// Declared by a remote node.
    Remote,
}

impl LocalityLabel {
    /// Upstream's label value.
    pub const fn label(self) -> &'static str {
        match self {
            LocalityLabel::Local => "local",
            LocalityLabel::Remote => "remote",
        }
    }
}

/// Who is on the other end of a transport — the per-transport partition key
/// (`commons/zenoh-stats/src/labels.rs` @ `pub(crate) struct TransportLabels`).
///
/// A unicast transport names its peer; a multicast transport names its group
/// and no peer; a peer seen on a multicast group names both. Every field is
/// written in every sample, an absent one as the empty string, which is what
/// `prometheus-client` does with a `None` label value.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TransportLabels {
    /// The peer's zid in zenoh's hex form.
    pub remote_zid: Option<String>,
    /// The peer's role.
    pub remote_whatami: Option<WhatAmI>,
    /// The multicast group locator.
    pub remote_group: Option<String>,
    /// The peer certificate's common name.
    pub remote_cn: Option<String>,
}

impl TransportLabels {
    /// A unicast transport to `zid`.
    pub fn unicast(zid: &str, whatami: WhatAmI, cn: Option<&str>) -> Self {
        TransportLabels {
            remote_zid: Some(String::from(zid)),
            remote_whatami: Some(whatami),
            remote_group: None,
            remote_cn: cn.map(String::from),
        }
    }

    /// A multicast transport on `group`.
    pub fn multicast(group: &str) -> Self {
        TransportLabels {
            remote_zid: None,
            remote_whatami: None,
            remote_group: Some(String::from(group)),
            remote_cn: None,
        }
    }

    /// A peer `zid` seen on the multicast `group`.
    pub fn multicast_peer(zid: &str, whatami: WhatAmI, group: &str) -> Self {
        TransportLabels {
            remote_zid: Some(String::from(zid)),
            remote_whatami: Some(whatami),
            remote_group: Some(String::from(group)),
            remote_cn: None,
        }
    }

    /// Whether closing one of this transport's links changes the
    /// `zenoh_links_opened` gauge. Upstream decrements it only for a transport
    /// that is not a multicast PEER entry
    /// (`commons/zenoh-stats/src/registry.rs` @ `if transport.remote_group.is_none() || transport.remote_zid.is_none() {`),
    /// because a peer entry's link was never counted as a new link.
    fn owns_its_links(&self) -> bool {
        self.remote_group.is_none() || self.remote_zid.is_none()
    }

    fn write(&self, w: &mut LabelWriter<'_>) {
        w.opt("remote_zid", self.remote_zid.as_deref());
        w.opt("remote_whatami", self.remote_whatami.map(WhatAmI::to_str));
        w.opt("remote_group", self.remote_group.as_deref());
        w.opt("remote_cn", self.remote_cn.as_deref());
    }
}

/// One link of a transport — the per-link partition key.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct LinkLabels {
    /// This node's end, as a locator string.
    pub src_locator: String,
    /// The remote end, as a locator string.
    pub dst_locator: String,
}

impl LinkLabels {
    /// A link from `src` to `dst`.
    pub fn new(src: &str, dst: &str) -> Self {
        LinkLabels {
            src_locator: String::from(src),
            dst_locator: String::from(dst),
        }
    }

    /// The `protocol` label this link's samples carry: the remote locator's
    /// scheme when upstream knows it, and otherwise the WHOLE remote locator
    /// (`commons/zenoh-stats/src/labels.rs` @ `static KNOWN_PROTOCOLS`) — so an
    /// unknown scheme gets one series per remote end, which is upstream's.
    pub fn protocol(&self) -> String {
        const KNOWN_PROTOCOLS: [&str; 9] = [
            "tcp",
            "udp",
            "tls",
            "quic",
            "unixsock-stream",
            "ws",
            "serial",
            "unixpipe",
            "vsock",
        ];
        let scheme = self
            .dst_locator
            .split_once('/')
            .map_or(self.dst_locator.as_str(), |(scheme, _)| scheme);
        match KNOWN_PROTOCOLS.iter().find(|known| **known == scheme) {
            Some(known) => String::from(*known),
            None => self.dst_locator.clone(),
        }
    }

    fn write(&self, w: &mut LabelWriter<'_>) {
        w.label("src_locator", &self.src_locator);
        w.label("dst_locator", &self.dst_locator);
    }
}

/// A family's label set: the part of a sample's labels the family itself owns.
pub trait StatsLabelSet: Ord + Clone {
    /// Append this set's `,key="value"` pairs, in upstream's field order.
    fn write(&self, w: &mut LabelWriter<'_>);
}

/// `zenoh_{tx,rx}_bytes`'s labels.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BytesLabels {
    /// See [`LinkLabels::protocol`].
    pub protocol: String,
}

impl StatsLabelSet for BytesLabels {
    fn write(&self, w: &mut LabelWriter<'_>) {
        w.label("protocol", &self.protocol);
    }
}

/// `zenoh_{tx,rx}_transport_message`'s labels.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TransportMessageLabels {
    /// See [`LinkLabels::protocol`].
    pub protocol: String,
}

impl StatsLabelSet for TransportMessageLabels {
    fn write(&self, w: &mut LabelWriter<'_>) {
        w.label("protocol", &self.protocol);
    }
}

/// `zenoh_{tx,rx}_network_message`'s labels.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct NetworkMessageLabels {
    /// The message's priority band.
    pub priority: Priority,
    /// The message kind.
    pub message: MessageLabel,
    /// Whether the payload travelled in shared memory.
    pub shm: bool,
    /// See [`LinkLabels::protocol`].
    pub protocol: String,
}

impl StatsLabelSet for NetworkMessageLabels {
    fn write(&self, w: &mut LabelWriter<'_>) {
        w.label("priority", self.priority.display_str());
        w.label("message", self.message.label());
        w.label("shm", bool_label(self.shm));
        w.label("protocol", &self.protocol);
    }
}

/// `zenoh_{tx,rx}_network_message_payload`'s labels, which the per-key family
/// shares.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct NetworkMessagePayloadLabels {
    /// Admin space or user space.
    pub space: StatSpace,
    /// The message's priority band.
    pub priority: Priority,
    /// The message kind.
    pub message: MessageLabel,
    /// Whether the payload travelled in shared memory.
    pub shm: bool,
}

impl StatsLabelSet for NetworkMessagePayloadLabels {
    fn write(&self, w: &mut LabelWriter<'_>) {
        w.label("space", self.space.label());
        w.label("priority", self.priority.display_str());
        w.label("message", self.message.label());
        w.label("shm", bool_label(self.shm));
    }
}

/// `zenoh_{tx,rx}_network_message_dropped_payload`'s labels.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct NetworkMessageDroppedPayloadLabels {
    /// The message's priority band.
    pub priority: Priority,
    /// The message kind.
    pub message: MessageLabel,
    /// The link protocol, when the drop happened on a link; written as the
    /// empty string otherwise.
    pub protocol: Option<String>,
    /// Why it was dropped.
    pub reason: ReasonLabel,
}

impl StatsLabelSet for NetworkMessageDroppedPayloadLabels {
    fn write(&self, w: &mut LabelWriter<'_>) {
        w.label("priority", self.priority.display_str());
        w.label("message", self.message.label());
        w.opt("protocol", self.protocol.as_deref());
        w.label("reason", self.reason.label());
    }
}

/// A metric one cell holds, and how it is written.
pub trait StatsMetric: Clone + Default {
    /// The OpenMetrics type the descriptor declares.
    const TYPE: &'static str;

    /// Add `other` into `self` — the aggregation across transports and links.
    fn merge_from(&mut self, other: &Self);

    /// Write this metric's sample lines. `name` is the full metric name with its
    /// unit, `head` the registry's constant labels, `labels` the rest as a
    /// `,key="value"` fragment.
    fn encode(&self, out: &mut String, name: &str, head: &str, labels: &str);
}

impl StatsMetric for u64 {
    const TYPE: &'static str = "counter";

    fn merge_from(&mut self, other: &Self) {
        *self = self.wrapping_add(*other);
    }

    fn encode(&self, out: &mut String, name: &str, head: &str, labels: &str) {
        let _ = writeln!(out, "{name}_total{{{head}{labels}}} {self}");
    }
}

/// A payload-size histogram over [`PAYLOAD_SIZE_BUCKETS`].
///
/// Counts are stored per bucket and made cumulative when written, which is
/// what upstream stores and what `prometheus-client` writes
/// (`commons/zenoh-stats/src/histogram.rs` @ `pub fn observe(&self, value: u64) {`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PayloadHistogram {
    sum: u64,
    counts: [u64; BUCKET_COUNT],
}

impl PayloadHistogram {
    /// Count one payload of `size` bytes. A size equal to a bound lands in that
    /// bound's bucket (`value <= bound`).
    pub fn observe(&mut self, size: u64) {
        let bucket = PAYLOAD_SIZE_BUCKETS
            .iter()
            .position(|bound| size <= *bound)
            .unwrap_or(PAYLOAD_SIZE_BUCKETS.len());
        self.counts[bucket] = self.counts[bucket].wrapping_add(1);
        self.sum = self.sum.wrapping_add(size);
    }

    /// How many payloads were observed.
    pub fn count(&self) -> u64 {
        self.counts.iter().fold(0u64, |acc, c| acc.wrapping_add(*c))
    }

    /// The total bytes observed.
    pub fn sum(&self) -> u64 {
        self.sum
    }
}

impl StatsMetric for PayloadHistogram {
    const TYPE: &'static str = "histogram";

    fn merge_from(&mut self, other: &Self) {
        self.sum = self.sum.wrapping_add(other.sum);
        for (mine, theirs) in self.counts.iter_mut().zip(other.counts.iter()) {
            *mine = mine.wrapping_add(*theirs);
        }
    }

    fn encode(&self, out: &mut String, name: &str, head: &str, labels: &str) {
        let _ = writeln!(out, "{name}_sum{{{head}{labels}}} {}", Float(self.sum));
        let _ = writeln!(out, "{name}_count{{{head}{labels}}} {}", self.count());
        let mut cumulative = 0u64;
        for (bucket, count) in self.counts.iter().enumerate() {
            cumulative = cumulative.wrapping_add(*count);
            let _ = write!(out, "{name}_bucket{{{head},le=\"");
            match PAYLOAD_SIZE_BUCKETS.get(bucket) {
                Some(bound) => {
                    let _ = write!(out, "{}", Float(*bound));
                }
                None => out.push_str("+Inf"),
            }
            let _ = writeln!(out, "\"{labels}}} {cumulative}");
        }
    }
}

/// One payload histogram per configured key expression.
///
/// Keys are the configured expressions' own strings, which is what upstream
/// writes in the `key` label once it resolves its key index against the current
/// key list (`commons/zenoh-stats/src/keys.rs` @ `fn collect(&self)`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PerKeyHistogram {
    keys: BTreeMap<String, PayloadHistogram>,
}

impl PerKeyHistogram {
    /// Count one payload of `size` bytes under every key in `keys`. An empty
    /// `keys` counts nothing, which is upstream's `observe` early return.
    pub fn observe<'k>(&mut self, keys: impl IntoIterator<Item = &'k str>, size: u64) {
        for key in keys {
            self.keys
                .entry(String::from(key))
                .or_default()
                .observe(size);
        }
    }
}

impl StatsMetric for PerKeyHistogram {
    const TYPE: &'static str = "histogram";

    fn merge_from(&mut self, other: &Self) {
        for (key, histogram) in &other.keys {
            self.keys
                .entry(key.clone())
                .or_default()
                .merge_from(histogram);
        }
    }

    fn encode(&self, out: &mut String, name: &str, head: &str, labels: &str) {
        for (key, histogram) in &self.keys {
            let mut keyed = String::from(labels);
            LabelWriter { out: &mut keyed }.label("key", key);
            histogram.encode(out, name, head, &keyed);
        }
    }
}

/// One family's cells within one transport, keyed by link (`None` for a cell
/// that belongs to the transport rather than to one of its links) and label set
/// (`commons/zenoh-stats/src/family.rs` @ `struct TransportState<S, M> {`).
#[derive(Debug, Clone)]
pub struct FamilyCells<L, M> {
    cells: BTreeMap<(Option<LinkLabels>, L), M>,
}

impl<L, M> Default for FamilyCells<L, M> {
    fn default() -> Self {
        FamilyCells {
            cells: BTreeMap::new(),
        }
    }
}

impl<L: StatsLabelSet, M: StatsMetric> FamilyCells<L, M> {
    /// The cell for `labels` on `link`, created empty on first use — upstream
    /// creates its series the same way, so a series appears the first time it
    /// is touched and never before.
    pub fn cell(&mut self, link: Option<&LinkLabels>, labels: L) -> &mut M {
        self.cells.entry((link.cloned(), labels)).or_default()
    }

    /// Fold every cell of `link` into the transport-level cells, as upstream
    /// does when a link closes (`commons/zenoh-stats/src/family.rs` @ `pub(crate) fn remove_link(`).
    fn fold_link(&mut self, link: &LinkLabels) {
        let moved: Vec<(L, M)> = self
            .cells
            .iter()
            .filter(|((cell_link, _), _)| cell_link.as_ref() == Some(link))
            .map(|((_, labels), metric)| (labels.clone(), metric.clone()))
            .collect();
        self.cells
            .retain(|(cell_link, _), _| cell_link.as_ref() != Some(link));
        for (labels, metric) in moved {
            self.cell(None, labels).merge_from(&metric);
        }
    }

    /// Fold the transport-level cells of `other` into `self`'s transport-level
    /// cells. Link-scoped cells are NOT carried: upstream's garbage collection
    /// drains only the `None` link bucket
    /// (`commons/zenoh-stats/src/family.rs` @ `.get_mut(&None)`), so a count
    /// still held under a link when its transport is collected is lost there too.
    fn retire_from(&mut self, other: &Self) {
        for ((link, labels), metric) in &other.cells {
            if link.is_none() {
                self.cell(None, labels.clone()).merge_from(metric);
            }
        }
    }
}

/// Every family of one direction.
#[derive(Debug, Clone, Default)]
pub struct DirectionMetrics {
    /// Wire bytes, per link.
    pub bytes: FamilyCells<BytesLabels, u64>,
    /// Transport messages, per link.
    pub transport_message: FamilyCells<TransportMessageLabels, u64>,
    /// Network messages, per link.
    pub network_message: FamilyCells<NetworkMessageLabels, u64>,
    /// Network payload sizes, per transport.
    pub network_message_payload: FamilyCells<NetworkMessagePayloadLabels, PayloadHistogram>,
    /// Dropped network payload sizes, per transport.
    pub network_message_dropped_payload:
        FamilyCells<NetworkMessageDroppedPayloadLabels, PayloadHistogram>,
    /// Network payload sizes per configured key, per transport.
    pub network_message_payload_per_key: FamilyCells<NetworkMessagePayloadLabels, PerKeyHistogram>,
}

impl DirectionMetrics {
    fn fold_link(&mut self, link: &LinkLabels) {
        self.bytes.fold_link(link);
        self.transport_message.fold_link(link);
        self.network_message.fold_link(link);
        self.network_message_payload.fold_link(link);
        self.network_message_dropped_payload.fold_link(link);
        self.network_message_payload_per_key.fold_link(link);
    }

    fn retire_from(&mut self, other: &Self) {
        self.bytes.retire_from(&other.bytes);
        self.transport_message.retire_from(&other.transport_message);
        self.network_message.retire_from(&other.network_message);
        self.network_message_payload
            .retire_from(&other.network_message_payload);
        self.network_message_dropped_payload
            .retire_from(&other.network_message_dropped_payload);
        self.network_message_payload_per_key
            .retire_from(&other.network_message_payload_per_key);
    }
}

/// One transport's counters in both directions: what a session records into.
#[derive(Debug, Clone, Default)]
pub struct TransportMetrics {
    directions: [DirectionMetrics; 2],
}

impl TransportMetrics {
    /// The families of one direction.
    pub fn direction(&self, direction: StatsDirection) -> &DirectionMetrics {
        &self.directions[direction.index()]
    }

    /// The families of one direction, for recording.
    pub fn direction_mut(&mut self, direction: StatsDirection) -> &mut DirectionMetrics {
        &mut self.directions[direction.index()]
    }

    /// Create `link`'s byte and transport-message series in both directions,
    /// at zero — upstream creates them when the link's stats handle is made
    /// (`commons/zenoh-stats/src/link.rs` @ `pub(crate) fn new(transport_stats: TransportStats, link: LinkLabels) -> Self {`),
    /// which is why a freshly opened link reports `0` rather than nothing.
    fn open_link(&mut self, link: &LinkLabels) {
        let protocol = link.protocol();
        for direction in &mut self.directions {
            direction.bytes.cell(
                Some(link),
                BytesLabels {
                    protocol: protocol.clone(),
                },
            );
            direction.transport_message.cell(
                Some(link),
                TransportMessageLabels {
                    protocol: protocol.clone(),
                },
            );
        }
    }

    /// Count `bytes` wire bytes on `link`.
    pub fn inc_bytes(&mut self, direction: StatsDirection, link: &LinkLabels, bytes: u64) {
        let protocol = link.protocol();
        self.direction_mut(direction)
            .bytes
            .cell(Some(link), BytesLabels { protocol })
            .merge_from(&bytes);
    }

    /// Count `count` transport messages on `link`.
    pub fn inc_transport_message(
        &mut self,
        direction: StatsDirection,
        link: &LinkLabels,
        count: u64,
    ) {
        let protocol = link.protocol();
        self.direction_mut(direction)
            .transport_message
            .cell(Some(link), TransportMessageLabels { protocol })
            .merge_from(&count);
    }

    /// Count one network message on `link`.
    pub fn inc_network_message(
        &mut self,
        direction: StatsDirection,
        link: &LinkLabels,
        priority: Priority,
        message: MessageLabel,
        shm: bool,
    ) {
        let protocol = link.protocol();
        self.direction_mut(direction)
            .network_message
            .cell(
                Some(link),
                NetworkMessageLabels {
                    priority,
                    message,
                    shm,
                    protocol,
                },
            )
            .merge_from(&1);
    }

    /// Count one network payload of `size` bytes, and count it again under
    /// every configured key in `keys`. Both series are created on the first
    /// call even when `keys` is empty, as upstream creates the pair together
    /// (`commons/zenoh-stats/src/transport.rs` @ `pub fn observe_network_message_payload(`).
    #[allow(clippy::too_many_arguments)]
    pub fn observe_network_message_payload<'k>(
        &mut self,
        direction: StatsDirection,
        space: StatSpace,
        priority: Priority,
        message: MessageLabel,
        shm: bool,
        size: u64,
        keys: impl IntoIterator<Item = &'k str>,
    ) {
        let labels = NetworkMessagePayloadLabels {
            space,
            priority,
            message,
            shm,
        };
        let families = self.direction_mut(direction);
        families
            .network_message_payload
            .cell(None, labels.clone())
            .observe(size);
        families
            .network_message_payload_per_key
            .cell(None, labels)
            .observe(keys, size);
    }

    /// Count one dropped network payload of `size` bytes. `protocol` is the
    /// link's protocol when the drop was a link's, as upstream's congestion drop
    /// is, and `None` for a transport-level drop.
    pub fn observe_network_message_dropped_payload(
        &mut self,
        direction: StatsDirection,
        priority: Priority,
        message: MessageLabel,
        protocol: Option<&str>,
        reason: ReasonLabel,
        size: u64,
    ) {
        self.direction_mut(direction)
            .network_message_dropped_payload
            .cell(
                None,
                NetworkMessageDroppedPayloadLabels {
                    priority,
                    message,
                    protocol: protocol.map(String::from),
                    reason,
                },
            )
            .observe(size);
    }

    fn fold_link(&mut self, link: &LinkLabels) {
        for direction in &mut self.directions {
            direction.fold_link(link);
        }
    }

    fn retire_from(&mut self, other: &Self) {
        for (mine, theirs) in self.directions.iter_mut().zip(other.directions.iter()) {
            mine.retire_from(theirs);
        }
    }
}

/// A transport's identity in a [`StatsRegistry`]. Stable for the transport's
/// whole life, including the minute it spends disconnected.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct StatsTransportId(u64);

#[derive(Debug, Clone)]
struct RegisteredTransport {
    labels: TransportLabels,
    /// When the transport closed, on the caller's monotonic millisecond clock.
    disconnected_at: Option<u64>,
    metrics: TransportMetrics,
}

/// What a metrics query asks the encoder to include — upstream's four
/// partition parameters, with upstream's polarities
/// (`zenoh/src/net/runtime/adminspace.rs` @ `query.parameters().get("per_transport") != Some("false"),`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MetricsQuery {
    /// Write the `…_per_transport` blocks. On unless `per_transport=false`.
    pub per_transport: bool,
    /// Write the `…_per_link` blocks. On unless `per_link=false`.
    pub per_link: bool,
    /// Count and list disconnected transports that are not yet retired. Off
    /// unless `disconnected=true`.
    pub disconnected: bool,
    /// Write the per-key payload families. On unless `per_key=false`.
    pub per_key: bool,
}

impl Default for MetricsQuery {
    fn default() -> Self {
        MetricsQuery {
            per_transport: true,
            per_link: true,
            disconnected: false,
            per_key: true,
        }
    }
}

impl MetricsQuery {
    /// Read the four parameters through `get`, a selector-parameter lookup that
    /// answers `Some("")` for a key given without a value (zenoh's own `get`
    /// semantics). Equality against the literal is what upstream tests, so a
    /// bare `?per_link` leaves the partition ON and a bare `?disconnected`
    /// leaves it OFF.
    pub fn from_parameters<'p>(get: impl Fn(&str) -> Option<&'p str>) -> Self {
        MetricsQuery {
            per_transport: get("per_transport") != Some("false"),
            per_link: get("per_link") != Some("false"),
            disconnected: get("disconnected") == Some("true"),
            per_key: get("per_key") != Some("false"),
        }
    }
}

/// The node-wide stats registry (`commons/zenoh-stats/src/registry.rs` @ `pub struct StatsRegistry`).
///
/// Transports record into their own [`TransportMetrics`]; the registry owns the
/// gauges that are not per transport and does the collection when a metrics
/// query is answered. Time is the caller's: every method that needs it takes a
/// monotonic millisecond reading, so the registry stays `no_std`.
#[derive(Debug, Clone)]
pub struct StatsRegistry {
    local_zid: String,
    local_whatami: WhatAmI,
    build_version: String,
    transports_opened: i64,
    links_opened: BTreeMap<String, i64>,
    resources_declared: BTreeMap<(ResourceLabel, LocalityLabel), i64>,
    retired: TransportMetrics,
    transports: BTreeMap<StatsTransportId, RegisteredTransport>,
    next_id: u64,
}

impl StatsRegistry {
    /// An empty registry for the node `zid` in role `whatami`.
    pub fn new(zid: &str, whatami: WhatAmI, build_version: &str) -> Self {
        StatsRegistry {
            local_zid: String::from(zid),
            local_whatami: whatami,
            build_version: String::from(build_version),
            transports_opened: 0,
            links_opened: BTreeMap::new(),
            resources_declared: BTreeMap::new(),
            retired: TransportMetrics::default(),
            transports: BTreeMap::new(),
            next_id: 0,
        }
    }

    fn register(&mut self, labels: TransportLabels) -> StatsTransportId {
        let id = StatsTransportId(self.next_id);
        self.next_id += 1;
        self.transports.insert(
            id,
            RegisteredTransport {
                labels,
                disconnected_at: None,
                metrics: TransportMetrics::default(),
            },
        );
        id
    }

    /// Register an opened unicast transport to `zid`.
    pub fn open_unicast_transport(
        &mut self,
        zid: &str,
        whatami: WhatAmI,
        cn: Option<&str>,
    ) -> StatsTransportId {
        self.transports_opened += 1;
        self.register(TransportLabels::unicast(zid, whatami, cn))
    }

    /// Register an opened multicast transport on `group`.
    pub fn open_multicast_transport(&mut self, group: &str) -> StatsTransportId {
        self.transports_opened += 1;
        self.register(TransportLabels::multicast(group))
    }

    /// Register a peer seen on a multicast transport. It is a partition of its
    /// own but NOT an opened transport: upstream builds its stats without the
    /// registry's `transports_opened` increment
    /// (`commons/zenoh-stats/src/transport.rs` @ `pub fn peer_link_stats(`).
    pub fn open_multicast_peer(
        &mut self,
        zid: &str,
        whatami: WhatAmI,
        group: &str,
    ) -> StatsTransportId {
        self.register(TransportLabels::multicast_peer(zid, whatami, group))
    }

    /// Register `link` on `transport`. A multicast peer's link is the group's
    /// link seen again, so it does not count as a newly opened link.
    pub fn open_link(&mut self, transport: StatsTransportId, link: &LinkLabels) {
        let Some(entry) = self.transports.get_mut(&transport) else {
            return;
        };
        if entry.labels.owns_its_links() {
            *self.links_opened.entry(link.protocol()).or_insert(0) += 1;
        }
        entry.metrics.open_link(link);
    }

    /// `link` of `transport` closed: its cells fold into the transport's own.
    pub fn close_link(&mut self, transport: StatsTransportId, link: &LinkLabels) {
        let Some(entry) = self.transports.get_mut(&transport) else {
            return;
        };
        entry.metrics.fold_link(link);
        if entry.labels.owns_its_links() {
            *self.links_opened.entry(link.protocol()).or_insert(0) -= 1;
        }
    }

    /// `transport` closed at `now_ms`. It keeps its partition, marked
    /// disconnected, until [`Self::collect_garbage`] retires it.
    ///
    /// ⚠ Upstream decrements `transports_opened` for EVERY dropped transport
    /// stats handle, a multicast peer's included, though a peer's was never
    /// counted (`commons/zenoh-stats/src/registry.rs` @ `pub(crate) fn remove_transport(`).
    /// That asymmetry is upstream's and is kept, so the gauge answers the same
    /// on both implementations.
    pub fn close_transport(&mut self, transport: StatsTransportId, now_ms: u64) {
        if let Some(entry) = self.transports.get_mut(&transport) {
            if entry.disconnected_at.is_none() {
                entry.disconnected_at = Some(now_ms);
                self.transports_opened -= 1;
            }
        }
    }

    /// Fold every transport disconnected for longer than
    /// [`GARBAGE_COLLECTION_DELAY_MS`] into the retired bucket and forget its
    /// labels. Upstream runs this at the end of each collection; a host calls it
    /// after answering a metrics query, which is the same moment.
    pub fn collect_garbage(&mut self, now_ms: u64) {
        let expired: Vec<StatsTransportId> = self
            .transports
            .iter()
            .filter(|(_, entry)| {
                entry
                    .disconnected_at
                    .is_some_and(|at| now_ms.saturating_sub(at) > GARBAGE_COLLECTION_DELAY_MS)
            })
            .map(|(id, _)| *id)
            .collect();
        for id in expired {
            if let Some(entry) = self.transports.remove(&id) {
                self.retired.retire_from(&entry.metrics);
            }
        }
    }

    /// The counters `transport` records into.
    pub fn transport_mut(&mut self, transport: StatsTransportId) -> Option<&mut TransportMetrics> {
        self.transports
            .get_mut(&transport)
            .map(|entry| &mut entry.metrics)
    }

    /// A resource was declared.
    pub fn inc_resource_declared(&mut self, resource: ResourceLabel, locality: LocalityLabel) {
        *self
            .resources_declared
            .entry((resource, locality))
            .or_insert(0) += 1;
    }

    /// A resource was undeclared.
    pub fn dec_resource_declared(&mut self, resource: ResourceLabel, locality: LocalityLabel) {
        *self
            .resources_declared
            .entry((resource, locality))
            .or_insert(0) -= 1;
    }

    /// Write the whole OpenMetrics document, `# EOF` included, as upstream's
    /// `encode_metrics` writes it.
    pub fn encode_metrics(&self, out: &mut String, query: MetricsQuery) {
        let mut head = String::new();
        {
            let mut w = LabelWriter { out: &mut head };
            w.label("local_id", &self.local_zid);
            w.label("local_whatami", self.local_whatami.to_str());
        }
        // The fragment writer always leads with a comma; the constant labels
        // open the brace, so the first comma is dropped here once.
        let head = &head[1..];

        push_build_info(
            out,
            &self.local_zid,
            self.local_whatami.to_str(),
            &self.build_version,
        );

        out.push_str("# HELP zenoh_transports_opened Count of transports currently opened.\n");
        out.push_str("# TYPE zenoh_transports_opened gauge\n");
        let _ = writeln!(
            out,
            "zenoh_transports_opened{{{head}}} {}",
            self.transports_opened
        );

        // A registered FAMILY is written only once it holds a series
        // (`prometheus-client` skips an empty one), and a series that fell back
        // to zero stays. Upstream's help text for this gauge says "transports";
        // it is upstream's, and a consumer matching on it would read it so.
        if !self.links_opened.is_empty() {
            out.push_str("# HELP zenoh_links_opened Count of transports currently opened.\n");
            out.push_str("# TYPE zenoh_links_opened gauge\n");
            for (protocol, count) in &self.links_opened {
                let mut labels = String::new();
                LabelWriter { out: &mut labels }.label("protocol", protocol);
                let _ = writeln!(out, "zenoh_links_opened{{{head}{labels}}} {count}");
            }
        }
        if !self.resources_declared.is_empty() {
            out.push_str(
                "# HELP zenoh_resources_declared Count of resources currently declared.\n",
            );
            out.push_str("# TYPE zenoh_resources_declared gauge\n");
            for ((resource, locality), count) in &self.resources_declared {
                let mut labels = String::new();
                {
                    let mut w = LabelWriter { out: &mut labels };
                    w.label("resource", resource.label());
                    w.label("locality", locality.label());
                }
                let _ = writeln!(out, "zenoh_resources_declared{{{head}{labels}}} {count}");
            }
        }

        let ctx = EncodeCtx {
            head,
            query,
            retired: &self.retired,
            transports: &self.transports,
        };
        for direction in StatsDirection::ALL {
            let dir = direction.label();
            let action = direction.action();
            ctx.family(
                out,
                direction,
                |d| &d.bytes,
                FamilyName {
                    name: dir.into(),
                    help: alloc::format!("Count of transport messages bytes {action}"),
                    unit: Some("bytes"),
                },
            );
            ctx.family(
                out,
                direction,
                |d| &d.transport_message,
                FamilyName {
                    name: alloc::format!("{dir}_transport_message"),
                    help: alloc::format!("Count of transport messages {action}"),
                    unit: None,
                },
            );
            ctx.family(
                out,
                direction,
                |d| &d.network_message,
                FamilyName {
                    name: alloc::format!("{dir}_network_message"),
                    help: alloc::format!("Count of network messages {action}"),
                    unit: None,
                },
            );
            ctx.family(
                out,
                direction,
                |d| &d.network_message_payload,
                FamilyName {
                    name: alloc::format!("{dir}_network_message_payload"),
                    help: alloc::format!("Histogram of network messages payload {action}"),
                    unit: Some("bytes"),
                },
            );
            ctx.family(
                out,
                direction,
                |d| &d.network_message_dropped_payload,
                FamilyName {
                    name: alloc::format!("{dir}_network_message_dropped_payload"),
                    help: alloc::format!(
                        "Histogram of network messages payload dropped while {action}"
                    ),
                    unit: Some("bytes"),
                },
            );
            // Upstream's per-key collector returns before writing even its
            // descriptor when the query turns the partition off
            // (`commons/zenoh-stats/src/family.rs` @ `&& !COLLECT_PER_KEY.get()`).
            if query.per_key {
                ctx.family(
                    out,
                    direction,
                    |d| &d.network_message_payload_per_key,
                    FamilyName {
                        name: alloc::format!("{dir}_network_message_payload_per_key"),
                        help: alloc::format!(
                            "Histogram of network messages payload {action} per key"
                        ),
                        unit: Some("bytes"),
                    },
                );
            }
        }
        out.push_str("# EOF\n");
    }
}

struct FamilyName {
    name: String,
    help: String,
    unit: Option<&'static str>,
}

/// One label set's collection: its total and its share per transport.
struct Collected<'a, M> {
    total: M,
    transports: Vec<TransportShare<'a, M>>,
}

struct TransportShare<'a, M> {
    labels: &'a TransportLabels,
    disconnected: bool,
    total: M,
    links: Vec<(&'a LinkLabels, M)>,
}

struct EncodeCtx<'a> {
    head: &'a str,
    query: MetricsQuery,
    retired: &'a TransportMetrics,
    transports: &'a BTreeMap<StatsTransportId, RegisteredTransport>,
}

impl<'a> EncodeCtx<'a> {
    /// Upstream's collection for one family
    /// (`commons/zenoh-stats/src/family.rs` @ `fn collect(&self)`).
    fn collect<L: StatsLabelSet + 'a, M: StatsMetric + 'a>(
        &self,
        direction: StatsDirection,
        select: fn(&DirectionMetrics) -> &FamilyCells<L, M>,
    ) -> BTreeMap<&'a L, Collected<'a, M>> {
        let mut results: BTreeMap<&'a L, Collected<'a, M>> = BTreeMap::new();
        for ((_, labels), metric) in &select(self.retired.direction(direction)).cells {
            results
                .entry(labels)
                .or_insert_with(|| Collected {
                    total: M::default(),
                    transports: Vec::new(),
                })
                .total
                .merge_from(metric);
        }
        for entry in self.transports.values() {
            let disconnected = entry.disconnected_at.is_some();
            if disconnected && !self.query.disconnected {
                continue;
            }
            for ((link, labels), metric) in &select(entry.metrics.direction(direction)).cells {
                let collected = results.entry(labels).or_insert_with(|| Collected {
                    total: M::default(),
                    transports: Vec::new(),
                });
                collected.total.merge_from(metric);
                let share = match collected.transports.last_mut() {
                    Some(share) if *share.labels == entry.labels => share,
                    _ => {
                        collected.transports.push(TransportShare {
                            labels: &entry.labels,
                            disconnected,
                            total: M::default(),
                            links: Vec::new(),
                        });
                        collected
                            .transports
                            .last_mut()
                            .expect("a share was pushed on the line above")
                    }
                };
                share.total.merge_from(metric);
                if let Some(link) = link {
                    share.links.push((link, metric.clone()));
                }
            }
        }
        results
    }

    /// Write one family's descriptor and samples, then its per-transport and
    /// per-link twins as the query asks
    /// (`commons/zenoh-stats/src/family.rs` @ `fn encode(&self, mut encoder: DescriptorEncoder) -> fmt::Result {`).
    fn family<L: StatsLabelSet + 'a, M: StatsMetric + 'a>(
        &self,
        out: &mut String,
        direction: StatsDirection,
        select: fn(&DirectionMetrics) -> &FamilyCells<L, M>,
        name: FamilyName,
    ) {
        let collected = self.collect(direction, select);

        let full = descriptor(out, &name.name, &name.help, name.unit, M::TYPE);
        for (labels, entry) in &collected {
            entry
                .total
                .encode(out, &full, self.head, &fragment(|w| labels.write(w)));
        }

        if self.query.per_transport {
            let full = descriptor(
                out,
                &alloc::format!("{}_per_transport", name.name),
                &alloc::format!("{} (per transport)", name.help),
                name.unit,
                M::TYPE,
            );
            for (labels, entry) in &collected {
                for share in &entry.transports {
                    let labels = fragment(|w| {
                        labels.write(w);
                        share.labels.write(w);
                        w.label("disconnected", bool_label(share.disconnected));
                    });
                    share.total.encode(out, &full, self.head, &labels);
                }
            }
        }

        let any_link = collected
            .values()
            .flat_map(|entry| entry.transports.iter())
            .any(|share| !share.links.is_empty());
        if self.query.per_link && any_link {
            let full = descriptor(
                out,
                &alloc::format!("{}_per_link", name.name),
                &alloc::format!("{} (per link)", name.help),
                name.unit,
                M::TYPE,
            );
            for (labels, entry) in &collected {
                for share in &entry.transports {
                    for (link, metric) in &share.links {
                        let labels = fragment(|w| {
                            labels.write(w);
                            share.labels.write(w);
                            link.write(w);
                        });
                        metric.encode(out, &full, self.head, &labels);
                    }
                }
            }
        }
    }
}

/// Write a family descriptor and return the metric name its samples use.
/// `name` is the collector's name without the registry prefix; the unit, when
/// there is one, is appended to it
/// (`prometheus-client` 0.24.1, `encoding/text.rs` `fn encode_descriptor`).
fn descriptor(out: &mut String, name: &str, help: &str, unit: Option<&str>, kind: &str) -> String {
    let mut full = alloc::format!("zenoh_{name}");
    if let Some(unit) = unit {
        full.push('_');
        full.push_str(unit);
    }
    let _ = writeln!(out, "# HELP {full} {help}");
    let _ = writeln!(out, "# TYPE {full} {kind}");
    if let Some(unit) = unit {
        let _ = writeln!(out, "# UNIT {full} {unit}");
    }
    full
}

/// The build-info block: upstream's `zenoh_build` `info` family, whose one
/// sample carries the registry's two constant labels and the version
/// (`commons/zenoh-stats/src/registry.rs` @ `"Zenoh build version",`). The
/// no-`stats` literal writes the same three lines
/// (`zenoh/src/net/runtime/adminspace.rs` @ `"# HELP zenoh_build Zenoh build version.\n",`),
/// so both bodies share this one writer.
pub fn push_build_info(out: &mut String, zid: &str, whatami: &str, version: &str) {
    out.push_str("# HELP zenoh_build Zenoh build version.\n");
    out.push_str("# TYPE zenoh_build info\n");
    out.push_str("zenoh_build_info{");
    let mut labels = String::new();
    {
        let mut w = LabelWriter { out: &mut labels };
        w.label("local_id", zid);
        w.label("local_whatami", whatami);
        w.label("version", version);
    }
    out.push_str(&labels[1..]);
    out.push_str("} 1\n");
}

/// Appends `,key="value"` pairs to a label fragment.
pub struct LabelWriter<'a> {
    out: &'a mut String,
}

impl LabelWriter<'_> {
    /// Append one label.
    pub fn label(&mut self, key: &str, value: &str) {
        self.out.push(',');
        self.out.push_str(key);
        self.out.push_str("=\"");
        push_label_value(value, self.out);
        self.out.push('"');
    }

    /// Append one optional label; an absent value is written as `""`.
    pub fn opt(&mut self, key: &str, value: Option<&str>) {
        self.label(key, value.unwrap_or(""));
    }
}

fn fragment(write: impl FnOnce(&mut LabelWriter<'_>)) -> String {
    let mut out = String::new();
    write(&mut LabelWriter { out: &mut out });
    out
}

const fn bool_label(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

/// Append `s` as an OpenMetrics label value, escaping `\`, `"` and newline. A
/// value without those bytes is written unchanged — the only case upstream's
/// unescaped writer produces a valid document for.
pub fn push_label_value(s: &str, out: &mut String) {
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
}

/// An integer written the way `prometheus-client` writes an `f64`: through
/// `dtoa`, which spells an integral value with a trailing `.0` and never uses
/// an exponent at these magnitudes. The value goes through `f64` first so a
/// sum past 2^53 rounds exactly as upstream's does.
struct Float(u64);

impl core::fmt::Display for Float {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut digits = String::new();
        let _ = write!(digits, "{}", self.0 as f64);
        f.write_str(&digits)?;
        if !digits.contains('.') {
            f.write_str(".0")?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests;
