// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael
//
//! Byte-compatible C ABI struct layouts + the shared ownership-function
//! families.
//!
//! zenoh-pico's owned types are macro-generated by-value structs the C side
//! stack-allocates (`api/olv_macros.h`), not opaque pointers. A drop-in must
//! therefore match each owned struct's SIZE and hide its Rust handle in the
//! pico value's leading pointer slot. This module reproduces the layouts wz
//! Round 1 exercises (an ABI is not copyrightable expression, so this is a
//! clean-room reproduction of the layout contract, not a copy of pico's
//! EPL/Apache headers). Grounded sizes (LP64), all verified against
//! `~/zenoh-pico/`:
//!
//! | type                | pico layout                              | size |
//! |---------------------|------------------------------------------|------|
//! | session (owned)     | `{ void* _val; void* _cnt }` (rc)        | 16 B |
//! | config (owned)      | `{ _z_config_t }` (open hashmap)         | 32 B |
//! | bytes (owned)       | `{ _z_bytes_t }` (arc-slice svec)        | 32 B |
//! | slice (owned)       | `{ _z_slice_t }`                         | 32 B |
//! | string (owned)      | `{ _z_string_t }` (`{ _z_slice_t }`)     | 32 B |
//! | closure_sample      | `{ void* context; call; drop }`          | 24 B |
//! | view_keyexpr        | `{ _z_declared_keyexpr_t }`              | 48 B |
//!
//! For every owned value type we store our Rust handle (`Box::into_raw`) in
//! the leading pointer slot and zero-pad the remainder. The C side never
//! reads the padding directly — it only passes the struct (by pointer) back
//! to our exported accessors — so this is safe and forward-compatible.
//!
//! Publisher / subscriber owned structs are also stack-allocated by a real
//! pico program, but their exact size is `Z_FEATURE`-flag dependent; Round 1
//! ships this crate's own header (a program compiled against it is
//! self-consistent) and defers the full binary size-match audit to a
//! follow-up round.

use std::ffi::c_void;

// A raw pointer used as an FFI handle slot. Zeroed = "null / not present".
type Handle = *mut c_void;

/// The sentinel a handle value type parks in `_pad[0]` to say "slot 0 is a
/// BORROW, not an owned `Box`".
///
/// `1` is chosen because it is not a valid `Box::into_raw` result for any type
/// this crate boxes (all are over-aligned relative to 1) and because every
/// producer of an owned struct already zeroes the padding — so the tag is
/// unforgeable by accident, and its absence is the pre-existing default rather
/// than something each constructor has to opt into.
pub(crate) const HANDLE_BORROWED_TAG: usize = 1;

/// Whether an owned handle struct's slot 0 is a BORROW that its `drop` must not
/// free.
///
/// wz's owned value types normally carry a `Box::into_raw` handle that their
/// `z_*_drop` reclaims. One case breaks that rule, and it comes from upstream
/// rather than from wz: a C program is entitled to read a CONCRETE pico struct
/// field — `z_pong.c` does `z_owned_bytes_t payload = {._val = sample->payload}`
/// — which bitwise-copies a value the sample still owns. pico survives this
/// because its `_z_bytes_t` is an `_z_arc_slice_svec_t` carrying an `_aliased`
/// flag, and its `_z_svec_clear` skips the free when that flag is set. This
/// trait is the same discipline in wz's handle model: the flag lives in
/// `_pad[0]` instead of inside a vector header, and the ownership family reads
/// it in exactly the two places ownership transfers — `drop` and the
/// take-the-payload path.
///
/// The default is `false`, which is the right answer for every type whose
/// values only ever come from a wz constructor. A type overrides it when a C
/// program can obtain one of its values by reading pico's own struct layout.
pub(crate) trait HandleOwnership {
    /// `true` iff slot 0 is borrowed and `z_*_drop` must leave it alone.
    fn handle_is_borrowed(&self) -> bool {
        false
    }
}

// ---------------------------------------------------------------------------
// 32-byte handle value types: config, bytes, slice, string.
// ---------------------------------------------------------------------------

macro_rules! define_handle_type {
    ($Owned:ident, $Loaned:ident, $Moved:ident, $pad:expr) => {
        /// Owned value: our handle in slot 0, zero padding to the pico size.
        #[repr(C)]
        pub struct $Owned {
            pub(crate) handle: Handle,
            pub(crate) _pad: [Handle; $pad],
        }

        /// Loaned view: identical layout; slot 0 is the same handle. `loan`
        /// hands back a pointer to the owned struct (its value is at offset 0).
        #[repr(C)]
        pub struct $Loaned {
            pub(crate) handle: Handle,
            pub(crate) _pad: [Handle; $pad],
        }

        /// Moved wrapper: `{ owned _this }` (pico `z_moved_*_t`).
        #[repr(C)]
        pub struct $Moved {
            pub(crate) _this: $Owned,
        }

        impl $Owned {
            #[inline]
            pub(crate) fn null_value() -> Self {
                Self {
                    handle: std::ptr::null_mut(),
                    _pad: [std::ptr::null_mut(); $pad],
                }
            }
        }
    };
}

define_handle_type!(z_owned_config_t, z_loaned_config_t, z_moved_config_t, 3);
define_handle_type!(z_owned_bytes_t, z_loaned_bytes_t, z_moved_bytes_t, 3);

// The NO-BORROWED-FORM census. Every handle value type in this crate is listed
// here or overrides below, so "does this type have a borrowed form?" is answered
// by one readable block rather than by seven scattered impls. A new type that
// forgets to answer does not compile: the ownership macro's `drop` calls the
// trait, so the compiler enumerates the omissions.
//
// Each of these is `false` for the same reason: a C program can only obtain one
// of their values from a wz constructor, never by reading a field of one of
// pico's concrete structs.
impl HandleOwnership for z_owned_config_t {}
impl HandleOwnership for crate::encoding::z_owned_encoding_t {}
impl HandleOwnership for crate::pubsub::z_owned_publisher_t {}
impl HandleOwnership for crate::pubsub::z_owned_subscriber_t {}
impl HandleOwnership for crate::querier::z_owned_querier_t {}
impl HandleOwnership for crate::query::z_owned_queryable_t {}
impl HandleOwnership for crate::serde::z_owned_bytes_writer_t {}
impl HandleOwnership for crate::serde::ze_owned_serializer_t {}

/// bytes is the ONE type with a borrowed form, and the reason is upstream's:
/// `z_pong.c` builds a `z_owned_bytes_t` by copying `sample->payload` — a field
/// of pico's concrete `_z_sample_t` — out of a sample that still owns it. See
/// [`HandleOwnership`] and `SampleMarshal`'s pico-layout prefix.
impl HandleOwnership for z_owned_bytes_t {
    fn handle_is_borrowed(&self) -> bool {
        self._pad[0] as usize == HANDLE_BORROWED_TAG
    }
}

impl z_owned_bytes_t {
    /// A BORROWED bytes value over `buf`, the shape `SampleMarshal` parks at
    /// pico's `offsetof(_z_sample_t, payload)` so a C program reading that field
    /// gets something wz can recognise on the way back in.
    pub(crate) fn borrowed(buf: *const c_void) -> Self {
        Self {
            handle: buf as *mut c_void,
            _pad: [
                HANDLE_BORROWED_TAG as *mut c_void,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
            ],
        }
    }
}

// ---------------------------------------------------------------------------
// slice: the BORROWED-VIEW model (the shape string already uses).
//
// slice does not use `define_handle_type!` because pico has a `z_view_slice_t`
// that LOANS into `z_loaned_slice_t` (`_Z_VIEW_FUNCTIONS_DEF(slice)`,
// `api/primitives.h:1495`), and a view borrows storage it does not own. With a
// handle-shaped loaned form there is nothing a view could loan into without
// allocating a `Vec` it would then have to leak — the view has no drop. So the
// loaned form is a `{ start, len }` borrow pair and the OWNED form carries a
// cached self-view, exactly as string does; `z_slice_data` / `z_slice_len` then
// read the same two fields whichever producer they came from.
// ---------------------------------------------------------------------------

/// Loaned slice — a borrowed `{ start, len }`. Produced both by an owned
/// slice's `z_slice_loan` (via its cached self-view) and by
/// `z_view_slice_loan`.
#[repr(C)]
pub struct z_loaned_slice_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
}

/// View slice (pico `z_view_slice_t`, a view of `_z_slice_t` = 32 B). Slots 0/1
/// are `{ start, len }` so `z_view_slice_loan` is a pointer reinterpretation.
#[repr(C)]
pub struct z_view_slice_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
    pub(crate) _pad: [usize; 2],
}

/// Owned slice (32 B): our handle → a heap `SliceState`. Its loan derives a
/// `z_loaned_slice_t` from the state's cached self-view.
#[repr(C)]
pub struct z_owned_slice_t {
    pub(crate) handle: Handle,
    pub(crate) _pad: [Handle; 3],
}

/// Moved owned slice (pico `z_moved_slice_t`).
#[repr(C)]
pub struct z_moved_slice_t {
    pub(crate) _this: z_owned_slice_t,
}

impl z_owned_slice_t {
    #[inline]
    pub(crate) fn null_value() -> Self {
        Self {
            handle: std::ptr::null_mut(),
            _pad: [std::ptr::null_mut(); 3],
        }
    }
}

// ---------------------------------------------------------------------------
// Borrowed {ptr,len} view loaned types: keyexpr, string, and the string view.
//
// pico view types alias external storage; the loaned form is the underlying
// value read by-pointer, never freed. keyexpr and string reading go through
// this model so `z_keyexpr_as_view_string` and the owned-string loan both
// yield the SAME `z_loaned_string_t` (a `{ start, len }` borrow) that
// `z_string_data` / `z_string_len` read — no allocation, no leak.
// ---------------------------------------------------------------------------

/// Loaned keyexpr. pico's `z_loaned_keyexpr_t` is `_z_declared_keyexpr_t`
/// (`{ _declaration, _inner }`, 48 B) and BOTH a view keyexpr and a declared
/// one loan to it — `z_view_keyexpr_loan` and `z_keyexpr_loan` return the same
/// type. wz reproduces that by giving the two producers ONE layout:
///
/// | slot | view (borrowed literal) | declared (`z_declare_keyexpr`) |
/// |------|-------------------------|--------------------------------|
/// | 0/1  | `{ start, len }` into the caller's storage | `{ start, len }` into the OWNED copy |
/// | 2    | null                    | `Box<DeclaredKeyexpr>` handle  |
/// | 3    | 0                       | the wire mapping id (never 0)  |
///
/// Keeping `{ start, len }` at slots 0/1 for BOTH is what lets
/// [`crate::keyexpr::keyexpr_str`] stay a single branchless read: the literal
/// is always there, and the declaration is additive information a publish path
/// may consult. The alternative — a handle at slot 0 for the owned form —
/// would make slot 0 ambiguous (a non-null pointer means "literal" in one arm
/// and "handle" in the other) and force every reader to carry a tag.
///
/// Slot 3 doubles as the discriminant: `mapping == 0` is "not declared", which
/// is sound rather than merely convenient, because 0 is RESERVED on the wire
/// (`SendDeclareError::ReservedMappingIdZero`) and can never be a real id.
#[repr(C)]
pub struct z_loaned_keyexpr_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
    pub(crate) _handle: Handle,
    pub(crate) _mapping: usize,
}

impl z_loaned_keyexpr_t {
    /// The BORROWED arm: a literal `{ start, len }` with no declaration.
    ///
    /// Every inbound keyexpr (a delivered sample's, a received query's) is
    /// built through here. A constructor rather than six struct literals
    /// because the two declaration slots must be zeroed at every one of those
    /// sites, and a forgotten zero would be read as a live mapping id — the
    /// publish path would then alias an id the peer never received.
    #[inline]
    pub(crate) fn borrowed(start: *const u8, len: usize) -> Self {
        Self {
            _start: start,
            _len: len,
            _handle: std::ptr::null_mut(),
            _mapping: 0,
        }
    }
}

/// View keyexpr (pico `z_view_keyexpr_t`, 48 B). Slots 0/1 are `{ start, len }`
/// so `z_view_keyexpr_loan` is a pointer reinterpretation to
/// `z_loaned_keyexpr_t`; `_pad` covers the declaration slots a view never
/// carries, and `z_view_keyexpr_from_str` zeroes it.
#[repr(C)]
pub struct z_view_keyexpr_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
    pub(crate) _pad: [usize; 4],
}

/// Owned keyexpr (pico `z_owned_keyexpr_t`, 48 B — measured with a real C
/// compiler against pico's headers, same size as the view because pico wraps
/// the same `_z_declared_keyexpr_t`).
///
/// Produced only by [`crate::keyexpr::z_declare_keyexpr`]. Its first four slots
/// are laid out exactly as [`z_loaned_keyexpr_t`], so `z_keyexpr_loan` is a
/// pointer reinterpretation, matching every other type in this module.
#[repr(C)]
pub struct z_owned_keyexpr_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
    pub(crate) _handle: Handle,
    pub(crate) _mapping: usize,
    pub(crate) _pad: [usize; 2],
}

/// Moved owned keyexpr (pico `z_moved_keyexpr_t`).
#[repr(C)]
pub struct z_moved_keyexpr_t {
    pub(crate) _this: z_owned_keyexpr_t,
}

impl z_owned_keyexpr_t {
    #[inline]
    pub(crate) fn null_value() -> Self {
        Self {
            _start: std::ptr::null(),
            _len: 0,
            _handle: std::ptr::null_mut(),
            _mapping: 0,
            _pad: [0usize; 2],
        }
    }
}

/// Loaned string — a borrowed `{ start, len }`. Produced both by an owned
/// string's `z_string_loan` (via its cached self-view) and by
/// `z_view_string_loan`.
#[repr(C)]
pub struct z_loaned_string_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
}

/// View string (pico `z_view_string_t`, a view of `_z_string_t` = 32 B).
#[repr(C)]
pub struct z_view_string_t {
    pub(crate) _start: *const u8,
    pub(crate) _len: usize,
    pub(crate) _pad: [usize; 2],
}

/// Owned string (32 B): our handle → a heap `StringState`. Its loan derives a
/// `z_loaned_string_t` from the state's cached self-view.
#[repr(C)]
pub struct z_owned_string_t {
    pub(crate) handle: Handle,
    pub(crate) _pad: [Handle; 3],
}

/// Moved owned string (pico `z_moved_string_t`).
#[repr(C)]
pub struct z_moved_string_t {
    pub(crate) _this: z_owned_string_t,
}

impl z_owned_string_t {
    #[inline]
    pub(crate) fn null_value() -> Self {
        Self {
            handle: std::ptr::null_mut(),
            _pad: [std::ptr::null_mut(); 3],
        }
    }
}

/// Read a borrowed `{ start, len }` loaned view as a byte slice.
///
/// # Safety
/// `start`/`len` must describe live borrowed storage (the pico view contract).
#[inline]
pub(crate) unsafe fn view_bytes<'a>(start: *const u8, len: usize) -> Option<&'a [u8]> {
    if start.is_null() {
        return None;
    }
    Some(std::slice::from_raw_parts(start, len))
}

/// Emit the pico ownership 7-function core shared by every handle value type
/// (`internal_null`, `internal_check`, `loan`, `loan_mut`, `move`, `take`,
/// `drop`). This is the exact set pico's `_Z_OWNED_FUNCTIONS_NO_COPY_NO_MOVE`
/// generates (session / publisher / subscriber); the full-DEF value types
/// layer `take_from_loaned` (+ per-type `clone`) on top via
/// [`impl_value_ownership`].
///
/// Every export is wrapped in a panic guard: a Rust unwind across the C ABI
/// boundary is UB. The pointer-cast bodies cannot themselves panic, but the
/// uniform guard is cheap and future-proofs the surface (e.g. `drop` runs the
/// payload's `Drop`, which could panic).
macro_rules! impl_handle_ownership7 {
    ($Owned:ty, $Loaned:ty, $Moved:ty, $free:path,
     $null:ident, $check:ident, $loan:ident, $loan_mut:ident,
     $mv:ident, $take:ident, $drop:ident) => {
        /// Zero the owned struct in place (pico `z_internal_*_null`).
        #[no_mangle]
        pub unsafe extern "C" fn $null(obj: *mut $Owned) {
            if obj.is_null() {
                return;
            }
            *obj = <$Owned>::null_value();
        }

        /// `true` iff the owned struct holds a live handle
        /// (pico `z_internal_*_check`).
        #[no_mangle]
        pub unsafe extern "C" fn $check(obj: *const $Owned) -> bool {
            $crate::ffi::guard_val(false, || !obj.is_null() && !(*obj).handle.is_null())
        }

        /// Borrow immutably (pico `z_*_loan`). The loaned view has the same
        /// layout, so this is a pointer reinterpretation.
        #[no_mangle]
        pub unsafe extern "C" fn $loan(obj: *const $Owned) -> *const $Loaned {
            obj as *const $Loaned
        }

        /// Borrow mutably (pico `z_*_loan_mut`).
        #[no_mangle]
        pub unsafe extern "C" fn $loan_mut(obj: *mut $Owned) -> *mut $Loaned {
            obj as *mut $Loaned
        }

        /// Move-cast (pico `z_*_move`) — a pure reinterpretation; nulls
        /// nothing (the consuming callee is responsible for that).
        #[no_mangle]
        pub unsafe extern "C" fn $mv(obj: *mut $Owned) -> *mut $Moved {
            obj as *mut $Moved
        }

        /// Take the value out of `src` into `dst`, leaving `src` null
        /// (pico `z_*_take`).
        #[no_mangle]
        pub unsafe extern "C" fn $take(dst: *mut $Owned, src: *mut $Moved) {
            if dst.is_null() || src.is_null() {
                return;
            }
            (*dst).handle = (*src)._this.handle;
            (*dst)._pad = (*src)._this._pad;
            (*src)._this = <$Owned>::null_value();
        }

        /// Drop the owned value (pico `z_*_drop`). Idempotent on a null
        /// handle, and a NO-OP on a BORROWED one (see [`HandleOwnership`]).
        /// Guarded because the payload's `Drop` runs here.
        #[no_mangle]
        pub unsafe extern "C" fn $drop(obj: *mut $Moved) {
            let _ = $crate::ffi::guarded(|| {
                if obj.is_null() {
                    return $crate::result::Z_OK;
                }
                let h = (*obj)._this.handle;
                if !h.is_null() {
                    if !$crate::abi::HandleOwnership::handle_is_borrowed(&(*obj)._this) {
                        $free(h);
                    }
                    (*obj)._this = <$Owned>::null_value();
                }
                $crate::result::Z_OK
            });
        }
    };
}

pub(crate) use impl_handle_ownership7;

/// The full-DEF value-type family: the 7-function core plus
/// `take_from_loaned` (pico `_Z_OWNED_FUNCTIONS_DEF` minus the per-type
/// `clone`, which is hand-written in the owning module).
macro_rules! impl_value_ownership {
    ($Owned:ty, $Loaned:ty, $Moved:ty, $free:path,
     $null:ident, $check:ident, $loan:ident, $loan_mut:ident,
     $mv:ident, $take:ident, $drop:ident, $take_from_loaned:ident) => {
        $crate::abi::impl_handle_ownership7!(
            $Owned, $Loaned, $Moved, $free, $null, $check, $loan, $loan_mut, $mv, $take, $drop
        );

        /// Adopt a loaned value into an owned, nulling the source location
        /// (pico `z_*_take_from_loaned`).
        #[no_mangle]
        pub unsafe extern "C" fn $take_from_loaned(
            dst: *mut $Owned,
            src: *mut $Loaned,
        ) -> $crate::result::ZResult {
            if dst.is_null() || src.is_null() {
                return $crate::result::Z_ERR_NULL;
            }
            (*dst).handle = (*src).handle;
            (*dst)._pad = (*src)._pad;
            (*src).handle = std::ptr::null_mut();
            (*src)._pad = [std::ptr::null_mut(); 3];
            $crate::result::Z_OK
        }
    };
}

pub(crate) use impl_value_ownership;

/// Emit the OWNED-ELEMENT family for a plane whose LOANED form is a borrowed
/// callback marshal (`sample`, `reply`, `query`).
///
/// These three differ from every type above in one structural way, and it is
/// the reason they need their own emitter rather than
/// [`impl_handle_ownership7`]. For a handle value type the loaned form has the
/// SAME layout as the owned one, so `loan` is a pointer reinterpretation. Here
/// the loaned form is a pointer to the marshal itself — that is what the
/// existing accessors read, because that is what a subscriber/query/reply
/// callback is handed — so `loan` must hand back the marshal the owned struct
/// POINTS AT, not the owned struct's own address.
///
/// The owned struct is a `$size`-byte block (pico stack-allocates it, so the
/// size is fixed by upstream's header and is pinned by the caller's
/// `const _` assertion) carrying this crate's `Box` handle in slot 0. That
/// layout is `memcpy`-relocatable, which pico's channel machinery requires:
/// `_z_<handler>_elem_move` copies `sizeof(z_owned_*_t)` bytes out of a heap
/// cell and frees the original.
///
/// `take_from_loaned` DEEP-COPIES rather than moving. Upstream can move because
/// its loaned value is a full `_z_sample_t` the caller owns; wz's is a
/// dispatcher-owned marshal that is still borrowed by the frame around the
/// callback (and, when a session holds several matching subscriptions, by the
/// next callback too). Copying is what makes the escape sound; the cost is one
/// payload copy per channel push, which is the honest price of the borrow
/// model this crate already uses everywhere else.
macro_rules! impl_boxed_element {
    ($Owned:ident, $Moved:ident, $Loaned:ty, $size:expr,
     $free:path, $deep_copy:path,
     $null:ident, $check:ident, $loan:ident, $loan_mut:ident,
     $mv:ident, $take:ident, $drop:ident, $take_from_loaned:ident) => {
        /// Owned element: this crate's boxed marshal handle in slot 0, inert
        /// padding to pico's measured size.
        #[repr(C)]
        pub struct $Owned {
            pub(crate) handle: *mut ::std::ffi::c_void,
            pub(crate) _pad: [u8; $size - ::std::mem::size_of::<*mut ::std::ffi::c_void>()],
        }

        /// Moved element (pico `z_moved_*_t`).
        #[repr(C)]
        pub struct $Moved {
            pub(crate) _this: $Owned,
        }

        impl $Owned {
            #[inline]
            pub(crate) fn null_value() -> Self {
                Self {
                    handle: ::std::ptr::null_mut(),
                    _pad: [0u8; $size - ::std::mem::size_of::<*mut ::std::ffi::c_void>()],
                }
            }
        }

        /// Zero the owned struct in place (pico `z_internal_*_null`).
        #[no_mangle]
        pub unsafe extern "C" fn $null(obj: *mut $Owned) {
            if obj.is_null() {
                return;
            }
            *obj = <$Owned>::null_value();
        }

        /// `true` iff the owned struct holds a live marshal
        /// (pico `z_internal_*_check`).
        #[no_mangle]
        pub unsafe extern "C" fn $check(obj: *const $Owned) -> bool {
            $crate::ffi::guard_val(false, || !obj.is_null() && !(*obj).handle.is_null())
        }

        /// Borrow the marshal (pico `z_*_loan`). Hands back the POINTEE, which
        /// is the same address a callback receives.
        #[no_mangle]
        pub unsafe extern "C" fn $loan(obj: *const $Owned) -> *const $Loaned {
            if obj.is_null() {
                return ::std::ptr::null();
            }
            (*obj).handle as *const $Loaned
        }

        /// Borrow the marshal mutably (pico `z_*_loan_mut`).
        #[no_mangle]
        pub unsafe extern "C" fn $loan_mut(obj: *mut $Owned) -> *mut $Loaned {
            if obj.is_null() {
                return ::std::ptr::null_mut();
            }
            (*obj).handle as *mut $Loaned
        }

        /// Move-cast (pico `z_*_move`).
        #[no_mangle]
        pub unsafe extern "C" fn $mv(obj: *mut $Owned) -> *mut $Moved {
            obj as *mut $Moved
        }

        /// Take the value out of `src` into `dst`, leaving `src` null
        /// (pico `z_*_take`).
        #[no_mangle]
        pub unsafe extern "C" fn $take(dst: *mut $Owned, src: *mut $Moved) {
            if dst.is_null() || src.is_null() {
                return;
            }
            (*dst).handle = (*src)._this.handle;
            (*dst)._pad = (*src)._this._pad;
            (*src)._this = <$Owned>::null_value();
        }

        /// Release the owned element (pico `z_*_drop`). Idempotent.
        #[no_mangle]
        pub unsafe extern "C" fn $drop(obj: *mut $Moved) {
            let _ = $crate::ffi::guarded(|| {
                if obj.is_null() {
                    return $crate::result::Z_OK;
                }
                let handle = (*obj)._this.handle;
                if !handle.is_null() {
                    $free(handle);
                    (*obj)._this = <$Owned>::null_value();
                }
                $crate::result::Z_OK
            });
        }

        /// Escape a borrowed marshal into an owned one
        /// (pico `z_*_take_from_loaned`). See the macro doc for why this is a
        /// deep copy.
        #[no_mangle]
        pub unsafe extern "C" fn $take_from_loaned(
            dst: *mut $Owned,
            src: *mut $Loaned,
        ) -> $crate::result::ZResult {
            $crate::ffi::guarded(|| {
                if dst.is_null() {
                    return $crate::result::Z_ERR_NULL;
                }
                *dst = <$Owned>::null_value();
                if src.is_null() {
                    return $crate::result::Z_ERR_NULL;
                }
                let handle = $deep_copy(src as *const $Loaned);
                if handle.is_null() {
                    return $crate::result::Z_ERR_GENERIC;
                }
                (*dst).handle = handle;
                $crate::result::Z_OK
            })
        }
    };
}

pub(crate) use impl_boxed_element;

// ---------------------------------------------------------------------------
// Handle read helper.
// ---------------------------------------------------------------------------

/// Read the boxed payload behind a loaned/owned value's handle slot as `&T`,
/// or `None` if the pointer or handle is null.
///
/// # Safety
/// The handle at offset 0 of `*ptr` must be a live `Box::into_raw::<T>`
/// pointer of the correct type, or null.
#[inline]
pub(crate) unsafe fn handle_ref<'a, S, T>(ptr: *const S) -> Option<&'a T> {
    if ptr.is_null() {
        return None;
    }
    // Every value type in this module lays its handle out at offset 0.
    let handle = *(ptr as *const Handle);
    if handle.is_null() {
        return None;
    }
    Some(&*(handle as *const T))
}
