// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! `sce_link_runtime_tokio` — Tokio + mio epoll runtime for the
//! watching-zenoh AP linux target.
//!
//! Phase Z entry (R51). The trait surface here matches
//! `docs/runtime-crate-tokio.md` §2.1 minimum: open / send / close /
//! poll_event. Trust-class gating, io_uring opt-in, and pool-slot Rx
//! borrows are deferred to later rounds; the R51-R52 scope is the
//! 4-method baseline + a TCP impl + the R52 echo demo (publisher /
//! subscriber tokio tasks on loopback).
//!
//! R54 entry. The R29 session_fsm.scxml script-action placeholders
//! are wired to `LinkDriver` through `session_glue::SessionLinkActions`
//! plus Lua-engine `register_global_function` registrations. The
//! generated state machine emit lives at `pub mod session_fsm_unicast`
//! and is composed via `session_glue::install_session_actions` for
//! every native dispatch from `<script>...</script>` action bodies.

// R311cb — TCP/UDP imports are wire-up-gated. cfg-off elides the
// tokio::net dependency at the driver-construction site (the tokio
// dep stays unconditional because session_glue.rs uses tokio::time +
// tokio::sync regardless of which link kind is enabled).
#[cfg(feature = "transport-link-tcp")]
use sce_forge_runtime::codec::SceCursor;
use std::io;
#[cfg(any(feature = "transport-link-tcp", feature = "transport-link-udp"))]
use std::net::SocketAddr;
#[cfg(feature = "transport-link-tcp")]
use tokio::io::{AsyncReadExt, AsyncWriteExt};
#[cfg(feature = "transport-link-tcp")]
use tokio::net::TcpStream;
#[cfg(feature = "transport-link-udp")]
use tokio::net::UdpSocket;
#[cfg(feature = "transport-link-tcp")]
use wz_codecs::stream_envelope::StreamEnvelope;

// R311mk — `session_glue` is the unicast handshake driver (it names the
// `SessionFsmUnicast{Policy,Event}` types + drives `session_actions` /
// `session_timeouts` / `drive`, all `session-unicast`-gated in
// wz-session-core), so it is gated on `transport-unicast`. Previously it
// compiled unconditionally and a `transport-multicast`-only build (no
// `transport-unicast`) failed on its unicast imports — the facade
// composability gap this round closes. The shared reassembly-pool wiring it
// used to host moved to the always-available `crate::reassembly` SSOT; the
// multicast transport drive loop (`multicast_glue`) is independent of this
// module (it dispatches into the shared `ApplicationLayerObserver` directly,
// not through the unicast `SessionLinkActions`).
#[cfg(feature = "transport-unicast")]
pub mod session_glue;

/// SCE-generated AP reassembly buffer-pool config. The emit comes from
/// `sources/network/reassembly_pool_ap.scxml` (an `sce:kind="buffer-pool"`
/// document, the SSOT). R311y22b: COMMITTED at
/// `out/wz-runtime-tokio/reassembly_pool_ap.rs` and `include!`-ed from there
/// (regenerated by the `xtask` codegen SSOT + the Layer B2 regen-diff gate, so
/// this crate has no build script); compiled only under the `reassembly`
/// feature via the `#[cfg]` on the wrapping module below.
///
/// R311in — exposes the spec-anchored pool constants the host
/// `ReassemblyDispatcher` consumes: `SLOT_COUNT` / `SLOT_SIZE` (the
/// dispatcher const generics) and `PER_PEER_QUOTA` /
/// `REASSEMBLY_TIMEOUT_MS` (the `ReassemblyConfig` runtime knobs). This
/// replaces the formerly hand-transcribed `4 / 4096 / 2 / 500` constants
/// in `session_glue.rs`; the values now have a single SCE-owned source
/// (see the scxml header). The xtask strips the file-head
/// `#![...]` inner attributes and the trailing SCE-pool-API
/// `generated_tests` module; the lint allows are restored here as outer
/// attributes on the wrapping module. SCE's §5.E DMA slot-pool API in the
/// emit (`Slot<S>` / the pool struct) is unused by the AP host (the
/// dispatcher owns its own strict-in-order staging) and is dead code.
#[cfg(feature = "reassembly")]
#[allow(non_snake_case)]
#[allow(unused_imports)]
#[allow(dead_code)]
#[allow(unused_variables)]
#[allow(unused_mut)]
#[allow(clippy::all)]
pub mod reassembly_pool_ap {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../out/wz-runtime-tokio",
        "/reassembly_pool_ap.rs"
    ));
}

/// R311mk — shared AP reassembly-pool wiring: the [`reassembly::TokioReassembly`]
/// Router type + [`reassembly::reassembly_config`], hoisted out of
/// [`session_glue`] (the unicast handshake driver) so a `transport-multicast`-only
/// build reaches the pool config without `transport-unicast`. Transport-agnostic
/// SSOT — both the unicast and multicast drive loops run a pool instance over
/// the same SCE-sourced AP dims/knobs. Gated on `reassembly` (the dims come from
/// [`reassembly_pool_ap`]).
#[cfg(feature = "reassembly")]
pub mod reassembly;

// Crate-local fixtures for this crate's OWN unit tests (recording driver
// + actions builders). Kept in-crate — NOT in the test-support sibling —
// so unit tests receive this crate's version of `SessionLinkActions`
// (the dev-dependency cycle would otherwise hand them a second copy that
// `Session::new` rejects). See the module docs.
#[cfg(test)]
mod test_fixtures;

// R311il — the `script_bind` module (the generic Lua `bind_unit` /
// `bind_guard` binders) was retired with the engine-free session FSM
// migration: scouting dropped it at R311ik and the session FSM was its
// last consumer, so no SCXML in the workspace is Lua-bound any more.

/// R221 — zenoh keyexpr canonicalization mirror. Mirrors the
/// structural-only canonicalization performed by zenoh-pico's
/// `_z_keyexpr_canonize` so wz-side subscriber / queryable
/// registrations store the canonical form a peer would emit on the
/// wire. See `keyexpr_canon` module doc comment for the scope (no
/// lowercase / no NFC — pure structural) and the call-site wiring.
// R311di-2 — keyexpr_canon moved to wz-session-core; re-export keeps
// `crate::keyexpr_canon::*` callsites verbatim across the wz-runtime-tokio
// surface (query.rs / pubsub.rs / session.rs / session_glue.rs).
//
// R311fd — the re-export is UNCONDITIONAL (was `#[cfg(feature =
// "keyexpr-canon")]` per R311cf's intent to gate the canonicalization
// mirror). That gate became inconsistent and broke composability: the
// R311o type-ungating cascade made `OutboundKeyexprError` unconditional
// (it is wrapped by the always-present `LivelinessAliasError::Invalid
// Keyexpr` variant, and `session.rs` imports it unconditionally), so the
// keyexpr_canon *types* are foundational by signature-stability. The
// backing module is also always present: wz-runtime-tokio enables
// `wz-session-core/alloc` unconditionally (Cargo.toml — tokio is AP-only,
// always-alloc), and wz-session-core gates `keyexpr_canon` on `alloc`.
// So a build that turned `keyexpr-canon` OFF had a phantom-gated re-export
// while the module + unconditional consumers were still present — every
// such subset failed to compile (carry #3: udp-off / keyexpr-canon-off
// coherent subsets). Making the re-export unconditional aligns the gate
// with reality. `keyexpr-canon` is therefore a FOUNDATIONAL feature, not
// an excludable atomic; the Cargo feature is retained as a no-op
// compatibility marker (see the manifests). Genuine exclusion is
// impossible without reverting R311o's signature-stability ungating.
pub use wz_session_core::keyexpr_canon;

/// R223 — zenoh-style locality filter for subscribers and queryables.
/// Mirrors zenoh-pico's `z_locality_t` enum and the
/// `_z_locality_allows_local` / `_z_locality_allows_remote` helpers
/// so applications can register subscriptions that fire only on
/// session-local samples, only on remote samples, or both
/// (default). See `locality` module doc for the dispatch invariant
/// and the surface-vs-dispatch distinction.
// R311di-3 — locality moved to wz-session-core; re-export keeps every
// `crate::locality::*` callsite (pubsub.rs / query.rs / session.rs)
// verbatim across the wz-runtime-tokio surface.
pub use wz_session_core::locality;

/// R311pk — the locator parse seam (`parse_any_locator` + the `AnyLocator`
/// sum type its scheme-dispatch produces). Re-exported so a facade consumer
/// (wz-ap-demo's `establish_link`) can turn a `--connect ws/...` argument
/// into the typed locator that [`session_open::dial_locator`] dials — the
/// same parse path `ws_e2e.rs` exercises in-process. Ungated (the locator
/// leaves parse-always regardless of which transport BACKEND is compiled),
/// so naming it never depends on a `transport-link-*` feature.
pub use wz_session_core::locator;

/// R222 / R225 — application-layer `Sample` type for subscriber callbacks.
/// Mirrors zenoh-pico's `_z_sample_t` projection. R222 introduced the
/// three load-bearing fields (`keyexpr` / `kind` / `payload`); R225
/// extends the parity surface with `timestamp` / `encoding` / `qos` /
/// `attachment` / `source_info` / `reliability` so subscribers no longer
/// need to dig into `Push.extensions` to inspect Sample metadata. See
/// the `sample` module doc for the wire-decode origin of each field
/// and the `#[non_exhaustive]` future-additive contract.
// R311di-4 — sample moved to wz-session-core; re-export keeps every
// `crate::sample::*` callsite (pubsub.rs / session.rs / session_glue.rs)
// verbatim across the wz-runtime-tokio surface.
pub use wz_session_core::sample;

/// R311gb-2b — sample-delivery seam (`SampleView` accessor contract +
/// `SampleSink` DIP trait + the `alloc` `BoxedSink` closure adapter).
/// Re-exported so AP consumers name `crate::sink::SampleView` in the
/// `declare_subscriber` closure (the registry now delivers
/// `&dyn SampleView` rather than the owned `&Sample`).
pub use wz_session_core::sink;

/// R311gb-3b — query-dispatch seam: the `QueryView` inbound accessor
/// contract, the `ReplyOut` outbound emit contract, the `QuerySink` DIP
/// trait, and the `alloc` `BoxedQuerySink` closure adapter. Re-exported
/// so AP consumers name `crate::query_sink::{QueryView, ReplyOut}` in the
/// `declare_queryable` closure (the registry now hands the handler a
/// `&dyn QueryView` and a `&mut dyn ReplyOut`, replacing the owned
/// `&QueryEvent` and `&mut ReplyEmitter`).
pub use wz_session_core::query_sink;

/// R311gb-3c — reply-delivery seam (`ReplyKind` + `ReplyView` accessor
/// contract + `ReplySink` DIP trait + the `alloc` `BoxedReplySink`
/// closure adapter). Re-exported so AP consumers name
/// `crate::reply_sink::ReplyView` in the z_get `on_reply` closure (the
/// registry now hands the handler a `&dyn ReplyView` rather than the
/// owned `&InboundReply`).
pub use wz_session_core::reply_sink;

/// R311gb-3d — declare-event observer seam: the `DeclView` accessor
/// contract, the `DeclSink` / `UndeclSink` DIP traits, and the `alloc`
/// `BoxedDeclSink` / `BoxedUndeclSink` closure adapters. Re-exported so AP
/// consumers name `crate::decl_sink::DeclView` in the
/// `on_subscriber_declared` / `on_queryable_declared` / `on_token_declared`
/// closures (the registries now hand the observer a `&dyn DeclView`
/// rather than the owned `(&DeclXOwned, &str)`; the undeclare observer
/// gets the bare `id`).
pub use wz_session_core::decl_sink;

/// R311y45 (§5.23 Phase 2b) — the admin-space `local_data` / config / metrics
/// helpers + the Session-independent `answer_admin_query` SSOT. Re-exported (under
/// `adminspace-core`) so a routing-peer host names
/// `crate::adminspace::answer_admin_query` for its forwarder-hosted admin
/// queryable, the same answerer `Session::declare_adminspace` uses.
#[cfg(feature = "adminspace-core")]
pub use wz_session_core::adminspace;

/// R311y68 (§5.25) — the Zenoh Serialization Format codec
/// (`z_serialize` / `z_deserialize`), re-exported under
/// `ext-pubsub-serde-codec` so an AP consumer serializes typed payloads
/// (and the advanced pub/sub miss-detection heartbeat) without
/// depending on `wz-session-core` directly.
#[cfg(feature = "ext-pubsub-serde-codec")]
pub use wz_session_core::serde_codec;

/// R311y52 (§5.23 `adminspace-write`) — resolve the effective config-WRITE permit
/// from the embedder's [`adminspace::AdminSpacePermissions`]. This is the
/// library-resident write-side mirror of the `adminspace-read` GET gate's per-call
/// `let read = permissions.read` idiom (`Session::declare_adminspace_with_permissions`,
/// `session/mod.rs`). Under the `adminspace-write` cfg it returns
/// `permissions.write` (default `false` — zenoh's `PermissionsConf` asymmetry,
/// lib.rs:893); with the gate compiled out it returns `true` (the gate elided —
/// the pre-y51 apply-all behavior). This is THE `adminspace-write` cfg site, so the
/// `wz` / `wz-runtime-tokio` facade chain gates real library code: a config-write
/// host calls this, then feeds the resolved bool to
/// [`adminspace::parse_admin_config_write`] (the feature-independent gate+decode
/// SSOT — "the gate is the value, not a cfg" once past this resolver).
#[cfg(feature = "adminspace-core")]
pub fn admin_write_permit(permissions: &adminspace::AdminSpacePermissions) -> bool {
    #[cfg(feature = "adminspace-write")]
    {
        permissions.write
    }
    #[cfg(not(feature = "adminspace-write"))]
    {
        let _ = permissions;
        true
    }
}

#[cfg(all(test, feature = "adminspace-core"))]
mod admin_write_permit_tests {
    use super::admin_write_permit;
    use super::adminspace::AdminSpacePermissions;

    #[test]
    fn permit_resolves_per_gate() {
        let granted = AdminSpacePermissions {
            read: true,
            write: true,
        };
        let denied = AdminSpacePermissions {
            read: true,
            write: false,
        };
        #[cfg(feature = "adminspace-write")]
        {
            // Gated: the resolver reads permissions.write (default-deny).
            assert!(admin_write_permit(&granted));
            assert!(!admin_write_permit(&denied));
        }
        #[cfg(not(feature = "adminspace-write"))]
        {
            // Gate elided (pre-y51 apply-all): the value is ignored, always permit.
            assert!(admin_write_permit(&granted));
            assert!(admin_write_permit(&denied));
        }
    }
}

/// The zenoh-hex zid rendering (`zid_to_zenoh_hex`) — re-exported so a consumer
/// builds admin keyexprs (`@/<zid>/<whatami>/...`) without depending on
/// `wz-session-core` directly.
pub use wz_session_core::zid_hex;

/// R98 — application-layer subscriber registry. Routes decoded
/// `NetworkMessage::Push` records to user-registered callbacks
/// filtered by literal keyexpr. See `pubsub::SubscriberRegistry`
/// doc comment for the scope and threading contract.
///
/// R311h — pubsub module stays always-on at the wz-runtime-tokio
/// level (wire-side `codec-push` gating elides session_glue.rs's
/// Push surface; pubsub.rs requires the `wz_codecs::push::Push`
/// type unconditionally because dispatch_push / SampleKind
/// projection / Subscriber RAII reference it directly). The
/// `wz-codecs/codec-push` Cargo dep stays in the wz-runtime-tokio
/// base feature set so the Push module is always compiled.
/// Consumer-module gating cascade (Subscriber / declare_subscriber*
/// / publish* on codec-push) is deferred to R311m for atomic
/// per-cascade footprint per `feedback_signature_stability`
/// MEMORY anchor's architectural deferral carve-out.
pub mod pubsub;

/// R121j-5b — application-layer queryable registry. Q-side mirror of
/// [`pubsub::SubscriberRegistry`]: routes inbound
/// `NetworkMessage::Request` records (Query body arm) to user-
/// registered `on_query` callbacks, which emit Reply / Err records
/// via a [`query::QueryResponder`] borrow. The runtime wiring that
/// turns the accumulated `Vec<QueryReply>` into outbound Response
/// frames lands in R121j-5c. See `query` module doc comment for the
/// scope, threading, and Responder lifetime contract.
///
/// R311r — module is type-ungated. The `QueryableRegistry` struct,
/// the `QueryResponder` internal type, the `QueryReply` accumulator
/// enum, and the supporting types are always defined regardless of
/// the `query-queryable` feature so that the model-B query seam
/// contracts ([`query_sink::QueryView`] / [`query_sink::ReplyOut`])
/// and the type-ungated `Session::declare_queryable{_aliased}`
/// Result-form signatures compile unconditionally. The wire-emit
/// terminal step (`QueryReply::into_response`) remains cfg-gated on
/// `codec-response` — the dispatch / loopback / staging paths stage
/// `QueryReply` records into a `Vec` without needing `codec-response`,
/// so the module body compiles cleanly under any consumer-feature
/// subset.
pub mod query;

/// R311y39 — the typed [`config::WzConfig`] runtime config SSOT (§5.23):
/// read-at-open handshake mirror + the live interceptor/access-control
/// subset, re-applied to the forwarder under `config-mutate-runtime`.
pub mod config;

/// R121k-2 — application-layer remote-declaration registries. Route
/// decoded `Declare(Decl*|Undecl*)` records to user-registered
/// callbacks. This round lands `RemoteSubscriberRegistry`
/// (DeclSubscriber + UndeclSubscriber); R121k-3 adds
/// `RemoteQueryableRegistry`, R121k-4 adds `LivelinessRegistry`. The
/// dispatch wiring that fans inbound `Declare` envelopes through all
/// three lands in R121k-5. See `declare` module doc comment for the
/// scope and callback contract.
pub mod declare;

/// R121j-6 — application-layer reply registry. Z_get-side mirror of
/// [`query::QueryableRegistry`]: routes inbound
/// `NetworkMessage::Response(Reply|Err)` and
/// `NetworkMessage::ResponseFinal` records to per-rid callbacks
/// registered by `z_get`-side callers. Pending entries auto-
/// unregister on `ResponseFinal` (zenoh-pico "exactly one Final
/// terminates the chain" semantics). See `reply` module doc comment
/// for scope, callback shape, and threading.
///
/// R311s — module is type-ungated. The `ReplyRegistry` struct, the
/// `InboundReply` projection, the `ReplyHandle` opaque, and the
/// supporting types are always defined so the type-ungated
/// `Session::query` / `Querier` surface compiles unconditionally; the
/// wire-dispatch / wire-emit terminal steps inside reply.rs stay
/// cfg-gated on the corresponding codec features (codec-response /
/// codec-response-final) so feature-OFF builds elide them naturally.
pub mod reply;

/// R121k-7 — application-layer observer bundle. Combines the six
/// per-domain registries (subscribers, queryables, remote_subscribers,
/// remote_queryables, liveliness, replies) plus the queryable side's
/// pending-reply / pending-final staging buffers into one cohesive
/// struct so production callers drive the whole dispatch graph with
/// a single [`observer::ApplicationLayerObserver::dispatch`] call per
/// [`session_glue::IterationEvent`]. See `observer` module doc
/// comment for the rationale, dispatch flow, and what is NOT in
/// scope.
pub mod observer;

/// R228 — application-level [`session::Session`] bundle. Owns an
/// outbound [`session_glue::SessionLinkActions`] handle plus a
/// shared [`observer::ApplicationLayerObserver`] reference so a
/// single [`session::Session::publish`] call routes through both the
/// wire-side codec and the in-process subscriber loopback per
/// [`session::PublishOptions::allowed_destination`]. Mirrors
/// zenoh-pico's `_z_session_t`. R228 scope: literal-keyexpr Put +
/// Del. Aliased publish + full Sample metadata are R229+ carries.
///
/// R311mk — gated on `transport-unicast`: the [`session::Session`] handle
/// owns a [`session_glue::SessionLinkActions`] bundle (the unicast action
/// machinery), so it is the unicast-session API surface. A
/// `transport-multicast`-only build drives multicast through
/// [`multicast_glue::drive_multicast_session`] over a shared
/// [`observer::ApplicationLayerObserver`] instead of a `Session` handle.
/// Unifying multicast under the `Session` handle (the zenoh-cpp
/// transport-agnostic-session shape) is a separate north-star cascade.
///
/// R311mn (Level B, B2) — gate loosened from `transport-unicast` to
/// `any(transport-unicast, transport-multicast)`: the module now also
/// compiles in a multicast-ONLY build, where `Session` exposes only the
/// transport-agnostic surface (observer / clock / drain_deferred_fires /
/// zid) plus the `Session::new_multicast` constructor. The full unicast
/// publish / query / declare surface inside the module stays
/// `transport-unicast`-gated (it names `session_glue` types); the
/// `session_glue` module itself remains `transport-unicast`.
#[cfg(any(feature = "transport-unicast", feature = "transport-multicast"))]
pub mod session;

/// R4b — the §5.16 pubkey transport-auth method (`PubKeyMethod`, mutual RSA
/// challenge-response, the wz mirror of zenoh `auth/pubkey.rs`). AP-only +
/// std-gated because the `rsa` crate requires std — unlike usrpwd, which lives
/// in the no_std session kernel. The `AuthMethod` trait + dispatch + ZBuf codec
/// stay in `wz-session-core`; this is the concrete impl where its crypto dep
/// mandates. Gated on `access-extauth-pubkey`.
#[cfg(feature = "access-extauth-pubkey")]
pub mod extauth_pubkey;

/// R4b — re-export the `rsa` crate the pubkey method is built against: a
/// `PubKeyMethod`'s constructors take `RsaPrivateKey` / `RsaPublicKey`, so a
/// consumer must name those types, and re-exporting the exact version avoids a
/// version-skew between the caller's `rsa` and the method's.
#[cfg(feature = "access-extauth-pubkey")]
pub use rsa;

/// R311y — per-runtime synchronization primitive aliases (`Mutex<T>`,
/// `RwLock<T>`) implementing the R311w option (a) decision lock on
/// §5.P Mutex/RwLock shape. The tokio profile binds the aliases to
/// `std::sync::*`; a future `wz-runtime-embassy::sync` module will
/// re-bind the same names to `embassy_sync::*` so cross-runtime call
/// sites can switch via cfg gate without renaming. See the module
/// doc-comment for the per-runtime alias rationale and the R311z+
/// migration roadmap.
pub mod sync;

/// R252 — AP-profile concrete impls of the
/// [`wz_runtime_core::Runtime`] and [`wz_runtime_core::TimeSource`]
/// trait contracts authored in R251. [`runtime_impl::TokioRuntime`]
/// spawns tasks via `tokio::task::spawn` and wraps the returned
/// `tokio::task::JoinHandle` into a [`runtime_impl::TokioJoinHandle`]
/// that satisfies the trait's `Future<Output = Result<T,
/// RuntimeError>>` shape by mapping `tokio::task::JoinError` to
/// [`wz_runtime_core::RuntimeError::JoinFailed`].
/// [`runtime_impl::TokioTime`] samples a monotonic
/// `tokio::time::Instant` for `now_monotonic_ms` and yields via
/// `tokio::time::sleep(Duration)` for the async sleep contract. R252
/// lands the impl but leaves the 111 std/tokio call sites unchanged;
/// R253+ migrate them leaf-first, with `Session` last per the
/// §5.P "leaf crates first" guidance.
pub mod runtime_impl;

/// R311il — the engine-free unicast session FSM (the
/// `SessionFsmUnicastState` / `SessionFsmUnicastEvent` enums, the
/// `SessionFsmUnicastActions` host trait, and `SessionFsmUnicastPolicy<A>`)
/// now lives in [`wz_session_core::session_fsm_unicast`] (committed under
/// `out/wz-session-core/` via the `xtask` codegen SSOT (R311y22b), gated
/// `session-unicast`, mirroring the reassembly and scouting FSMs). This crate re-exports it
/// under the same `session_fsm_unicast` module path so every
/// `crate::session_fsm_unicast::…` and
/// `wz_runtime_tokio::session_fsm_unicast::…` callsite is unchanged. The
/// host side ([`session_glue::SessionActionsBinding`] impl plus the drive
/// loop) owns every session deadline and the §2.7 admission guards.
///
/// R311cb — `transport-unicast` is FOUNDATIONAL: it gates this re-export
/// and the entire `session_glue` (which names the `SessionFsmUnicast`
/// event/policy types). cfg-off is intentionally not buildable until
/// transport-multicast (reserved) introduces an alternate FSM; default-on
/// keeps the AP path compiling and gives the future multicast cascade a
/// single edit point.
///
/// R311ml — the R311cb "cfg-off is intentionally not buildable" clause is
/// SUPERSEDED. R311mk structurally decoupled transport-multicast from
/// transport-unicast, so a transport-multicast-only build (transport-unicast
/// OFF) now compiles and drives multicast via
/// [`multicast_glue::drive_multicast_session`] — it simply never names the
/// unicast FSM. `transport-unicast` still gates this re-export + `session_glue`
/// because they name the `SessionFsmUnicast` types, but it is no longer
/// FOUNDATIONAL-as-in-unconditional: transport-multicast is an
/// independently-composable catalog atom (guarded by Layer C4e). Unifying
/// multicast under the [`session::Session`] handle (so a multicast-only build
/// also yields a `Session`, not just the standalone drive loop) is the Level B
/// north-star cascade.
#[cfg(feature = "transport-unicast")]
pub use wz_session_core::session_fsm_unicast;

// R311ik — scouting FSM <-> multicast-link glue (active mode),
// engine-free. The SCE-generated FSM (the `ScoutingActions` trait,
// `ScoutingPolicy<A>`, and the state/event enums) now lives in
// `wz_session_core::scouting` (the FSM was lifted out of this crate into
// the runtime-agnostic core; R311y22b committed it under
// `out/wz-session-core/` via the `xtask` SSOT, mirroring the reassembly
// slot FSM). This module is the host side: the `ScoutingActions` trait
// impl that stages Scout/Hello bytes + the async scout->hello drive loop
// that owns the scout deadline. No Lua engine is involved.
#[cfg(feature = "scouting-active")]
pub mod scouting_glue;

/// Round C — multicast transport drive loop (the AP host loop that drives
/// the `wz-session-core` `MulticastDispatcher` over a UDP-multicast link:
/// periodic JOIN beacon, RX classify -> dispatch, lease sweep). Gated on
/// `transport-multicast` (the §5.1 atom forwarding to `session-multicast`).
#[cfg(feature = "transport-multicast")]
pub mod multicast_glue;

// R311di-4 — Reliability moved to wz-session-core::reliability; the
// re-export keeps every `wz_runtime_tokio::Reliability` external
// callsite (9 caller files across tests / wz-integration-tests /
// wz-ap-demo) verbatim across the migration.
pub use wz_session_core::reliability::Reliability;

// R311di-5 — TxFrame / RxFrame / LinkEvent / LostCause moved to
// wz-session-core::link; tokio-specific LinkDriver trait + driver
// impls (TcpDriver / UdpDriver) stay in this crate. Re-exports keep
// every external callsite (`wz_runtime_tokio::{TxFrame, RxFrame,
// LinkEvent, LostCause}`) verbatim across the migration.
pub use wz_session_core::link::{LinkEvent, LostCause, RxFrame, TxFrame};

/// R311et — canonical split-link session-open transport pipeline. Lifts the
/// read/write-split + writer-task idiom (originally `wz-ap-demo`'s
/// `link_driver.rs`) into the library so the production session-open path
/// has a single home, parameterised by transport.
///
/// The session FSM needs the link in two shapes at once — an async
/// `&mut LinkDriver` for the inbound poll loop
/// ([`session_glue::drive_session_until_terminal`]) and a sync
/// `Arc<dyn BoxedLinkDriver>` for the outbound `send_blocking` fired from
/// Lua script-action handlers. A single `TcpStream` cannot satisfy both, so
/// this module splits it into an [`link_pipeline::TcpReadDriver`] (owns the
/// read half) plus an [`stream_link::StreamWriteDriver`] (a non-blocking
/// channel enqueue) drained by a dedicated [`stream_link::writer_task`].
/// The channel decouples the sync-action / async-runtime boundary WITHOUT
/// `Handle::block_on` (the [`session_glue::TokioLinkDriverAdapter`] path
/// carries a documented current-thread-runtime deadlock hazard and has
/// never driven a full bidirectional session); this split is the model the
/// production AP path actually uses.
///
/// R311oa — the transport-NEUTRAL byte-stream machinery (the read/write
/// drivers + the StreamEnvelope `writer_task`) lives once in
/// [`stream_link`]; `link_pipeline` (TCP) and [`tls_pipeline`] (TLS) carry
/// only their dial/split and instantiate the shared drivers, so a TLS link
/// frames identically to a TCP link with no duplicated impl.
#[cfg(feature = "transport-link-tcp")]
pub mod stream_link;

#[cfg(feature = "transport-link-tcp")]
pub mod link_pipeline;

/// R311ez — datagram sibling of [`link_pipeline`] (UDP). A UDP socket is
/// not split into owned read/write halves; the one socket is shared via
/// `Arc` to back the inbound [`udp_pipeline::UdpReadDriver`] and the
/// outbound [`udp_pipeline::udp_writer_task`]. `dial_udp` binds an
/// ephemeral local socket; `wire_udp_socket` shares it into the
/// read-driver / write-driver / writer-task triple the session FSM
/// consumes. One datagram is exactly one wire message (no length-prefix
/// envelope — UDP preserves boundaries).
#[cfg(feature = "transport-link-udp")]
pub mod udp_pipeline;

/// R311nv — host tty backend for the SERIAL link (the 2nd layer of the
/// R311nt 2-layer split; the transport-agnostic framing/handshake logic is
/// [`wz_session_core::serial_link`]). `dial_serial`/`accept_serial` open the
/// tty ([`tokio_serial`]) + drive the link handshake; `wire_serial_stream`
/// splits the connected stream into the read/write-driver + writer-task
/// triple the session FSM consumes, COBS-framing each payload via the R311ns
/// serial codec. Gated `transport-link-serial` only — the drivers compile
/// standalone; the `session_open` DialedLink::Serial integration rides the
/// `transport-link-tcp`-gated session-open module as an additive serial arm.
#[cfg(feature = "transport-link-serial")]
pub mod serial_pipeline;

/// R311oa — TLS-over-TCP backend for the TLS link. `dial_tls`/`accept_tls`
/// run the rustls client/server handshake; `wire_tls_stream` splits the
/// secured stream into the read/write-driver + writer-task triple the session
/// FSM consumes, reusing the TCP pipeline's `StreamEnvelope` framing
/// ([`link_pipeline::writer_task`] + [`poll_framed`]) — a TLS link frames
/// identically to TCP, differing only in the stream type. Gated
/// `transport-link-tls` (which forwards `transport-link-tcp`); the
/// `session_open` DialedLink::Tls integration rides the
/// `transport-link-tcp`-gated session-open module as an additive TLS arm,
/// exactly like serial.
#[cfg(feature = "transport-link-tls")]
pub mod tls_pipeline;

/// R311og — PEM cert/key material loader for the TLS link. Where
/// [`tls_pipeline`] runs the handshake over a rustls config, this module BUILDS
/// that config from the on-disk PEM an application supplies — the production
/// answer to "where do the certs come from" (the e2e tests' `rcgen` fixture is
/// test-only). `client_config_from_pem` / `server_config_from_pem` parse a PEM
/// cert chain + private key (+ optional CA bundle) into the rustls
/// [`tls_pipeline`]-ready `ClientConfig` / `ServerConfig`; the optional
/// client-auth / client-CA arguments are the mTLS knob (the client presents a
/// cert, the server requires + verifies one), and the client builder's
/// `ServerNameVerification` argument is the verify-name knob (require the cert
/// SAN to match the dialed name, or accept any CA-chained name). Mirrors
/// zenoh-rust `zenoh-link-tls/src/utils.rs` and pico's TLS `session_cfg` cert
/// keys (`ROOT_CA_CERTIFICATE` / `CONNECT_CERTIFICATE` / `LISTEN_CERTIFICATE` /
/// `ENABLE_MTLS` / `VERIFY_NAME_ON_CONNECT`). Gated `transport-link-tls` OR
/// `transport-link-quic` (R311xk — the QUIC link reuses the SAME PEM loaders +
/// rustls 0.23 stack; [`quic_config`] builds its TLS-1.3 + ALPN config on top
/// of these loaders).
#[cfg(any(feature = "transport-link-tls", feature = "transport-link-quic"))]
pub mod tls_config;

/// R311ob — WebSocket-over-TCP backend for the WS link. The DATAGRAM-flow
/// sibling of [`udp_pipeline`], NOT of TCP/TLS: zenoh-pico classes `ws` as
/// `Z_LINK_CAP_FLOW_DATAGRAM`, so each batch rides one WebSocket BINARY
/// message with no length prefix (the message boundary delimits the frame).
/// `dial_ws`/`accept_ws` run the RFC6455 handshake ([`tokio_tungstenite`]);
/// `wire_ws_stream` splits the `WebSocketStream` (Sink+Stream) via
/// `futures_util` into the read-driver + writer-task halves. Reuses neither
/// `stream_link` (no StreamEnvelope) nor a codec; the WS protocol layer IS the
/// framing. Gated `transport-link-ws`; the `session_open` DialedLink::Ws
/// integration rides the `transport-link-tcp`-gated session-open module as an
/// additive WS arm, like udp (and — no cert — dials from a `ws/...` locator).
#[cfg(feature = "transport-link-ws")]
pub mod ws_pipeline;

/// R311xi — Unix-domain-stream backend for the unixsock link. The local-IPC
/// STREAM sibling of [`link_pipeline`] (TCP), NOT a datagram transport: a unix
/// socket is a reliable byte stream (zenoh's `unixsock_stream` link,
/// `is_streamed = true`, MTU 65535), so it REUSES `stream_link`'s StreamEnvelope
/// framing UNCHANGED — `dial_unixsock`/`bind_unixsock`/`accept_unixsock_on` over
/// `tokio::net::UnixStream`/`UnixListener`, `wire_unixsock_stream` splitting the
/// owned halves (`into_split`, like TCP). No new codec, no new dep (tokio's
/// `net` feature carries the unix types on Unix). Gated `transport-link-unixsock`
/// (which forwards `transport-link-tcp` for the shared `stream_link` SSOT); the
/// `session_open` DialedLink::Unixsock integration rides the
/// `transport-link-tcp`-gated session-open module as an additive arm, like
/// serial/tls. A `unixsock-stream/...` locator dials from the locator like
/// every other transport (no cert config needed).
#[cfg(feature = "transport-link-unixsock")]
pub mod unixsock_pipeline;

/// R311xj — AF_VSOCK backend for the vsock link (VM<->host / VM<->VM). The
/// STREAM sibling of [`link_pipeline`] (TCP) / [`unixsock_pipeline`]: vsock is a
/// reliable byte stream (zenoh's vsock link, `is_streamed = true`, MTU
/// `BatchSize::MAX`), so it REUSES `stream_link`'s StreamEnvelope framing
/// UNCHANGED — `dial_vsock`/`bind_vsock`/`accept_vsock_on` over a
/// `tokio_vsock::VsockStream`/`VsockListener`, `wire_vsock_stream` splitting via
/// `tokio::io::split` (the TLS pattern — VsockStream has no owned-half split).
/// No new codec. Gated `transport-link-vsock` (forwards `transport-link-tcp` for
/// the shared `stream_link` SSOT) AND `target_os = "linux"` (AF_VSOCK is
/// Linux-only, via the optional `tokio-vsock` dep — the same platform gate
/// zenoh-link-vsock carries). The `vsock/<CID>:<PORT>` locator PARSE is
/// platform-independent + ungated in `wz-session-core`; only this dial/accept
/// backend is gated. The `session_open` DialedLink::Vsock integration rides the
/// `transport-link-tcp`-gated session-open module additively, like tls/unixsock.
#[cfg(all(feature = "transport-link-vsock", target_os = "linux"))]
pub mod vsock_pipeline;

/// R311y10 — host Unix named-pipe (FIFO) backend. The same-host FIFO sibling of
/// [`unixsock_pipeline`] (AF_UNIX stream): zenoh's `zenoh-link-unixpipe` carries
/// a batch over a PAIR of named FIFOs (uplink + downlink), distinct from the
/// AF_UNIX socket. wz uses tokio's NATIVE FIFO support (`tokio::net::unix::pipe`
/// — `Sender` is `AsyncWrite`, `Receiver` is `AsyncRead`), so a FIFO link reuses
/// the shared `stream_link` StreamEnvelope drivers UNCHANGED (a FIFO is a byte
/// stream), needing only a one-call `libc::mkfifo` — no `unix_named_pipe` crate,
/// no `advisory-lock`, no `AsyncFd` dance. Gated `transport-link-unixpipe`
/// (forwards `transport-link-tcp` for the shared `stream_link` SSOT) AND
/// `target_os = "linux"` (the `read_write` open-rendezvous knob that liquidates
/// the FIFO `ENXIO` open-ordering race is Linux-only in tokio — the same
/// platform-gate shape as vsock). The `unixpipe/...` locator PARSE is
/// platform-independent + ungated in `wz-session-core`; only this dial/accept
/// backend is gated.
#[cfg(all(feature = "transport-link-unixpipe", target_os = "linux"))]
pub mod unixpipe_pipeline;

/// R311xk — TLS-1.3 + ALPN-`hq-29` rustls config builders for the QUIC link.
/// QUIC mandates TLS 1.3, so its rustls config differs from the TLS link's two
/// ways (TLS-1.3-only, ALPN `hq-29`); everything else (PEM loaders, `ring`
/// provider, rustls 0.23 stack) is shared with [`tls_config`]. Gated
/// `transport-link-quic`.
#[cfg(feature = "transport-link-quic")]
pub mod quic_config;

/// transport-shm — the AP POSIX shared-memory provider (memmap2 over /dev/shm):
/// `ShmBackedPayload` (owner alloc/write) + `PosixShmResolver` (the reader-side
/// impl of the no_std `wz_session_core::extshm::ShmResolver` seam). The std mmap
/// half of the scoped same-host SHM transport; the descriptor + 0x2 marker codec
/// live in the no_std core.
#[cfg(feature = "transport-shm")]
pub mod shm_provider;

/// R311xk — host QUIC backend. The STREAM sibling of [`tls_pipeline`]: zenoh
/// carries a batch over ONE bidirectional QUIC stream (uni rejected, bidi=1)
/// with the SAME StreamEnvelope length-prefix as TCP/TLS (`is_streamed = true`,
/// MTU `BatchSize::MAX`), so it REUSES `stream_link`'s drivers UNCHANGED — a
/// `quinn::RecvStream` is `AsyncRead`, a `SendStream` is `AsyncWrite`, and they
/// are ALREADY a split pair (no `into_split`/`tokio::io::split`). The endpoint +
/// connection ride into the read driver as a keep-alive (QUIC's stream
/// references its connection references the endpoint driver). Gated
/// `transport-link-quic` (forwards `transport-link-tcp` for the shared
/// `stream_link` SSOT, pulls `quinn` + the tls rustls cert stack). Cert config
/// is threaded via `DialConfig.quic` (the tls pattern); the `session_open`
/// DialedLink::Quic arm rides the `transport-link-tcp`-gated session-open module
/// additively, like tls.
#[cfg(feature = "transport-link-quic")]
pub mod quic_pipeline;

/// R311y8 — host QUIC unreliable-DATAGRAM backend (RFC9221). The DATAGRAM
/// sibling of [`quic_pipeline`]: zenoh ships `zenoh-link-quic_datagram` beside
/// `zenoh-link-quic`, sharing the TLS config but carrying each batch as ONE
/// QUIC datagram (`send_datagram`/`read_datagram`, `rel=0`) instead of over a
/// bidi stream — the datagram boundary is the framing, so it reuses the UDP
/// read/write driver shape (shared `Connection` handle, one datagram = one
/// frame), NOT the StreamEnvelope drivers. Gated `transport-link-quic-datagram`,
/// which IMPLIES `transport-link-quic` (reuses [`quic_config`] + the quinn/rustls
/// stack); the only new surface is the datagram path + the per-datagram MTU. The
/// `session_open` DialedLink::QuicDatagram arm reuses `DialConfig.quic` (same
/// cert), like tls/quic.
#[cfg(feature = "transport-link-quic-datagram")]
pub mod quic_datagram_pipeline;

/// R311eu — mode-agnostic session-open orchestration over the R311et
/// [`link_pipeline`]. `dial_locator` dispatches an `AnyLocator`'s scheme
/// to a raw transport (R311nv: TCP/UDP/serial); `connect_and_open_session`
/// dials, splits into the pipeline, wires the Initiator FSM, and drives the
/// handshake to Established. Gated on `transport-unicast` too because it
/// drives the `session_fsm_unicast` FSM.
#[cfg(all(feature = "transport-link-tcp", feature = "transport-unicast"))]
pub mod session_open;

/// R311uy — the storage service DRIVER (§5.11 storage, atom 3/4): the AP
/// tokio binding for the runtime-agnostic storage kernel. A
/// [`storage_service::StorageService`] declares a capture [`Subscriber`]
/// + a complete [`Queryable`] on a storage keyexpr and drives the
/// [`wz_session_core::storage_state::StorageState`] gate (Put / Delete
/// capture -> newer-wins; query -> per-key reply). Gated on
/// `storage-backend` (which forwards the kernel + `query-queryable`), so a
/// profile without storage never compiles the driver.
/// R311xt — §5.18 time: the [`FallbackStamp`](timestamp_source::FallbackStamp)
/// timestamp-source seam (`time-timestamp-source`, FOUNDATIONAL) plus the
/// optional [`uhlc::HLC`] source (`time-hlc`, active). Consumed by
/// [`storage_service`] to stamp un-timestamped captured samples — wz's only
/// auto-stamp site today — so the module is gated on `storage-backend`.
#[cfg(feature = "storage-backend")]
pub mod timestamp_source;

#[cfg(feature = "storage-backend")]
pub mod storage_service;

/// Round 311vm — the storage-replication DRIVER, digest publisher half
/// (§5.11 storage, replication 6/N): the tokio binding that periodically
/// publishes this storage's replication
/// [`wz_session_core::storage_replication::Digest`] on
/// `@-digest/<zid>/<config-fp>` so peer replicas can detect divergence. It
/// shares the live [`storage_service::StorageService`] state (the digest
/// reflects the actual stored data), and the spawned publish loop is
/// RAII-bound (dropping the [`storage_replication_service::DigestPublisher`]
/// aborts it). Gated on `storage-replication` (implies storage-backend).
#[cfg(feature = "storage-replication")]
pub mod storage_replication_service;

/// Round 311 A8c-2a — the storage-aligner DRIVER, ANSWER half (§5.11 storage,
/// aligner): the tokio binding that declares a [`Queryable`](session::Queryable)
/// on this replica's aligner keyexpr (`@zid/<zid>/<config-fp>/aligner`) and
/// answers a peer's
/// [`AlignmentQuery`](wz_session_core::storage_aligner::AlignmentQuery) with
/// the entries it needs to converge. The decode / answer / emit core delegates
/// to the no_std kernel
/// ([`StorageState::answer_alignment_query`](wz_session_core::storage_state::StorageState::answer_alignment_query));
/// this module reads the query attachment, locks the shared
/// [`storage_service::StorageService`] state, and emits each response on the
/// reply seam. The queryable is RAII-bound (dropping the
/// [`storage_aligner_service::AlignerService`] undeclares it). Gated on
/// `storage-aligner` (implies storage-replication).
#[cfg(feature = "storage-aligner")]
pub mod storage_aligner_service;

/// R311y62 — the storage MANAGER DRIVER (§5.24): the AP tokio binding that
/// hosts N live [`storage_service::StorageService`]s over a volume registry.
/// A [`storage_manager_service::RuntimeStorageManager`] reuses the kernel
/// [`wz_session_core::storage_manager::StorageManager`] for volume
/// registration + backend creation, then declares one live StorageService per
/// [`StorageConfig`](wz_session_core::storage_config::StorageConfig) and holds
/// it by name — the live-service counterpart of the sync kernel manager (which
/// holds bare backends). Dropping the manager undeclares every hosted storage
/// (each StorageService's RAII Drop). Gated on `storage-mgr-multi-storage-host`
/// (which forwards the kernel manager + pulls `storage-backend` for the
/// service).
#[cfg(feature = "storage-mgr-multi-storage-host")]
pub mod storage_manager_service;

/// R311qa — the multi-peer accept loop: the `routing-router` / `routing-peer`
/// foundation. Binds once and holds N concurrent peer faces (bind -> accept
/// loop -> per-face open + drive), the increment zenoh's role-agnostic
/// `accept_task` provides over the one-shot [`session_open`] accept. No
/// forwarding yet (that is the sibling `routing-routes` atom). Gated on the
/// `routing-accept` feature (which pulls `transport-link-tcp` + `transport-unicast`
/// + `futures-util`) — a selectable atom both role features compose, not an
/// always-on module, so a profile that selects neither role never compiles it
/// (nor pays for `futures-util`).
#[cfg(feature = "routing-accept")]
pub mod accept_loop;

/// R311qc — the data-plane forwarding atom: the [`routing_forward::RoutingForwarder`]
/// that backs the [`accept_loop`]'s `FaceForwarder` seam with the
/// [`wz_session_core::routing::RouteTable`] kernel, turning a held face into a
/// route (a Put on one face forwarded to every other face that declared a
/// matching subscriber). Gated on `routing-routes` (which pulls `routing-accept`
/// + the kernel + the Push / DeclareSubscriber codecs); the hold-only
/// foundation builds without it (it uses `accept_loop::NoOpForwarder`).
#[cfg(feature = "routing-routes")]
pub mod routing_forward;

/// P4 linkstate-peer routing — the driver (step c3) that connects the
/// topology graph (the [`wz_routing_graph`] crate, lifted out of this
/// runtime crate in R311qw) to the accept/peer-loop face lifecycle: a
/// [`FaceForwarder`](accept_loop::FaceForwarder) that connects faces in the
/// graph and ingests inbound `OAM_LINKSTATE` topology. Gated on
/// `routing-peer`.
#[cfg(feature = "routing-peer")]
pub mod linkstate_forward;

/// R311tt — the §5.16 access-control interceptor SEAM: the composable
/// message-admission chain ([`interceptor::InterceptorChain`]) the ACL,
/// downsampling, and low-pass enforcers plug into, plus the ACL enforcer
/// adapter (`interceptor::access_control::AclInterceptor`). The wz mirror of
/// zenoh `net/routing/interceptor/{mod.rs,access_control.rs}`. The seam +
/// adapter reference the codec `NetworkMessage` types, so they live in this
/// runtime crate and consume the pure `wz_access_control` policy engine (zenoh's
/// `authorization.rs`), kept message-type-free in its own crate. The SEAM is
/// gated on `routing-peer` (the forwarder it gates is); each concrete enforcer
/// is an independent §5.16 knob (`access-acl` / `access-downsampling` /
/// `access-quota`) so a routing peer composes exactly the admission filters it
/// needs — none of them is access control disabled.
#[cfg(feature = "routing-peer")]
pub mod interceptor;

/// P4 linkstate-peer routing (step c3c-3 atom2) — the peer interest table
/// [`linkstate_interest::LinkstatepeerInterest`]: which peers are interested in
/// which key expression. ONE generic type the forwarder instantiates per
/// interest plane (subscriptions, queryables). zenoh keeps this OFF the topology
/// `Network` (it hangs on the routing `Resource`), so wz mirrors that separation
/// — the graph is [`wz_routing_graph`], these interest sets are the HAT-analogue
/// state the forwarder owns. Drives the declaration-filtered data route (atom4)
/// / query route by feeding the interested-peer set to `directions_toward`.
/// Gated on `routing-peer`.
#[cfg(feature = "routing-peer")]
pub mod linkstate_interest;

/// P4 linkstate-peer routing (query-routing atom 3) — the pending-query return
/// table [`linkstate_pending::PendingQueries`]: the per-outbound-face `out qid
/// -> (inbound face, inbound rid)` map that routes a routed Query's `Response` /
/// `ResponseFinal` BACK to the querier across the mesh (the reverse of the
/// forward hop, reconstructed from this state, not the topology tree). The wz
/// analogue of zenoh's per-`FaceState` `pending_queries`. Gated on
/// `routing-peer`.
#[cfg(feature = "routing-peer")]
pub mod linkstate_pending;

/// A4b (session-reconnect) — the re-dial + re-handshake supervisor over
/// [`session_open`]: `open_session_with_reconnect` wires the actions
/// bundle over a `SwappableLink`, and `ReconnectingSession::drive` re-runs
/// the open loop + declaration replay whenever the steady-state loop
/// terminates without the caller's stop signal. zenoh-pico
/// `Z_FEATURE_AUTO_RECONNECT` (`_z_client_reopen_task_fn`) parity. Gated
/// like [`session_open`] (it re-runs that module's open loop) plus the
/// `session-reconnect` state tier it drives.
#[cfg(all(
    feature = "session-reconnect",
    feature = "transport-link-tcp",
    feature = "transport-unicast"
))]
pub mod reconnect;

/// The 4-method `LinkDriver` trait. Matches
/// docs/runtime-crate-tokio.md §2.1. Trust-class flavored variants
/// (untrusted / session_arming / established_session) deferred to
/// later rounds; this baseline assumes established_session
/// (the trust class where all four methods are present).
#[allow(async_fn_in_trait)] // R51: simple trait; refine to Send bounds later
pub trait LinkDriver {
    async fn open(&mut self) -> io::Result<()>;
    async fn send(&mut self, frame: &TxFrame<'_>, reliability: Reliability) -> io::Result<()>;
    async fn close(&mut self) -> io::Result<()>;
    async fn poll_event(&mut self) -> LinkEvent;
}

/// Minimal TCP driver. Reads/writes length-prefixed frames on a
/// single TcpStream using the Zenoh streamed-link wire envelope:
/// **2-byte little-endian length** + payload bytes. This matches
/// zenoh-pico's `_z_link_send_t_msg` /
/// `_z_link_recv_t_msg_cap_flow_stream` (`Z_LINK_CAP_FLOW_STREAM`
/// branch) at zenoh-pico/src/transport/common/{tx,rx}.c with
/// `_Z_MSG_LEN_ENC_SIZE = 2` (zenoh-pico/include/zenoh-pico/
/// protocol/definitions/core.h:32), and bounds the per-frame
/// payload to 65535 bytes which is also the upstream
/// `Z_BATCH_UNICAST_SIZE` ceiling.
///
/// R121h: the wire envelope is now expressed by
/// `sources/codecs/stream_envelope.scxml` (SCE codec_kind) and
/// rendered into `wz_codecs::stream_envelope::StreamEnvelope`. The
/// driver invokes the generated encoder on `send` and the generated
/// decoder on `poll_event` so the codec catalog is the single
/// source of truth for the on-wire shape. The 2-byte prefix read
/// at the start of `poll_event` is unavoidable until SCE exposes a
/// codec-level `MIN_FRAME_BYTES` associated constant (the wire
/// shape needs a length to size the second `read_exact`, and the
/// codec's `decode` requires the full frame in the cursor before
/// it can run). The duplication is bounded to a 2-byte `[u8; 2]`
/// length sniff; the structural decode runs through the codec.
#[cfg(feature = "transport-link-tcp")]
pub struct TcpDriver {
    stream: Option<TcpStream>,
    /// R265 — partial-read state machine for the cancel-safe
    /// poll_event implementation. Carries the in-flight length
    /// prefix or payload bytes across `tokio::select!` cancellations
    /// of `poll_event`, so the next iteration resumes from the
    /// last byte offset rather than re-syncing from a mid-frame
    /// socket cursor. See [`ReadState`] for the state graph.
    read_state: ReadState,
}

/// R265 — cancel-safe partial-read state for [`TcpDriver::poll_event`]
/// (the same shape is mirrored on `wz-ap-demo`'s `InboundReadDriver`).
///
/// Background. The `tokio::io::AsyncReadExt::read_exact` future loops
/// internally over `.read()` calls; if its outer future is dropped
/// (e.g. by `tokio::select!` losing the race) any bytes already
/// consumed from the socket are discarded. For a length-prefixed
/// envelope (2 byte length, N byte payload) that means the next
/// poll re-reads from the socket cursor at an offset that no longer
/// aligns with a frame boundary, and the decoder mis-interprets
/// payload bytes as the next frame's length. R264 fixture surfaced
/// this when a sub-second sweep cadence inside `drive_session_until_-
/// terminal` race-cancelled `poll_and_dispatch_one` 10x/s.
///
/// Fix shape. The state machine keeps the partial-read buffers in
/// `&mut self`, and the only `.await` point per state transition is
/// a single `.read()` syscall. `AsyncReadExt::read` is documented as
/// cancel-safe (no bytes consumed if the future is dropped before
/// completion), so dropping `poll_event` mid-state leaves the
/// captured offset / buffer intact for the next invocation.
#[cfg(feature = "transport-link-tcp")]
#[derive(Default)]
pub(crate) enum ReadState {
    /// No partial read in flight. Next `poll_event` enters
    /// `Length` and begins reading the 2-byte prefix.
    #[default]
    Idle,
    /// Length prefix partially read. `prefix[..offset]` holds the
    /// bytes consumed so far; `offset < 2`. Once `offset == 2`,
    /// the prefix is decoded and the state transitions to
    /// `Payload` with a sized buffer.
    Length { prefix: [u8; 2], offset: usize },
    /// Payload partially read into `frame[..offset]`; `frame`
    /// includes the 2-byte length prefix at `frame[..2]` so the
    /// codec decode at frame-complete operates on the wire-shape
    /// bytes verbatim. `offset < frame.len()` while reading;
    /// `offset == frame.len()` means the frame is complete and
    /// the state machine emits a `LinkEvent::Rx` + transitions
    /// back to `Idle` on the next iteration.
    Payload { frame: Vec<u8>, offset: usize },
}

/// R311et — shared cancel-safe framing read used by both [`TcpDriver`]
/// (the unified acceptor/adapter-path driver) and
/// [`link_pipeline::TcpReadDriver`] (the split read half on the production
/// session-open path). Reads one length-prefixed [`StreamEnvelope`] frame
/// from `src`, advancing `read_state` across `tokio::select!` cancellations
/// (each `.await` is a single cancel-safe `.read()` syscall), and returns
/// the codec-decoded payload as [`LinkEvent::Rx`] — or [`LinkEvent::Lost`]
/// on EOF / IO / codec error, resetting `read_state` to `Idle` so a retry
/// path does not inherit a partial buffer.
///
/// Extracted from the pre-R311et `TcpDriver::poll_event` body verbatim so
/// the framing state machine has a single home. `wz-ap-demo`'s duplicated
/// `InboundReadDriver` copy retires when the demo consumes `link_pipeline`
/// (R311ev); the wire shape stays codec-routed (the [`StreamEnvelope`]
/// decode is the single source of truth, not a hand-rolled prefix strip).
#[cfg(feature = "transport-link-tcp")]
pub(crate) async fn poll_framed<S>(read_state: &mut ReadState, src: &mut S) -> LinkEvent
where
    S: tokio::io::AsyncRead + Unpin,
{
    loop {
        match read_state {
            ReadState::Idle => {
                *read_state = ReadState::Length {
                    prefix: [0u8; 2],
                    offset: 0,
                };
            }
            ReadState::Length { prefix, offset } => match src.read(&mut prefix[*offset..]).await {
                Ok(0) => {
                    *read_state = ReadState::Idle;
                    return LinkEvent::Lost {
                        cause: LostCause::PeerClosed,
                    };
                }
                Ok(n) => {
                    *offset += n;
                    if *offset == 2 {
                        let payload_len = u16::from_le_bytes(*prefix) as usize;
                        let mut frame = vec![0u8; 2 + payload_len];
                        frame[..2].copy_from_slice(prefix);
                        *read_state = ReadState::Payload { frame, offset: 2 };
                    }
                }
                Err(_) => {
                    *read_state = ReadState::Idle;
                    return LinkEvent::Lost {
                        cause: LostCause::OsError,
                    };
                }
            },
            ReadState::Payload { frame, offset } => {
                if *offset == frame.len() {
                    // Frame complete. Take the buffer out before decoding
                    // so the state reset is visible if the codec rejects.
                    let bytes = std::mem::take(frame);
                    *read_state = ReadState::Idle;
                    let mut cursor = SceCursor::new(&bytes);
                    return match StreamEnvelope::decode(&mut cursor) {
                        Ok(env) => LinkEvent::Rx(RxFrame::new(env.payload.to_vec())),
                        Err(_) => LinkEvent::Lost {
                            cause: LostCause::PeerClosed,
                        },
                    };
                }
                match src.read(&mut frame[*offset..]).await {
                    Ok(0) => {
                        *read_state = ReadState::Idle;
                        return LinkEvent::Lost {
                            cause: LostCause::PeerClosed,
                        };
                    }
                    Ok(n) => {
                        *offset += n;
                    }
                    Err(_) => {
                        *read_state = ReadState::Idle;
                        return LinkEvent::Lost {
                            cause: LostCause::OsError,
                        };
                    }
                }
            }
        }
    }
}

#[cfg(feature = "transport-link-tcp")]
impl TcpDriver {
    /// Wrap an already-open TcpStream (acceptor side). The
    /// `open()` method is a no-op for this constructor.
    pub fn from_stream(stream: TcpStream) -> Self {
        Self {
            stream: Some(stream),
            read_state: ReadState::Idle,
        }
    }

    /// R311es — dial an outbound TCP connection to `addr` and wrap the
    /// resulting stream (Initiator side). This is the dial half of the
    /// scouting locator seam: a [`wz_session_core::locator::ParsedLocator`]
    /// with `proto = Tcp` carries the numeric `addr` this constructor
    /// connects to, mirroring [`from_stream`] for the acceptor side.
    ///
    /// `open()` is a no-op afterwards because the stream is already
    /// connected — same post-condition as `from_stream`. Connect-timeout
    /// / retry tuning is the caller's concern (compose a
    /// `tokio::time::timeout` around this); the kernel default applies
    /// otherwise, matching `wz-ap-demo`'s `establish_link` (runner.rs).
    ///
    /// R311et — the actual socket dial routes through the single raw-dial
    /// primitive [`link_pipeline::dial_tcp`], so this unified-driver
    /// constructor and the split session-open pipeline
    /// ([`link_pipeline::wire_tcp_stream`]) share one connect path. The
    /// mode-agnostic `dial_locator(AnyLocator)` dispatcher (R311eu)
    /// dispatches a numeric `Proto::Tcp` endpoint to `dial_tcp` and then splits the
    /// stream for the FSM, rather than burying the stream inside this
    /// driver — hence the raw-dial seam lives in `link_pipeline`.
    pub async fn connect(addr: SocketAddr) -> io::Result<Self> {
        Ok(Self::from_stream(link_pipeline::dial_tcp(addr).await?))
    }
}

#[cfg(feature = "transport-link-tcp")]
impl LinkDriver for TcpDriver {
    async fn open(&mut self) -> io::Result<()> {
        // R51 baseline: caller passes an already-open stream via
        // from_stream. Outbound dial flow (TcpStream::connect) lands
        // when the session FSM Initiator path is wired.
        if self.stream.is_some() {
            Ok(())
        } else {
            Err(io::Error::new(
                io::ErrorKind::NotConnected,
                "TcpDriver::open requires from_stream constructor",
            ))
        }
    }

    async fn send(&mut self, frame: &TxFrame<'_>, _reliability: Reliability) -> io::Result<()> {
        let stream = self
            .stream
            .as_mut()
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotConnected, "no stream"))?;
        let payload_len: u16 = frame
            .bytes
            .len()
            .try_into()
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "frame > 65535 bytes"))?;
        // Borrowed zero-copy view over the in-scope frame buffer — the
        // SCE borrowed codec encodes directly from `frame.bytes` with
        // no owned copy (the envelope lives only until `encode_to_vec`).
        let envelope = StreamEnvelope {
            payload_len,
            payload: frame.bytes,
        };
        let wire = envelope.encode_to_vec();
        stream.write_all(&wire).await?;
        stream.flush().await?;
        Ok(())
    }

    async fn close(&mut self) -> io::Result<()> {
        if let Some(mut s) = self.stream.take() {
            s.shutdown().await?;
        }
        Ok(())
    }

    async fn poll_event(&mut self) -> LinkEvent {
        // R311et — the cancel-safe framing state machine lives in the
        // shared [`poll_framed`] free fn so the split read half
        // ([`link_pipeline::TcpReadDriver`]) decodes identical wire
        // bytes. The `stream.is_none()` (closed) guard stays here because
        // it is `TcpDriver`-specific (the split read half always owns its
        // `OwnedReadHalf`).
        match self.stream.as_mut() {
            Some(stream) => poll_framed(&mut self.read_state, stream).await,
            None => LinkEvent::Lost {
                cause: LostCause::PeerClosed,
            },
        }
    }
}

/// UDP datagram driver. R51 baseline assumes one peer; each
/// `send()` writes one datagram, each `poll_event()` receives one
/// datagram. No framing prefix — UDP preserves message boundaries.
/// Honors `Reliability::BestEffort` (the natural UDP semantic) and
/// silently drops the hint on `Reliability::Reliable` (the session
/// FSM's responsibility — UDP cannot enforce reliability at the
/// link layer).
#[cfg(feature = "transport-link-udp")]
pub struct UdpDriver {
    socket: Option<UdpSocket>,
    peer: Option<SocketAddr>,
}

#[cfg(feature = "transport-link-udp")]
impl UdpDriver {
    /// Wrap a bound UdpSocket + the remote peer the driver
    /// `send()` targets. R51 baseline: caller establishes the
    /// (socket, peer) pair externally; future rounds add an
    /// outbound-discovery + scout-driven peer-selection path.
    pub fn from_socket(socket: UdpSocket, peer: SocketAddr) -> Self {
        Self {
            socket: Some(socket),
            peer: Some(peer),
        }
    }

    /// R311es — bind an ephemeral local UDP socket and target `peer`
    /// for unicast `send()` (Initiator side). This is the UDP dial half
    /// of the scouting locator seam: a
    /// [`wz_session_core::locator::ParsedLocator`] with `proto = Udp`
    /// carries the numeric `peer` this constructor targets, mirroring
    /// [`TcpDriver::connect`] for the datagram transport.
    ///
    /// Distinct from [`bind_multicast_v4`], which joins a scouting group;
    /// this dials a single already-discovered unicast peer. The local
    /// bind address family mirrors `peer` so an IPv6 locator binds an
    /// IPv6 socket (a v4-bound socket cannot reach a v6 peer).
    pub async fn connect(peer: SocketAddr) -> io::Result<Self> {
        let bind_addr: SocketAddr = match peer {
            SocketAddr::V4(_) => (std::net::Ipv4Addr::UNSPECIFIED, 0).into(),
            SocketAddr::V6(_) => (std::net::Ipv6Addr::UNSPECIFIED, 0).into(),
        };
        let socket = UdpSocket::bind(bind_addr).await?;
        Ok(Self::from_socket(socket, peer))
    }

    /// R311en — bind a UDP socket on a multicast group and join it,
    /// returning a driver whose `send()` multicasts to the group. This
    /// is the scouting link transport (docs/scouting-fsm.md §1.2): the
    /// default zenoh scout group is `224.0.0.224:7446`
    /// (`Z_CONFIG_MULTICAST_LOCATOR_DEFAULT`).
    ///
    /// The four setup steps must stay consistent, which is why they are
    /// folded into one constructor rather than left to the caller as
    /// `from_socket` does:
    ///   1. SO_REUSEADDR + SO_REUSEPORT before bind — a multicast group
    ///      port is inherently multi-listener: every zenoh peer on the
    ///      host binds the SAME `0.0.0.0:port` to receive the group.
    ///      Without both reuse options the second binder fails with
    ///      `EADDRINUSE`, so co-locating a wz multicast receiver with a
    ///      foreign zenoh-pico peer (the `pico -> wz` dial-in) is
    ///      impossible.
    ///   2. bind `0.0.0.0:port` (INADDR_ANY) — a socket bound to a
    ///      unicast address cannot receive datagrams addressed to the
    ///      group.
    ///   3. `join_multicast_v4(group, INADDR_ANY)` — subscribe on the
    ///      default interface; without the join the kernel drops group
    ///      datagrams even with the matching bind port.
    ///   4. `set_multicast_loop_v4(true)` — let a same-host peer (and
    ///      the loopback smoke test) observe the traffic; off by default
    ///      on some platforms.
    ///
    /// `peer` is set to `group:port` so `LinkDriver::send` writes the
    /// Scout datagram to the group.
    ///
    /// R311no — the reuse options require a pre-bind setsockopt, which
    /// `tokio::net::UdpSocket` does not expose (it only adopts an already
    /// bound std socket), so the socket is built through `socket2`
    /// (Socket -> `std::net::UdpSocket` -> tokio `from_std`). This
    /// matches zenoh-pico, which sets SO_REUSEADDR + SO_REUSEPORT
    /// unconditionally on its multicast listener before binding
    /// `0.0.0.0:port`
    /// (`vendor/zenoh-pico/src/link/transport/udp/udp_multicast_posix.c`
    /// :180 / :185 / :196). The earlier single-receiver scouting design
    /// deliberately avoided socket2; the `pico -> wz` multicast interop
    /// requirement is exactly the multi-listener case that decision
    /// anticipated, so socket2 now enters as a feature-gated production
    /// dep (scouting-active / transport-multicast).
    // Round C — generalised from `scouting-active`-only to also serve the
    // multicast TRANSPORT (`transport-multicast`): the bind + join + loop
    // setup is identical for the scout group and the multicast session
    // group (zenoh shares the `224.0.0.224:7446` locator for both). The
    // caller passes the group, so the same constructor builds the scout
    // driver and the multicast session driver.
    #[cfg(any(feature = "scouting-active", feature = "transport-multicast"))]
    pub async fn bind_multicast_v4(group: std::net::Ipv4Addr, port: u16) -> io::Result<Self> {
        use socket2::{Domain, Protocol, Socket, Type};

        // Step 1: REUSEADDR + REUSEPORT must be set before bind, and
        // tokio's UdpSocket exposes no pre-bind setsockopt hook, so the
        // socket is built through socket2 and adopted by tokio post-bind.
        let raw = Socket::new(Domain::IPV4, Type::DGRAM, Some(Protocol::UDP))?;
        raw.set_reuse_address(true)?;
        raw.set_reuse_port(true)?;
        // tokio requires the std socket to be non-blocking before adoption.
        raw.set_nonblocking(true)?;
        let bind_addr = SocketAddr::from((std::net::Ipv4Addr::UNSPECIFIED, port));
        raw.bind(&bind_addr.into())?;

        // Step 2 done by the bind above; steps 3-4 use tokio's wrappers.
        let socket = UdpSocket::from_std(raw.into())?;
        socket.join_multicast_v4(group, std::net::Ipv4Addr::UNSPECIFIED)?;
        socket.set_multicast_loop_v4(true)?;
        let peer = SocketAddr::from((group, port));
        Ok(Self {
            socket: Some(socket),
            peer: Some(peer),
        })
    }
}

#[cfg(feature = "transport-link-udp")]
impl LinkDriver for UdpDriver {
    async fn open(&mut self) -> io::Result<()> {
        if self.socket.is_some() && self.peer.is_some() {
            Ok(())
        } else {
            Err(io::Error::new(
                io::ErrorKind::NotConnected,
                "UdpDriver::open requires from_socket constructor",
            ))
        }
    }

    async fn send(&mut self, frame: &TxFrame<'_>, _reliability: Reliability) -> io::Result<()> {
        // UDP link layer is best-effort by definition; Reliability
        // hint is the session FSM's concern (it may resend on the
        // RELIABLE channel via a sequence-number window). Here we
        // just write the datagram.
        let socket = self
            .socket
            .as_ref()
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotConnected, "no socket"))?;
        let peer = self
            .peer
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotConnected, "no peer address"))?;
        socket.send_to(frame.bytes, peer).await?;
        Ok(())
    }

    async fn close(&mut self) -> io::Result<()> {
        // UdpSocket has no kernel-level "close" handshake; dropping
        // the socket releases the FD. Set our handle to None so
        // subsequent calls report NotConnected.
        self.socket = None;
        self.peer = None;
        Ok(())
    }

    async fn poll_event(&mut self) -> LinkEvent {
        let socket = match self.socket.as_ref() {
            Some(s) => s,
            None => {
                return LinkEvent::Lost {
                    cause: LostCause::PeerClosed,
                }
            }
        };
        // Single datagram size cap = 65507 bytes (max UDP payload).
        // R51 baseline allocates per-recv; production tuning will
        // use a recycled buffer pool (RFC §5.E lifecycle).
        let mut buf = vec![0u8; 65507];
        match socket.recv_from(&mut buf).await {
            Ok((n, src)) => {
                buf.truncate(n);
                // Carry the datagram source so a multicast consumer can
                // attribute Frame / KeepAlive / Close to a peer by address
                // (harmless for unicast, which ignores it).
                LinkEvent::Rx(RxFrame::with_src(buf, src))
            }
            Err(_) => LinkEvent::Lost {
                cause: LostCause::OsError,
            },
        }
    }
}
