// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! FFI bindings to vendored zenoh-pico (1.9.0+, pin 3b3ab65c).
//!
//! All bindings are auto-generated by `bindgen` from
//! `vendor/zenoh-pico/include/zenoh-pico.h` at build time; the
//! allowlist in `build.rs` keeps the surface bound to symbols Layer
//! 3 wire-interop tests actually consume.
//!
//! Phase 2 walking-skeleton scope (R41): `_z_id_t` + `_z_id_len`.
//! Each subsequent Layer 3 test round (R42+) extends the allowlist
//! to include the `_z_*_encode` / `_z_*_decode` pair the new
//! interop fixture references.
//!
//! Safety:
//!   - All bound functions are `unsafe extern "C" fn`. Callers must
//!     ensure pointer arguments are valid and that bound types are
//!     ABI-equivalent to their C definitions (bindgen takes care of
//!     this on supported platforms; for novel pointer-width or
//!     endianness targets the layout tests below catch divergence).
//!   - This crate does NOT expose a safe Rust wrapper. The intended
//!     consumer is `crates/wz-integration-tests` (R42+) which uses
//!     the raw FFI inside Layer 3 byte-comparison harnesses where
//!     safety is bounded by the test harness scope. Production
//!     consumers must wrap the raw bindings in a safe abstraction
//!     before exposing them in their public API.

// bindgen-generated code carries C-style identifiers that violate
// rust naming conventions; the workspace's `warnings = "deny"` would
// otherwise reject the bindings module wholesale.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
// Clippy on bindgen output: same rationale as wz-codecs — the
// entire crate body is auto-generated FFI, style lints belong on
// bindgen / clang-emit side, not on the consumer.
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
