// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

#![no_std]

//! wz-runtime-lwip — Phase W MCU profile (R311au scope C entry).
//!
//! This crate is the MCU sibling of [`wz-runtime-tokio`] for the §5.P
//! runtime-services-tier contract. R311au lands a deliberately narrow
//! scope: **sync primitive aliases only**. The [`Runtime`] trait impl
//! (`LwipRuntime` + `spawn` + `JoinHandle`) and the lwIP-sys FFI
//! bridge land in subsequent rounds.
//!
//! ## Why this scope (architectural fork acknowledged)
//!
//! The trait's `spawn<F: Future + Send + 'static>` contract does not
//! compose with embassy_executor's static-task model (embassy's
//! `Spawner::spawn` takes a `SpawnToken` generated by the
//! `#[embassy_executor::task]` proc-macro, not a generic Future). The
//! two paths to a working `LwipRuntime` impl are:
//!
//! 1. Self-roll a cooperative task pool using `alloc::boxed::Box<dyn
//!    Future + Send>` + manual polling (~100 lines of careful code;
//!    multi-round project).
//! 2. Wrap embassy_executor with an adapter layer that fan-in/out
//!    static-slot tasks against the generic spawn contract (deep
//!    redesign; static-task lifetime invariants leak through).
//!
//! R311au routes around this decision by landing the **sync primitive
//! half** first. Every consumer that needs `R::Mutex<...>` or
//! `R::RwLock<...>` in generic code now has a real per-profile
//! binding on the MCU side, mirroring the AP-side
//! `wz_runtime_tokio::sync` module landed in R311y. The Runtime impl
//! carries forward as an explicit open question.
//!
//! ## Why not a NOP `impl Runtime` stub
//!
//! The R53/R58/R63 retrospect (see `crates/Cargo.toml` comment on
//! `wz-runtime-lwip` removal) ratified that NOP impls + doc-only
//! "Phase W deferred skeleton" reframes are document-around-the-hack
//! anti-patterns. R311au ships **only real impls**:
//!
//! - [`sync::Mutex`] aliases `critical_section::Mutex<RefCell<T>>` —
//!   a working IRQ-disabling lock primitive that compiles on every
//!   Phase W MCU target and is link-ready against a deploy-provided
//!   critical_section impl.
//! - No `impl Runtime for LwipRuntime` exists in this round. A reader
//!   searching for the trait impl finds an honest absence rather than
//!   a misleading NOP that silently discards spawned futures.
//!
//! ## Layer G.4 cross-compile gate
//!
//! The `scripts/run-ci.sh` Layer G matrix exercises this crate
//! against every Phase W rustup target (thumbv6m / thumbv7m /
//! thumbv7em / thumbv8m.{base,main}{,-hf} / riscv32imac) so the
//! `#![no_std]` sync surface stays mechanically buildable as the
//! Runtime impl decision works itself out.
//!
//! [`wz-runtime-tokio`]: ../wz_runtime_tokio/index.html
//! [`Runtime`]: ../wz_runtime_core/trait.Runtime.html

pub mod sync;
