/* SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial */
/* SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael */
/*
 * Bindgen umbrella header for zenoh-pico-sys.
 *
 * Pulls in the zenoh-pico public surface (`zenoh-pico.h`) PLUS the
 * internal headers that expose the `_z_*` prefixed wire-codec
 * encode/decode functions + wbuf/zbuf primitives that Layer 3
 * byte-compare tests consume. The internal prefix indicates an
 * unstable ABI surface relative to zenoh-pico's public `z_*`
 * functions; this is by design — the watching-zenoh project is a
 * codec-level replacement, so we test against the internal codec
 * boundary, not the public application API.
 *
 * Allowlist policy (build.rs) still applies — this header is the
 * SUPERSET that bindgen can see; the allowlist narrows to exactly
 * the symbols each Layer 3 test round adds.
 */

#ifndef WZ_ZENOH_PICO_SYS_WRAPPER_H
#define WZ_ZENOH_PICO_SYS_WRAPPER_H

#include "zenoh-pico.h"

/* Internal headers for codec-layer byte-compare tests.
 *
 * - protocol/codec/transport.h: _z_*_encode for Init/Open/Close/Join/
 *   KeepAlive/Frame/Fragment + scouting envelope/transport envelope.
 * - protocol/codec/message.c siblings via message.h: _z_*_encode for
 *   Scout/Hello and the inner-MID body codecs (Put/Del/Query/Reply/
 *   Err/Timestamp/Encoding/...).
 * - protocol/iobuf.h: _z_wbuf_t / _z_zbuf_t + _z_wbuf_make /
 *   _z_wbuf_to_zbuf / _z_zbuf_get_rptr — the bytes-extraction path
 *   that lets Layer 3 read what the encoder wrote.
 */
#include "zenoh-pico/protocol/iobuf.h"
#include "zenoh-pico/protocol/codec/transport.h"
#include "zenoh-pico/protocol/codec/message.h"
#include "zenoh-pico/protocol/codec/network.h"
#include "zenoh-pico/protocol/codec/ext.h"
#include "zenoh-pico/protocol/ext.h"

/* Forward declarations for body-codec functions that have C-side
 * implementations in src/protocol/codec/message.c but no header
 * declaration (they are wrapped behind the public
 * `_z_scouting_message_encode` dispatcher in the upstream API).
 *
 * For Layer 3 byte-compare tests we need the body codec's output
 * directly (without the dispatcher's MID byte prefix), so we declare
 * the symbols here. The corresponding object code is already in
 * libzenohpico.a — declaring them here only changes the visibility
 * to bindgen + the rust linker, not the C-side build.
 */
#include "zenoh-pico/protocol/definitions/transport.h"  /* _z_s_msg_scout_t, _z_s_msg_hello_t */
z_result_t _z_scout_encode(_z_wbuf_t *wbf, uint8_t header, const _z_s_msg_scout_t *msg);
z_result_t _z_hello_encode(_z_wbuf_t *wbf, uint8_t header, const _z_s_msg_hello_t *msg);

/* R297 — keyexpr intersection matcher (chunk-level forward scan).
 *
 * `_z_keyexpr_forward_intersects` is the worker that
 * `_z_keyexpr_intersects` (public-ish wrapper in session/keyexpr.c)
 * dispatches into after extracting the string pointer + length from
 * the `_z_keyexpr_t` composite. Exposing the worker directly lets
 * Layer 3 wire-interop fixtures call the matcher with raw `(ptr,
 * len)` slices, side-stepping the `_z_keyexpr_t` / `_z_string_t`
 * construction boilerplate (those structs are not in the existing
 * allowlist).
 *
 * The symbol is generated by macro expansion of the `_ZP_CAT
 * (_z_keyexpr_forward, intersects)` pattern in
 * `keyexpr_match_template.h` (line 472 of the template). The expanded
 * function is `extern` (default C linkage) and lands in
 * libzenohpico.a as `_z_keyexpr_forward_intersects` — declaring it
 * here gives bindgen + the Rust linker visibility without changing
 * the C-side build.
 *
 * `can_have_verbatim` mirrors the upstream parameter; pass `true` to
 * exercise the full verbatim-chunk-aware path (matches what
 * `_z_keyexpr_intersects` does), or `false` to take the fast path
 * when callers guarantee no `@`-prefixed chunks.
 */
#include <stdbool.h>
bool _z_keyexpr_forward_intersects(const char *lbegin, const char *lend, const char *rbegin, const char *rend, bool can_have_verbatim);

/* R299 — keyexpr canonicalization mirror.
 *
 * `_z_keyexpr_canonize(char *start, size_t *len)` mutates `start`
 * in place into its canonical form (collapsing `$*$*` runs, lifting
 * lone `$*` to `*`, dropping `*` / `**` after `**`, validating per-
 * char grammar). The new length is written back through `*len`; the
 * return is `zp_keyexpr_canon_status_t` (0 = SUCCESS, negative =
 * grammar violation, with the variant enumerating which rule was
 * tripped).
 *
 * The symbol is `extern` in libzenohpico.a (declared in
 * `vendor/zenoh-pico/include/zenoh-pico/session/keyexpr.h:69`); the
 * status enum lives in `zenoh-pico/api/constants.h`. Both are
 * already pulled by the umbrella `zenoh-pico.h` so no extra include
 * directive is needed here — the wrapper just keeps the forward
 * decl visible to bindgen at the same site as the R297 intersect
 * worker so the keyexpr-domain FFI surface stays one place.
 */
#include <stddef.h>
#include "zenoh-pico/session/keyexpr.h"

#endif /* WZ_ZENOH_PICO_SYS_WRAPPER_H */
