// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael
//
//! R311y628 (§1.1g) — THE DRIVING ORACLE, first increment: wz and the REAL
//! `libzenohpico.so` are handed the SAME generated bytes and their ACCEPT /
//! REJECT verdicts are compared.
//!
//! ## Why this exists, and why it is a different kind of test from every other
//!
//! wz's charter is "specification source + differential oracle". Until this
//! file, the oracle half was OBSERVE-ONLY: wz read traffic that two cooperating
//! stock nodes happened to produce, and every defect the analyzer rounds found
//! had to be reached by a fixture someone imagined first. The register carries
//! that limitation as §1.4a — "a fixture can make a defect unreachable" — with
//! SEVEN recorded instances, one of them added in the round before this one. A
//! hand-authored corpus covers the state space someone thought of, and the
//! recurrence is structural rather than unlucky.
//!
//! A generator is the structural answer. The bytes below are not a corpus
//! someone believed to be interesting; they are produced by walking the wire
//! vocabulary and mutating it, and the verdict is not this workspace's opinion
//! — it is whether UPSTREAM's compiled decoder agrees.
//!
//! ## The anchor rule, unchanged
//!
//! wz is never its own oracle. Nothing here asserts that wz is right; it asserts
//! that wz and pico AGREE. A disagreement is one of three things — a wz defect,
//! a pico defect, or a wire spec that does not decide the case — and only the
//! third is invisible to both implementations' own test suites, which is the one
//! a specification source exists to find.
//!
//! ## Why ACCEPT/REJECT and not field-by-field
//!
//! Deliberate, and it is what keeps the ABI surface small enough to be honest.
//! Comparing decoded FIELDS would mean reconstructing `_z_transport_message_t`'s
//! layout in Rust — a union of per-MID bodies that changes with pico's own
//! configuration — and a layout error would produce differences that look like
//! protocol findings. The result code needs none of that: the message slot is
//! opaque and over-sized, written only by pico, read only by `_z_t_msg_clear`.
//!
//! The verdict is also the property that matters most. Two implementations that
//! disagree about WHETHER a byte string is a valid message disagree about the
//! protocol's boundary, which is where interop breaks and where a spec is
//! ambiguous. Field-level comparison is a later increment with a bigger ABI
//! bill.
//!
//! ## Why `#[ignore]`
//!
//! Same contract as `pico_pure_function_oracle`: the oracle is a CMake build
//! product, its absence is a hard FAIL rather than a skip, and Layer E is the
//! lane that provisions it. A comparison with nothing to compare against must
//! not report green.

use std::path::PathBuf;

use libloading::{Library, Symbol};
use wz_integration_tests::common::zenoh_pico_shared_library;

/// An 8-byte-aligned, over-sized slot for a pico struct this file never reads.
///
/// The same device `pico_pure_function_oracle` uses and for the same reason:
/// these structs hold POINTERS, so an unaligned buffer is undefined behaviour.
/// OVER-sized on purpose — pico writes `sizeof(T)` bytes and the excess is
/// untouched, so the slot needs a lower bound rather than the exact figure, and
/// a lower bound is a claim that cannot rot when pico's configuration changes.
#[repr(C, align(8))]
struct Slot<const N: usize>([u8; N]);

impl<const N: usize> Slot<N> {
    fn zeroed() -> Self {
        Self([0u8; N])
    }
    fn as_mut_ptr(&mut self) -> *mut u8 {
        self.0.as_mut_ptr()
    }
}

/// Far larger than either struct this file passes to pico.
///
/// `_z_transport_message_t` is a header byte, an ext vector and a union of the
/// per-MID bodies; `_z_zbuf_t` is an iosli plus a refcounted slice. Both are
/// well under a kilobyte in every configuration pico ships. The cost of being
/// generous is one page of stack.
const SLOT: usize = 4096;

/// `_z_iosli_t`, which is the FIRST member of `_z_zbuf_t`
/// (`protocol/iobuf.h:111-114`), so its fields sit at offset 0 of the zbuf.
///
/// This is the ONLY pico layout this file reproduces, and it is the stable part:
/// three `size_t`, a pointer, a `bool`
/// (`protocol/iobuf.h:35-41`). The refcounted `_slice` that follows it is never
/// touched — `_z_zbuf_make` fills it and `_z_zbuf_clear` frees it.
const IOS_R_POS: usize = 0;
const IOS_W_POS: usize = 8;
const IOS_CAPACITY: usize = 16;
const IOS_BUF: usize = 24;

/// Open a library in its OWN namespace, so wz's `z_*` and pico's `z_*` cannot
/// resolve to whichever was loaded first.
unsafe fn open(path: &PathBuf) -> Library {
    unsafe { Library::new(path) }.unwrap_or_else(|e| panic!("dlopen {}: {e}", path.display()))
}

/// Hand `bytes` to the REAL pico transport decoder and report whether it
/// ACCEPTED them.
///
/// # Safety
///
/// `lib` must be `libzenohpico.so`. The two slots are opaque to this function;
/// only pico writes them, and `_z_t_msg_clear` / `_z_zbuf_clear` free whatever
/// it allocated inside.
unsafe fn pico_accepts(lib: &Library, bytes: &[u8]) -> bool {
    unsafe {
        let zbuf_make: Symbol<unsafe extern "C" fn(*mut u8, usize)> = lib
            .get(b"_z_zbuf_make\0")
            .expect("_z_zbuf_make is exported");
        let zbuf_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_zbuf_clear\0")
            .expect("_z_zbuf_clear is exported");
        let decode: Symbol<unsafe extern "C" fn(*mut u8, *mut u8) -> i8> = lib
            .get(b"_z_transport_message_decode\0")
            .expect("_z_transport_message_decode is exported");
        let msg_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_t_msg_clear\0")
            .expect("_z_t_msg_clear is exported");

        // `_z_zbuf_make` returns by value; the sret pointer is the first
        // argument under the SysV ABI for a struct this size.
        let mut zbuf = Slot::<SLOT>::zeroed();
        zbuf_make(zbuf.as_mut_ptr(), bytes.len().max(1));

        // Fill the buffer through the iosli prefix: copy the bytes into the
        // allocation pico just made, then declare them written.
        let base = zbuf.as_mut_ptr();
        let buf = base.add(IOS_BUF).cast::<*mut u8>().read();
        let capacity = base.add(IOS_CAPACITY).cast::<usize>().read();
        assert!(
            !buf.is_null() && capacity >= bytes.len(),
            "pico gave a {capacity}-byte buffer for {} bytes",
            bytes.len()
        );
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, bytes.len());
        base.add(IOS_R_POS).cast::<usize>().write(0);
        base.add(IOS_W_POS).cast::<usize>().write(bytes.len());

        let mut msg = Slot::<SLOT>::zeroed();
        let rc = decode(msg.as_mut_ptr(), base);
        msg_clear(msg.as_mut_ptr());
        zbuf_clear(base);
        rc == 0
    }
}

/// R311y634 (§14.11) — how many bytes pico CONSUMED for the message at the
/// front of `bytes`, when it accepted one.
///
/// The read position pico leaves behind IS the message boundary — it is what
/// its own multicast receive path advances by before decoding the next message
/// out of the same datagram (`vendor/zenoh-pico/src/transport/multicast/rx.c:99`).
/// So this is the one number a batch walk depends on, and until now no oracle
/// compared it: two decoders can agree that a string is a valid message and
/// still disagree about where it ENDS, and that disagreement is invisible until
/// something is batched behind it.
///
/// # Safety
///
/// As [`pico_accepts`]: `lib` must be `libzenohpico.so`, and the slots are
/// opaque here.
unsafe fn pico_consumed(lib: &Library, bytes: &[u8]) -> Option<usize> {
    unsafe {
        let zbuf_make: Symbol<unsafe extern "C" fn(*mut u8, usize)> = lib
            .get(b"_z_zbuf_make\0")
            .expect("_z_zbuf_make is exported");
        let zbuf_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_zbuf_clear\0")
            .expect("_z_zbuf_clear is exported");
        let decode: Symbol<unsafe extern "C" fn(*mut u8, *mut u8) -> i8> = lib
            .get(b"_z_transport_message_decode\0")
            .expect("_z_transport_message_decode is exported");
        let msg_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_t_msg_clear\0")
            .expect("_z_t_msg_clear is exported");

        let mut zbuf = Slot::<SLOT>::zeroed();
        zbuf_make(zbuf.as_mut_ptr(), bytes.len().max(1));
        let base = zbuf.as_mut_ptr();
        let buf = base.add(IOS_BUF).cast::<*mut u8>().read();
        let capacity = base.add(IOS_CAPACITY).cast::<usize>().read();
        assert!(
            !buf.is_null() && capacity >= bytes.len(),
            "pico gave a {capacity}-byte buffer for {} bytes",
            bytes.len()
        );
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, bytes.len());
        base.add(IOS_R_POS).cast::<usize>().write(0);
        base.add(IOS_W_POS).cast::<usize>().write(bytes.len());

        let mut msg = Slot::<SLOT>::zeroed();
        let rc = decode(msg.as_mut_ptr(), base);
        let consumed = base.add(IOS_R_POS).cast::<usize>().read();
        msg_clear(msg.as_mut_ptr());
        zbuf_clear(base);
        if rc == 0 {
            Some(consumed)
        } else {
            None
        }
    }
}

/// What wz made of the same bytes — FOUR answers, not two.
///
/// R311y628 — the first cut of this file compared `parse_inbound(..).is_ok()`
/// against pico's result code and reported hundreds of disagreements, ALL of
/// them the same thing: wz answers `InboundFrame::Unknown { mid }` for a MID it
/// cannot name, which is an `Ok` in the `Result` sense and is NOT the claim
/// "this is a valid transport message". pico is a PARTICIPANT and rejects an
/// unknown MID; wz is an OBSERVER and names its own reach limit instead. Two
/// different contracts, and lumping them made the oracle report a design
/// decision as a protocol finding.
///
/// R311y630 — the SAME shape a second time, and this time the resolution was a
/// missing implementation rather than a missing distinction. Eighteen of the
/// twenty-seven pinned divergences were chains carrying an extension with the
/// MANDATORY bit set and an identity the message's extension space does not
/// define; both upstreams refuse the whole message on that
/// (`zenoh-codec-1.5.0/src/common/extension.rs:33-36`, pico
/// `_z_msg_ext_unknown_error`) and wz had no such rule anywhere. It has one now
/// ([`wz_session_core::ext_admit`]), and a decode wz can read but a participant
/// must refuse is its own answer here rather than being folded into either
/// neighbour: folding it into `Named` reports agreement wz has not earned, and
/// folding it into `Refused` erases the fact that the analyzer CAN read the
/// frame and say what is wrong with it.
///
/// The comparison that means something is ADMISSIBLE against ACCEPTED.
/// `Unnamed` is reported separately, because it is a census of this build's
/// reach rather than a disagreement about the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WzVerdict {
    /// wz decoded it as a specific transport message AND a participant may act
    /// on it.
    Named,
    /// wz decoded it as a specific transport message and a conforming
    /// PARTICIPANT must refuse it — the chain carries a mandatory extension
    /// this message's space does not define.
    Inadmissible,
    /// wz read a message and could not name its MID.
    Unnamed,
    /// wz refused the bytes.
    Refused,
}

fn wz_verdict(bytes: &[u8]) -> WzVerdict {
    use wz_session_core::ext_admit::ExtAdmission;
    use wz_session_core::inbound::{parse_inbound, InboundFrame};
    match parse_inbound(bytes) {
        Ok(InboundFrame::Unknown { .. }) => WzVerdict::Unnamed,
        Ok(frame) => match frame.ext_admission() {
            ExtAdmission::UnknownMandatory { .. } => WzVerdict::Inadmissible,
            // `Unjudged` cannot occur on a named frame — every variant
            // `parse_inbound` produces other than `Unknown` has an extension
            // space — and treating it as admissible here would be the exact
            // reach-limit-as-agreement error the enum above exists to prevent.
            ExtAdmission::Admissible | ExtAdmission::Unjudged => WzVerdict::Named,
        },
        Err(_) => WzVerdict::Refused,
    }
}

/// The generated corpus: every transport MID, at every flag combination its
/// header byte can carry, over a small ladder of body lengths.
///
/// NOT a list of interesting cases. The point of a driving oracle is that the
/// input space is walked rather than imagined — this is the whole 8-bit header
/// space against a body ladder, which is 256 x |ladder| strings and includes
/// every reserved-flag and unknown-MID combination without anyone having
/// thought of them.
///
/// The bodies are pseudo-random rather than zeroes for the reason R311y610
/// measured on a different fixture: low-entropy bodies make length prefixes and
/// VLE reads collapse to small values, so a corpus of zeroes never reaches the
/// arms that read a large field.
fn corpus() -> Vec<Vec<u8>> {
    let mut out = Vec::new();
    for header in 0u16..=0xFF {
        for body_len in [0usize, 1, 2, 4, 9, 32] {
            let mut wire = vec![header as u8];
            let mut x = 0x2545_F491u32.wrapping_add(header as u32);
            for _ in 0..body_len {
                x = x.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                wire.push((x >> 16) as u8);
            }
            out.push(wire);
        }
    }
    out
}

/// A minimal WELL-FORMED body for each transport MID, so a generated extension
/// chain is actually reached instead of being shadowed by a body both decoders
/// already refuse.
///
/// Hand-laid from the wire spec rather than produced by wz's own encoders, and
/// that is the anchor rule rather than fastidiousness: an input this workspace
/// generated from its own encoder is an input it has already agreed with, and a
/// differential fed such inputs goes quiet exactly where wz is wrong. These six
/// are short enough to read against `zenoh-protocol-1.5.0/src/transport/*.rs`
/// directly.
fn minimal_body(mid: u8) -> Option<Vec<u8>> {
    use wz_session_core::wire_const as w;
    Some(match mid {
        // version, cbyte (whatami=peer, zid_len-1 = 0), the 1-byte zid. No S, no
        // A, so no resolution pair and no cookie.
        w::T_MID_INIT => vec![0x09, 0x01, 0xAA],
        // VLE lease, VLE initial_sn, then the cookie slice the A-clear form
        // carries (length-prefixed, one byte).
        w::T_MID_OPEN => vec![0x0A, 0x01, 0x01, 0xBB],
        // reason.
        w::T_MID_CLOSE => vec![0x00],
        // empty.
        w::T_MID_KEEP_ALIVE => vec![],
        // VLE sn. FRAME's payload is the tail, so nothing more is required.
        w::T_MID_FRAME | w::T_MID_FRAGMENT => vec![0x01],
        _ => return None,
    })
}

/// R311y630 (§14.9) — THE SECOND GENERATOR: chains built from the extension
/// vocabulary the wire spec actually DEFINES, one message at a time.
///
/// ## Why the blind sweep above is not enough, measured rather than assumed
///
/// The 8-bit header walk produces extension chains out of pseudo-random bytes,
/// and over 1536 strings it produced TEN distinct mandatory extension
/// identities — every one of them a value neither implementation defines. So
/// the whole POSITIVE half of the admission rule (`frame::ext::QoS` at `0x31`,
/// JOIN's `0x51` / `0x52`) was never once driven through both decoders. A
/// generator that walks a space uniformly is exactly the generator that misses
/// the handful of points the protocol gives meaning to: they are seven bytes in
/// a space of 128.
///
/// ## What this adds
///
/// For each transport MID, a well-formed body followed by ONE extension, over
/// the identities zenoh declares for that message plus two controls. Every ext
/// body matches its own encoding, so the chain terminates cleanly and the only
/// thing either decoder can disagree about is whether that EXTENSION is
/// acceptable there — which is the question, isolated.
fn vocabulary_corpus() -> Vec<Vec<u8>> {
    // (identity, what its encoding requires after the header byte). Identities
    // are `id | M | enc`, read off `zenoh-protocol-1.5.0/src/transport/*.rs`.
    const UNIT: &[u8] = &[];
    const Z64: &[u8] = &[0x2A];
    const ZBUF: &[u8] = &[0x02, 0xC1, 0xC2];
    /// `frame::ext::QoS` / `fragment::ext::QoS` — `zextz64!(0x1, true)`, so
    /// `id 1 | FLAG_M | ENC_Z64`. Named because it is the case this generator
    /// exists to reach.
    const FRAME_QOS: u8 = 0x31;

    /// One extension: its identity (`id | M | enc`) and the body its encoding
    /// requires after the header byte.
    type Ext = (u8, &'static [u8]);
    /// One transport message's declared extension space.
    type Space = (u8, &'static [Ext]);

    // Per-MID: every identity that message's own `mod ext` declares, in id
    // order, plus the two controls at the end.
    use wz_session_core::wire_const as w;
    let spaces: &[Space] = &[
        (
            w::T_MID_INIT, // INIT: QoS unit, QoSLink z64, Shm zbuf, Auth zbuf, MultiLink
            // zbuf, LowLatency unit, Compression unit, Patch z64 — all
            // declared NON-mandatory.
            &[
                (0x01, UNIT),
                (0x21, Z64),
                (0x42, ZBUF),
                (0x43, ZBUF),
                (0x44, ZBUF),
                (0x05, UNIT),
                (0x06, UNIT),
                (0x27, Z64),
            ],
        ),
        (
            w::T_MID_OPEN, // OPEN: QoS unit, Shm z64, Auth zbuf, MultiLinkSyn zbuf,
            // MultiLinkAck unit, LowLatency unit, Compression unit.
            &[
                (0x01, UNIT),
                (0x22, Z64),
                (0x43, ZBUF),
                (0x44, ZBUF),
                (0x04, UNIT),
                (0x05, UNIT),
                (0x06, UNIT),
            ],
        ),
        // CLOSE and KEEP_ALIVE declare no `mod ext` at all: their spaces are
        // EMPTY, so the controls below are the whole of what can be sent.
        (w::T_MID_CLOSE, &[]),
        (w::T_MID_KEEP_ALIVE, &[]),
        // FRAME: QoS z64, MANDATORY. The one mandatory extension the data
        // plane defines, and the reason this generator exists.
        (w::T_MID_FRAME, &[(FRAME_QOS, Z64)]),
        // FRAGMENT: the same mandatory QoS, plus First / Drop as non-mandatory
        // units.
        (
            w::T_MID_FRAGMENT,
            &[(FRAME_QOS, Z64), (0x02, UNIT), (0x03, UNIT)],
        ),
    ];

    let mut out = Vec::new();
    for (mid, space) in spaces {
        let Some(body) = minimal_body(*mid) else {
            continue;
        };
        // The controls, on every message: one extension nothing defines with
        // the mandatory marker CLEAR (both sides must skip it) and the same
        // with it SET (both sides must refuse). Without them a message whose
        // space is empty would contribute nothing.
        let controls: [(u8, &[u8]); 2] = [(0x0F, UNIT), (0x1F, UNIT)];
        for (eid, ext_body) in space.iter().chain(controls.iter()) {
            let mut wire = vec![mid | 0x80];
            wire.extend_from_slice(&body);
            // Z clear on the entry: it terminates the chain.
            wire.push(*eid);
            wire.extend_from_slice(ext_body);
            out.push(wire);
        }
    }
    out
}

/// R311y628 (§1.1g) — THE DIVERGENCE LEDGER, and it is a PIN rather than a
/// silencer.
///
/// The first honest run of this oracle found 27 disagreements in 1536 generated
/// strings, and they were ONE family by symptom: every single one had the `Z`
/// bit set, so every one was about where the EXT CHAIN's boundary lies.
///
/// R311y630 TRIAGED them, which is the step the pin existed to make possible,
/// and by mechanism they were TWO families with two different owners:
///
/// - **Eighteen were a wz defect** and are gone from this list. The chain
///   carried an extension with the MANDATORY bit set and an identity the
///   message's space does not define; both upstreams refuse the message on that
///   and wz had no such rule. [`wz_session_core::ext_admit`] is the rule, the
///   participant seam consults it, and the oracle now compares ADMISSIBLE
///   against ACCEPTED.
/// - **Nine were a pico defect** and are the whole of what remains — plus SEVEN
///   MORE the wz defect had been hiding. Every one is `T_MID_CLOSE` with `Z`
///   set. `_z_close_decode` (`src/protocol/codec/transport.c:345-353`) opens
///   with `(void)(header);` and reads only the reason byte — it never looks at
///   the extension chain the header announced. zenoh's own Close codec does
///   (`zenoh-codec-1.5.0/src/transport/close.rs:80-83`,
///   `extension::skip_all(reader, "Close")?`), and wz agrees with zenoh. pico
///   is not being lenient about a chain it read; it is accepting bytes it never
///   read, which is why `close_acceptance_by_pico_does_not_depend_on_the_chain`
///   below can witness the mechanism directly rather than infer it.
///
/// TWO DEFECTS CAN CANCEL INTO APPARENT AGREEMENT, and that is the finding this
/// round would not have made by reading either implementation. Seven CLOSE
/// strings carried a mandatory-unknown extension over a chain that DID
/// terminate: pico accepted them because it never read the chain, wz accepted
/// them because it had no mandatory rule, and the oracle saw two decoders
/// agreeing. Fixing wz's side made pico's side visible — which is the shape to
/// expect whenever a differential is quiet in a region where both sides are
/// weak, and the reason the pin GREW while a defect was being closed.
///
/// Pinned as a SET with the drift check running BOTH WAYS, which is the pattern
/// this workspace ratified for Mnemosyne's orphan ledger: a NEW divergence fails
/// because the boundary moved somewhere nobody looked, and a pinned entry that
/// no longer diverges ALSO fails, because a set that can quietly shrink is a set
/// nobody has to justify shrinking. Neither direction can be absorbed silently.
/// The eighteen left this list by that second rule, deliberately and with a fix
/// under them, rather than by being deleted.
const KNOWN_DIVERGENCES: &[(u8, usize)] = &[
    // T_MID_CLOSE with Z, chain TRUNCATED: pico accepts, wz refuses the bytes.
    (0x83, 1),
    (0x83, 2),
    (0x83, 4),
    (0x83, 9),
    (0x83, 32),
    (0xA3, 1),
    (0xA3, 2),
    (0xC3, 1),
    (0xE3, 1),
    // T_MID_CLOSE with Z, chain TERMINATES but carries a mandatory extension
    // CLOSE's (empty) space does not define: pico accepts, wz reads the frame
    // and rules it inadmissible. R311y630 — these seven were invisible until
    // wz gained the mandatory rule, because until then both sides accepted
    // them for two different wrong reasons.
    (0xA3, 4),
    (0xA3, 9),
    (0xA3, 32),
    (0xE3, 2),
    (0xE3, 4),
    (0xE3, 9),
    (0xE3, 32),
    // T_MID_OAM (0x00), Unit and Z64 encodings: wz names it, pico refuses it.
    //
    // R311y878 — THE TWO UPSTREAMS DISAGREE, and this row records which one wz
    // follows rather than which one is right. zenoh's decoder dispatches
    // `id::OAM` (`zenoh-codec/src/transport/mod.rs:131` ->
    // `TransportBody::OAM`); zenoh-pico DEFINES the same id
    // (`include/zenoh-pico/protocol/definitions/transport.h:32`
    // `_Z_MID_T_OAM 0x00`) and then has no `case` for it in
    // `_z_transport_message_decode` (`src/protocol/codec/transport.c:571`), so
    // it falls to `default:` and returns `_Z_ERR_MESSAGE_TRANSPORT_UNKNOWN`.
    // Read directly in both trees, not inferred: pico's own header names the
    // message its own decoder refuses.
    //
    // wz follows zenoh here because the omission is pico's, and because the
    // cost of the other choice is measured: a MID with no length stops a batch
    // walk dead and drops the messages behind it.
    //
    // Lengths 1 (both) and 2 (0x20) are absent on purpose — they are NOT
    // agreements, they are truncations wz refuses too, so both sides say no.
    // If the corpus ever reaches them this list must grow, and the gate will
    // say so rather than this comment.
    (0x00, 2),
    (0x00, 4),
    (0x00, 9),
    (0x00, 32),
    (0x20, 4),
    (0x20, 9),
    (0x20, 32),
];

/// ANTI-VACUITY, and it comes first because every other assertion in this file
/// is worthless without it: the two decoders must actually RUN and must not
/// answer the same thing for everything.
///
/// A harness that always answered `false` on both sides would report perfect
/// agreement over the whole corpus. The two counts below are what make the
/// agreement a measurement — a corpus that is entirely rejected, or entirely
/// accepted, by both proves nothing about either.
// wz-proves: none -- harness control: it proves the two decoders RUN and that
// the corpus reaches every verdict, which is what keeps the oracle below from
// being vacuous. It adjudicates no atom of its own.
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn both_decoders_run_and_the_corpus_reaches_both_verdicts() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let cases = corpus();
    assert!(
        cases.len() > 1_000,
        "the walk must be a walk: {}",
        cases.len()
    );

    let mut named = 0usize;
    let mut inadmissible = 0usize;
    let mut unnamed = 0usize;
    let mut refused = 0usize;
    let mut pico_yes = 0usize;
    for bytes in &cases {
        match wz_verdict(bytes) {
            WzVerdict::Named => named += 1,
            WzVerdict::Inadmissible => inadmissible += 1,
            WzVerdict::Unnamed => unnamed += 1,
            WzVerdict::Refused => refused += 1,
        }
        if unsafe { pico_accepts(&pico, bytes) } {
            pico_yes += 1;
        }
    }
    // All FOUR of wz's answers must occur, or the classifier is not
    // classifying and the oracle below is comparing against a constant.
    // R311y630 — `inadmissible` joined this conjunction the round the answer
    // was added, and it is the one that keeps the new rule from becoming
    // decorative: a `judge_ext_chain` that returned `Admissible` for
    // everything would leave the oracle green (the eighteen would simply be
    // NEW divergences again) but would fail HERE, naming the cause.
    assert!(
        named > 0 && inadmissible > 0 && unnamed > 0 && refused > 0,
        "wz answered named={named} inadmissible={inadmissible} unnamed={unnamed} \
         refused={refused} over {} cases, which is not a classification",
        cases.len()
    );
    assert!(
        pico_yes > 0 && pico_yes < cases.len(),
        "pico accepted {pico_yes} of {}, which is not a decision",
        cases.len()
    );
    println!(
        "corpus {}: wz named={named} inadmissible={inadmissible} unnamed={unnamed} \
         refused={refused}; pico accepted={pico_yes}",
        cases.len()
    );
}

/// R311y630 (§14.1) — THE MECHANISM WITNESS for the sixteen surviving
/// divergences: pico's verdict on a `T_MID_CLOSE` does not depend on the
/// extension chain at all.
///
/// The triage read `_z_close_decode` and found `(void)(header);` with no
/// `_z_msg_ext_*` call in the body, which is an explanation. This is the
/// measurement of it, and the two are not the same thing — a source reading
/// says what one build of one file does, while this says what the linked
/// library in front of us actually decides. Four chains that a decoder reading
/// them could not possibly rate alike — a well-formed non-mandatory extension,
/// a mandatory extension nothing defines, a chain that claims a successor and
/// has none, and a chain truncated inside a length-prefixed body — all get the
/// same answer after a CLOSE header.
///
/// The control leg is what makes that a measurement rather than a tautology:
/// the SAME four chains after a `T_MID_KEEP_ALIVE` header, which pico DOES
/// read, must NOT all get the same answer. Without it, a harness that always
/// returned `accept` would pass the first leg perfectly.
// wz-proves: codec-close codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn close_acceptance_by_pico_does_not_depend_on_the_chain() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };

    // Four extension chains, deliberately spanning what a reader can tell
    // apart. Each is the ext-chain tail on its own; the caller prepends the
    // transport header and (for CLOSE) the reason byte.
    let chains: [(&str, &[u8]); 4] = [
        // id 0x4, UNIT, not mandatory, terminates the chain.
        ("well-formed non-mandatory", &[0x04]),
        // The same, with the mandatory marker set: a participant must refuse.
        ("mandatory and undefined", &[0x14]),
        // Claims a successor that is not there.
        ("continues past the end", &[0x84]),
        // ZBUF encoding announcing 9 body bytes, with 2 present.
        ("truncated inside a body", &[0x44, 0x09, 0xAA, 0xBB]),
    ];

    let close = |chain: &[u8]| {
        // Z | CLOSE, reason byte, then the chain.
        let mut wire = alloc_wire(0x80 | 0x03, &[0x00]);
        wire.extend_from_slice(chain);
        wire
    };
    let keep_alive = |chain: &[u8]| {
        // Z | KEEP_ALIVE — no body at all, the chain follows the header.
        let mut wire = alloc_wire(0x80 | 0x04, &[]);
        wire.extend_from_slice(chain);
        wire
    };

    let close_verdicts: Vec<(&str, bool)> = chains
        .iter()
        .map(|(name, chain)| (*name, unsafe { pico_accepts(&pico, &close(chain)) }))
        .collect();
    let keep_alive_verdicts: Vec<(&str, bool)> = chains
        .iter()
        .map(|(name, chain)| (*name, unsafe { pico_accepts(&pico, &keep_alive(chain)) }))
        .collect();

    // The control FIRST: if pico cannot be seen distinguishing these chains
    // anywhere, the leg below says nothing about CLOSE.
    assert!(
        keep_alive_verdicts.iter().any(|(_, v)| *v) && keep_alive_verdicts.iter().any(|(_, v)| !*v),
        "pico must be seen READING a chain somewhere or this test proves \
         nothing: KEEP_ALIVE verdicts {keep_alive_verdicts:?}"
    );

    // The finding: after a CLOSE header, every one of them is accepted.
    assert!(
        close_verdicts.iter().all(|(_, v)| *v),
        "pico's CLOSE verdict is supposed to be chain-INDEPENDENT (it never \
         reads the chain); got {close_verdicts:?}"
    );

    // And wz, which does read it, tells them apart — the other half of the
    // disagreement, asserted here so the divergence is not one-sided hearsay.
    let wz: Vec<(&str, WzVerdict)> = chains
        .iter()
        .map(|(name, chain)| (*name, wz_verdict(&close(chain))))
        .collect();
    assert!(
        wz.iter().filter(|(_, v)| *v == WzVerdict::Named).count() == 1,
        "exactly the well-formed chain may be admissible to wz: {wz:?}"
    );
    println!("pico CLOSE {close_verdicts:?}; KEEP_ALIVE {keep_alive_verdicts:?}; wz {wz:?}");
}

/// Header byte + body prefix, as a fresh buffer the caller appends to.
fn alloc_wire(header: u8, body: &[u8]) -> Vec<u8> {
    let mut wire = Vec::with_capacity(1 + body.len() + 8);
    wire.push(header);
    wire.extend_from_slice(body);
    wire
}

/// R311y630 (§14.9) — the three vocabulary cases the two implementations do
/// NOT agree on, each with the reason that makes it a finding rather than a
/// mystery.
///
/// Every one is pico's, and the middle two are the ones this generator was
/// built to reach: they are about the extension the wire spec gives the data
/// plane, and the blind sweep produced ten mandatory identities over 1536
/// strings without once producing this one.
const NAMED_DIVERGENCES: &[(u8, u8, &str)] = &[
    // CLOSE has no extension space, so a mandatory extension on one is
    // undefined by construction and both zenoh and wz refuse the message.
    // pico accepts it for the reason the sixteen sweep divergences are pinned
    // on: `_z_close_decode` never reads the chain at all.
    (
        wz_session_core::wire_const::T_MID_CLOSE,
        0x1F,
        "pico never reads a CLOSE ext chain",
    ),
    // THE FINDING. `frame::ext::QoS` is `zextz64!(0x1, true)` — the ONE
    // mandatory extension the transport data plane defines
    // (`zenoh-protocol-1.5.0/src/transport/frame.rs`, `mod ext`) — and zenoh's
    // own Frame codec READS it (`zenoh-codec-1.5.0/src/transport/frame.rs:102-107`
    // dispatches `ext::QoS::ID` before falling through to `extension::skip`).
    // pico's Frame path is `_z_msg_ext_skip_non_mandatories`
    // (`src/protocol/codec/transport.c:400`), which refuses EVERY mandatory
    // extension without exception, so it refuses the one its peer is entitled
    // to send. It does not fire in practice only because pico never offers QoS
    // at INIT, so zenoh disables the conduit and never emits the extension —
    // an interop gap held shut by a negotiation default rather than by
    // agreement.
    (
        0x05,
        0x31,
        "pico refuses frame::ext::QoS, which zenoh reads",
    ),
    // The same extension on FRAGMENT, refused by the same call
    // (`_z_fragment_decode_ext` knows only First / Drop), and zenoh puts it on
    // every fragment of a non-DEFAULT-priority chain.
    (
        0x06,
        0x31,
        "pico refuses fragment::ext::QoS, which zenoh reads",
    ),
];

fn named_divergence(mid: u8, eid: u8) -> Option<&'static str> {
    NAMED_DIVERGENCES
        .iter()
        .find(|(m, e, _)| *m == mid && *e == eid)
        .map(|(_, _, why)| *why)
}

/// R311y630 (§14.9) — THE VOCABULARY ORACLE, kept separate from the sweep
/// below rather than folded into its corpus.
///
/// Two reasons, and the second is the one that matters. The shallow one: the
/// sweep's pin is keyed by `(header, body length)` and a vocabulary string
/// collides with it — a CLOSE carrying one one-byte extension is `(0x83, 2)`,
/// which is already a pinned sweep case about something else entirely. The
/// deeper one: these are different questions. The sweep asks "is there a
/// boundary disagreement anywhere in the header space", and its answer is a set
/// nobody chose. This asks "do the two implementations agree about the
/// extensions the spec actually NAMES", and every string in it is a point the
/// protocol gives meaning to. Folding them would let a regression in the second
/// hide inside the first's pinned set.
///
/// The expectation is stated per case rather than pinned as a blob, because
/// with a vocabulary this small every case has a REASON, and a reason is what a
/// pin cannot carry.
// wz-proves: codec-init-body codec-parity partial
// wz-proves: codec-open-body codec-parity partial
// wz-proves: codec-keep-alive codec-parity partial
// wz-proves: codec-frame codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn the_two_agree_on_the_extensions_the_spec_names() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let cases = vocabulary_corpus();
    assert!(
        cases.len() >= 25,
        "the vocabulary must be walked, not sampled: {}",
        cases.len()
    );

    let mut disagreements = Vec::new();
    let mut explained: Vec<(u8, u8)> = Vec::new();
    let mut both_accept = 0usize;
    let mut both_refuse = 0usize;
    for bytes in &cases {
        let mid = bytes[0] & 0x1F;
        let mine = wz_verdict(bytes);
        let theirs = unsafe { pico_accepts(&pico, bytes) };
        // The extension header is the byte right after the body: every case in
        // this corpus is header + minimal body + exactly one extension.
        let eid = bytes[1 + minimal_body(mid).expect("a generated MID").len()];
        match (mine, theirs) {
            (WzVerdict::Named, true) => both_accept += 1,
            (WzVerdict::Inadmissible | WzVerdict::Refused, false) => both_refuse += 1,
            _ if named_divergence(mid, eid).is_some() => explained.push((mid, eid)),
            _ => disagreements.push(format!(
                "MID {mid:#04X} ext {eid:#04X}: wz={mine:?} pico={}",
                if theirs { "accept" } else { "reject" }
            )),
        }
    }

    // The pinned three must STILL diverge, the same both-ways rule the sweep's
    // pin follows: an entry that quietly stopped diverging is an entry nobody
    // had to justify removing.
    let healed: Vec<&(u8, u8, &str)> = NAMED_DIVERGENCES
        .iter()
        .filter(|(m, e, _)| !explained.contains(&(*m, *e)))
        .collect();
    assert!(
        healed.is_empty(),
        "{} named divergence(s) no longer diverge and must be removed \
         deliberately: {healed:?}",
        healed.len()
    );

    // ANTI-VACUITY, and it is sharper here than a count: this corpus is built so
    // that BOTH outcomes must occur — the declared extensions are acceptable and
    // the mandatory control is not — so a harness stuck on either answer fails.
    assert!(
        both_accept > 0 && both_refuse > 0,
        "the vocabulary must reach both verdicts: accept={both_accept} \
         refuse={both_refuse} of {}",
        cases.len()
    );

    assert!(
        disagreements.is_empty(),
        "{} disagreement(s) about extensions the wire spec NAMES — each is a \
         defect in one implementation, not an unexplored corner:\n  {}",
        disagreements.len(),
        disagreements.join("\n  ")
    );
    println!(
        "vocabulary {}: both-accept={both_accept} both-refuse={both_refuse}; \
         {} named divergence(s) hold",
        cases.len(),
        NAMED_DIVERGENCES.len()
    );
}

/// R311y630d (§14.2) — THE SAME RECIPE ON THE SCOUTING NAMESPACE, which is
/// where the id `0x01` means something else.
///
/// pico exports `_z_scouting_message_decode` beside the transport one, so the
/// second namespace costs one more symbol and no new machinery. What it buys
/// is the check that MATTERS for `ext_admit`: SCOUT is MID `0x01` and so is
/// INIT, their extension spaces differ (none versus eight), and a judge keyed
/// on a bare `u8` would answer INIT's question for a SCOUT. The
/// `ExtCarrier::Scouting` arm is what stops that, and this is the measurement
/// that it stops it against the real decoder rather than against wz's opinion
/// of itself.
// wz-proves: codec-scout codec-parity partial
// wz-proves: codec-hello codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn the_two_agree_on_the_scouting_namespaces_extensions() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };

    // SCOUT: version, cbyte (`what` in the low 3 bits, I flag CLEAR so no zid
    // follows). HELLO: version, cbyte (whatami + zid_len-1 = 0), the 1-byte
    // zid, L flag clear so no locator list.
    let bodies: [(u8, &[u8]); 2] = [
        (wz_session_core::wire_const::S_MID_SCOUT, &[0x09, 0x01]),
        (
            wz_session_core::wire_const::S_MID_HELLO,
            &[0x09, 0x01, 0xAA],
        ),
    ];
    // The scouting namespace declares NO extensions, so the space is empty and
    // the two controls are the whole vocabulary: a non-mandatory unknown both
    // sides must skip, and a mandatory unknown both sides must refuse.
    let chains: [(&str, u8, bool); 2] = [
        ("non-mandatory unknown", 0x0F, true),
        ("mandatory unknown", 0x1F, false),
    ];

    let mut agreed = 0usize;
    let mut disagreements = Vec::new();
    for (mid, body) in bodies {
        for (name, ext, must_accept) in chains {
            let mut wire = vec![mid | 0x80];
            wire.extend_from_slice(body);
            wire.push(ext);
            let theirs = unsafe { pico_accepts_scouting(&pico, &wire) };
            let mine = wz_scouting_verdict(&wire);
            let mine_accepts = mine == WzVerdict::Named;
            if mine_accepts == theirs && mine_accepts == must_accept {
                agreed += 1;
            } else {
                disagreements.push(format!(
                    "MID {mid:#04X} {name}: wz={mine:?} pico={} (spec says {})",
                    if theirs { "accept" } else { "reject" },
                    if must_accept { "accept" } else { "reject" },
                ));
            }
        }
    }
    assert!(
        disagreements.is_empty(),
        "{} scouting disagreement(s):\n  {}",
        disagreements.len(),
        disagreements.join("\n  ")
    );
    assert_eq!(agreed, 4, "every case must have been decided");

    // THE POINT, asserted directly rather than left implicit in the four
    // above: the SAME chain judged in the TRANSPORT namespace comes out
    // differently, because `0x01` is INIT there. Without this the scouting
    // arm would pass on a judge that ignored the carrier entirely.
    use wz_session_core::ext_admit::{judge_ext_chain, ExtAdmission, ExtCarrier};
    assert_eq!(
        judge_ext_chain(ExtCarrier::Scouting(0x01), [0x27u8]),
        ExtAdmission::Admissible,
        "0x27 is not mandatory, so scouting skips it"
    );
    assert_eq!(
        judge_ext_chain(ExtCarrier::Transport(0x01), [0x27u8]),
        ExtAdmission::Admissible,
        "and INIT knows it as Patch"
    );
    // The discriminating pair: a MANDATORY id that INIT's space would also not
    // define, so both refuse — and a scouting chain can never be admissible on
    // a mandatory entry, whatever the transport table says.
    assert_eq!(
        judge_ext_chain(ExtCarrier::Scouting(0x01), [0x31u8]),
        ExtAdmission::UnknownMandatory { eid: 0x31 },
        "the scouting space is EMPTY, so the data plane's QoS is unknown here"
    );
    assert_eq!(
        judge_ext_chain(ExtCarrier::Transport(0x05), [0x31u8]),
        ExtAdmission::Admissible,
        "while the same identity on a FRAME is the extension the spec defines \
         — one byte, two answers, and the carrier is what tells them apart"
    );
}

/// Hand `bytes` to pico's SCOUTING decoder — the sibling entry point to
/// `_z_transport_message_decode`, with the same slot discipline.
///
/// # Safety
///
/// `lib` must be `libzenohpico.so`; the slots are opaque and freed by pico's
/// own clear functions.
unsafe fn pico_accepts_scouting(lib: &Library, bytes: &[u8]) -> bool {
    unsafe {
        let zbuf_make: Symbol<unsafe extern "C" fn(*mut u8, usize)> = lib
            .get(b"_z_zbuf_make\0")
            .expect("_z_zbuf_make is exported");
        let zbuf_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_zbuf_clear\0")
            .expect("_z_zbuf_clear is exported");
        let decode: Symbol<unsafe extern "C" fn(*mut u8, *mut u8) -> i8> = lib
            .get(b"_z_scouting_message_decode\0")
            .expect("_z_scouting_message_decode is exported");
        let msg_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_s_msg_clear\0")
            .expect("_z_s_msg_clear is exported");

        let mut zbuf = Slot::<SLOT>::zeroed();
        zbuf_make(zbuf.as_mut_ptr(), bytes.len().max(1));
        let base = zbuf.as_mut_ptr();
        let buf = base.add(IOS_BUF).cast::<*mut u8>().read();
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, bytes.len());
        base.add(IOS_R_POS).cast::<usize>().write(0);
        base.add(IOS_W_POS).cast::<usize>().write(bytes.len());

        let mut msg = Slot::<SLOT>::zeroed();
        let rc = decode(msg.as_mut_ptr(), base);
        msg_clear(msg.as_mut_ptr());
        zbuf_clear(base);
        rc == 0
    }
}

/// wz's verdict on a SCOUTING datagram, through the namespace's own entry
/// point and its own admission table.
fn wz_scouting_verdict(bytes: &[u8]) -> WzVerdict {
    use wz_session_core::ext_admit::ExtAdmission;
    use wz_session_core::scouting_message::{parse_scouting, ScoutingFrame};
    match parse_scouting(bytes) {
        Ok(ScoutingFrame::Unknown { .. }) => WzVerdict::Unnamed,
        Ok(frame) => match frame.ext_admission() {
            ExtAdmission::UnknownMandatory { .. } => WzVerdict::Inadmissible,
            ExtAdmission::Admissible | ExtAdmission::Unjudged => WzVerdict::Named,
        },
        Err(_) => WzVerdict::Refused,
    }
}

/// THE ORACLE. The two implementations must agree on WHETHER each generated
/// byte string is a transport message.
///
/// A failure here is not automatically a wz bug. It is a disagreement about the
/// protocol's boundary, and it is exactly the finding neither implementation's
/// own suite can produce: pico's tests encode what pico believes and wz's encode
/// what wz believes, so a case both read differently and neither writes is
/// invisible to both.
///
/// The report names the header byte and the length, because those two are what
/// a person needs to reproduce it by hand.
// The transport MIDs the generated corpus actually drives through both
// decoders. `partial` on every line and deliberately so: this compares the
// ACCEPT/REJECT verdict, not decoded fields, so it adjudicates each codec's
// BOUNDARY and not its contents.
// wz-proves: codec-init-body codec-parity partial
// wz-proves: codec-open-body codec-parity partial
// wz-proves: codec-close codec-parity partial
// wz-proves: codec-keep-alive codec-parity partial
// wz-proves: codec-frame codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn wz_and_pico_agree_on_what_is_a_transport_message() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let mut divergences: Vec<((u8, usize), String)> = Vec::new();

    let mut unnamed_but_accepted = 0usize;
    for bytes in corpus() {
        let mine = wz_verdict(&bytes);
        let theirs = unsafe { pico_accepts(&pico, &bytes) };
        match (mine, theirs) {
            // The comparison that means something. `Inadmissible` sits on the
            // REFUSAL side of it: wz can read the frame, but it has said no
            // conforming participant may act on it, so pico accepting it is a
            // disagreement about the protocol's boundary exactly as a refusal
            // would be.
            (WzVerdict::Named, false)
            | (WzVerdict::Refused, true)
            | (WzVerdict::Inadmissible, true) => divergences.push((
                (bytes[0], bytes.len() - 1),
                format!(
                    "header 0x{:02X}, {} body byte(s): wz={mine:?} pico={}",
                    bytes[0],
                    bytes.len() - 1,
                    if theirs { "accept" } else { "reject" },
                ),
            )),
            // A MID this build cannot name, which pico CAN: a reach gap, not a
            // disagreement about the wire. Counted so it can never be zero by
            // accident and never mistaken for agreement.
            (WzVerdict::Unnamed, true) => unnamed_but_accepted += 1,
            _ => {}
        }
    }

    // BOTH directions of drift. `new` is a boundary that moved somewhere nobody
    // looked; `resolved` is a pinned entry that stopped diverging, which must be
    // taken off the list deliberately rather than left to rot into a claim
    // nobody checks.
    let pinned: std::collections::BTreeSet<(u8, usize)> =
        KNOWN_DIVERGENCES.iter().copied().collect();
    let new: Vec<&String> = divergences
        .iter()
        .filter(|(k, _)| !pinned.contains(k))
        .map(|(_, m)| m)
        .collect();
    let seen: std::collections::BTreeSet<(u8, usize)> =
        divergences.iter().map(|(k, _)| *k).collect();
    let resolved: Vec<&(u8, usize)> = KNOWN_DIVERGENCES
        .iter()
        .filter(|k| !seen.contains(k))
        .collect();

    assert!(
        new.is_empty(),
        "{} NEW disagreement(s) about the protocol's boundary \
         ({unnamed_but_accepted} unnamed-but-valid, reported separately):\n  {}",
        new.len(),
        new.iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );
    assert!(
        resolved.is_empty(),
        "{} pinned divergence(s) no longer diverge and must be removed from \
         KNOWN_DIVERGENCES: {:?}",
        resolved.len(),
        resolved
    );
    println!(
        "{} pinned divergence(s) hold; {unnamed_but_accepted} MID(s) pico names \
         and this build does not",
        KNOWN_DIVERGENCES.len()
    );
}

/// R311y634 (§14.11) — THE BOUNDARY ORACLE: where does the message END?
///
/// # Why this axis was missing
///
/// Every assertion in this file until now asked whether the two decoders AGREE
/// THAT a string is a message. None asked where they think it stops, because
/// nothing in wz walked past the front of a framing unit — so the answer could
/// not matter. R311y631 / y632 / y633 made all three wz paths walk a batch, and
/// a walk is exactly a chain of boundary claims: one wrong length and every
/// message behind it is read out of the middle of something.
///
/// Both reference implementations walk too (zenoh's
/// `while !batch.is_empty()`, pico decoding the residue of its own buffer), so
/// this is not a wz-specific question — it is the one thing two peers must
/// agree on to batch at all.
///
/// The comparison is restricted to strings BOTH accept. A boundary is only
/// meaningful where both read a message: where one refuses, there is no second
/// opinion to have.
// wz-proves: codec-frame codec-parity partial
// wz-proves: codec-close codec-parity partial
// wz-proves: codec-keep-alive codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn the_two_agree_on_where_a_message_ends() {
    use wz_session_core::inbound::{parse_inbound_consuming, InboundFrame};

    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let mut compared = 0usize;
    let mut frame_family = 0usize;
    let mut disagreements: Vec<(Vec<u8>, usize, usize)> = Vec::new();

    for bytes in corpus().into_iter().chain(vocabulary_corpus()) {
        if !matches!(wz_verdict(&bytes), WzVerdict::Named) {
            continue;
        }
        let Some(theirs) = (unsafe { pico_consumed(&pico, &bytes) }) else {
            continue;
        };
        let Ok((frame, ours)) = parse_inbound_consuming(&bytes) else {
            continue;
        };
        compared += 1;

        // THE FRAME FAMILY IS NOT A DISAGREEMENT, and saying so cost a read of
        // pico's own source rather than a guess: `_z_frame_decode` ends with
        // `msg->_payload = zbf` (`vendor/zenoh-pico/src/protocol/codec/transport.c:404`)
        // — it HANDS THE BUFFER OVER instead of consuming it, and the payload is
        // drained by a second stage that walks the network messages inside
        // (`src/transport/multicast/rx.c:225`). So pico's read position after a
        // Frame decode is the START of the payload, not the end of the message.
        //
        // Asserted as an EQUALITY rather than carved out: pico stops exactly
        // where wz's decoded payload begins, which is a stronger statement than
        // "these two are allowed to differ here" and would catch either side
        // moving. It is also the reason a Frame ends a batch on both sides.
        // THE FRAME FAMILY IS TWO RULES, NOT ONE, and that is pico's own
        // asymmetry rather than a wz observation:
        //
        // - `_z_frame_decode` ends with `msg->_payload = zbf`
        //   (`vendor/zenoh-pico/src/protocol/codec/transport.c:404`) — it HANDS
        //   THE BUFFER OVER without consuming it, and a second stage walks the
        //   network messages inside (`src/transport/multicast/rx.c:225`). Its
        //   read position therefore lands on the START of the payload.
        // - `_z_fragment_decode` aliases the payload and then explicitly drains
        //   the buffer, `zbf->_ios._r_pos = zbf->_ios._w_pos` (`transport.c:463`).
        //   Its read position lands on the END.
        //
        // Both are asserted as EQUALITIES rather than carved out: each is a
        // statement about where pico stopped that would fail if either side
        // moved, and together they are why a Frame or a Fragment ends a batch on
        // both implementations.
        let expected = match &frame {
            InboundFrame::Frame { payload, .. } => Some(ours - payload.len()),
            InboundFrame::Fragment { .. } => Some(ours),
            _ => None,
        };
        if let Some(expected) = expected {
            frame_family += 1;
            assert_eq!(
                ours,
                bytes.len(),
                "wz reads a frame to the end of its unit: header {:#04x}",
                bytes[0]
            );
            assert_eq!(
                theirs, expected,
                "pico stopped somewhere this file does not describe: header \
                 {:#04x}, wz {ours}",
                bytes[0]
            );
            continue;
        }

        if ours != theirs {
            disagreements.push((bytes, ours, theirs));
        }
    }

    assert!(
        compared > 100,
        "the boundary oracle must actually compare boundaries: {compared}"
    );
    assert!(
        frame_family > 0,
        "the frame family must be REACHED, or its equality above is a rule \
         nothing drives"
    );
    let sample: Vec<String> = disagreements
        .iter()
        .take(12)
        .map(|(b, ours, theirs)| {
            format!(
                "header {:#04x} len {} -> wz {ours} / pico {theirs}",
                b[0],
                b.len()
            )
        })
        .collect();

    // THE SET, not the count: every survivor must be the SAME known pico
    // defect, spelled out so a NEW kind of boundary disagreement fails here
    // instead of hiding inside a number that still adds up.
    //
    // R311y630 found it on the acceptance axis — `_z_close_decode` opens with
    // `(void)(header);` and reads the reason only, never the extension chain
    // (zenoh skips it, `zenoh-codec-1.5.0/src/transport/close.rs:80-83`). Here
    // it surfaces as a BOUNDARY: pico stops after the reason, so the chain byte
    // it never read is where it would start decoding the next message of a
    // batch. Same defect, second axis, and the second axis is the one that
    // corrupts everything behind it rather than only the message itself.
    for (bytes, ours, theirs) in &disagreements {
        assert_eq!(
            bytes[0] & 0x1f,
            wz_session_core::wire_const::T_MID_CLOSE,
            "a boundary disagreement outside the Close family: header {:#04x}, \
             wz {ours} / pico {theirs}",
            bytes[0]
        );
        assert_ne!(
            bytes[0] & wz_codecs::wire_const::FLAG_T_Z,
            0,
            "a Close with NO chain has nothing to disagree about: header {:#04x}",
            bytes[0]
        );
        assert_eq!(
            *theirs, 2,
            "pico reads the header and the reason and stops: header {:#04x}",
            bytes[0]
        );
        assert!(
            ours > theirs,
            "wz reads the chain pico skipped: header {:#04x}, wz {ours} / pico {theirs}",
            bytes[0]
        );
    }
    assert_eq!(
        disagreements.len(),
        BOUNDARY_DIVERGENCES,
        "compared {compared} message(s), {frame_family} of them frame-family; \
         boundary disagreements: {sample:#?}"
    );
}

/// R311y634 — the pinned count for [`the_two_agree_on_where_a_message_ends`].
///
/// FIVE, every one of them the Close-ignores-its-chain defect R311y630 already
/// found on the acceptance axis — and the loop above pins that SHAPE, so this
/// number is only the population size. The first measurement reported twenty
/// MORE, all of them the frame family, and reading pico's own decoder turned
/// those into the two equalities above rather than into a carve-out.
///
/// If this moves, read the sample the assertion prints: a new kind of
/// disagreement fails the shape loop first and never reaches this line.
const BOUNDARY_DIVERGENCES: usize = 5;

/// R311y635 (§14.11) — one self-delimiting message per MID, built from the
/// hand-laid minimal bodies, for composing into batches.
///
/// FRAME and FRAGMENT are absent by construction: they read to the end of their
/// unit, so a batch can hold one only as its LAST message, and a batch that
/// began with one would be a shape no conforming sender can write.
fn self_delimiting_messages() -> Vec<(&'static str, Vec<u8>)> {
    use wz_session_core::wire_const as w;
    [
        ("InitSyn", w::T_MID_INIT),
        ("OpenSyn", w::T_MID_OPEN),
        ("Close", w::T_MID_CLOSE),
        ("KeepAlive", w::T_MID_KEEP_ALIVE),
    ]
    .into_iter()
    .filter_map(|(name, mid)| minimal_body(mid).map(|body| (name, alloc_wire(mid, &body))))
    .collect()
}

/// The boundary a decoder claims for the message at the front, and whether that
/// message ENDS the unit.
#[derive(Debug, PartialEq, Eq)]
enum Step {
    /// Consumed this many bytes; another message may follow.
    Consumed(usize),
    /// The message reads to the end of its unit, so the walk stops.
    Terminal,
    /// Neither decoder can say where this ends.
    Stop,
}

/// wz's walk over `bytes`, as the sequence of boundary claims it makes.
fn wz_steps(bytes: &[u8]) -> Vec<Step> {
    use wz_session_core::inbound::{parse_inbound_consuming, InboundFrame};
    let mut out = Vec::new();
    let mut pos = 0usize;
    while pos < bytes.len() {
        match parse_inbound_consuming(&bytes[pos..]) {
            Ok((InboundFrame::Frame { .. } | InboundFrame::Fragment { .. }, _)) => {
                out.push(Step::Terminal);
                return out;
            }
            Ok((_, consumed)) if consumed > 0 => {
                out.push(Step::Consumed(consumed));
                pos += consumed;
            }
            _ => {
                out.push(Step::Stop);
                return out;
            }
        }
    }
    out
}

/// pico's walk over the same bytes, driven the way pico drives its own: decode,
/// advance by the read position, decode again out of the residue
/// (`vendor/zenoh-pico/src/transport/multicast/rx.c:68-77` and `:99`).
///
/// # Safety
///
/// As [`pico_consumed`].
unsafe fn pico_steps(lib: &Library, bytes: &[u8]) -> Vec<Step> {
    let mut out = Vec::new();
    let mut pos = 0usize;
    while pos < bytes.len() {
        let rest = &bytes[pos..];
        // A Frame hands its buffer over rather than consuming it, so pico's read
        // position is not a boundary there — it is the payload start, and the
        // payload runs to the end of the unit. The MID is what says so, exactly
        // as it does on the wz side above.
        let mid = rest[0] & 0x1f;
        if mid == wz_session_core::wire_const::T_MID_FRAME
            || mid == wz_session_core::wire_const::T_MID_FRAGMENT
        {
            // Only counted as terminal if pico ACCEPTS it; otherwise it is a stop.
            if unsafe { pico_accepts(lib, rest) } {
                out.push(Step::Terminal);
            } else {
                out.push(Step::Stop);
            }
            return out;
        }
        match unsafe { pico_consumed(lib, rest) } {
            Some(consumed) if consumed > 0 => {
                out.push(Step::Consumed(consumed));
                pos += consumed;
            }
            _ => {
                out.push(Step::Stop);
                return out;
            }
        }
    }
    out
}

/// R311y635 (§14.11) — THE END-TO-END FORM: two decoders walking the SAME
/// multi-message unit must land on the same boundaries, in the same order.
///
/// # Why one message at a time was not enough
///
/// R311y634 compared where each decoder thinks a single message ends. That is
/// the per-step claim; this is the WALK, and a walk can diverge in ways a step
/// cannot: a boundary that is right for message one and wrong for message two
/// puts the two implementations on different messages from there on, with both
/// still reporting success. Batching is the only reason either of them walks
/// (`zenoh-transport-1.5.0/src/common/pipeline.rs:318` keeps a batch open by
/// default), so this is the shape real traffic takes.
///
/// The corpus is every ordered PAIR of self-delimiting messages plus each pair
/// with a data frame appended — the shape a beacon-or-keepalive followed by a
/// publish actually has on the wire.
// wz-proves: codec-init-body codec-parity partial
// wz-proves: codec-open-body codec-parity partial
// wz-proves: codec-close codec-parity partial
// wz-proves: codec-keep-alive codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn the_two_walk_a_batch_to_the_same_boundaries() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let singles = self_delimiting_messages();
    assert!(
        singles.len() >= 4,
        "the batch corpus needs its building blocks: {}",
        singles.len()
    );
    // A minimal data frame: header, VLE sn, and a two-byte tail.
    let frame = alloc_wire(
        wz_session_core::wire_const::T_MID_FRAME,
        &[0x01, 0xAA, 0xBB],
    );

    let mut units: Vec<(String, Vec<u8>)> = Vec::new();
    for (a, first) in &singles {
        for (b, second) in &singles {
            let mut unit = first.clone();
            unit.extend_from_slice(second);
            units.push((format!("[{a}][{b}]"), unit.clone()));
            unit.extend_from_slice(&frame);
            units.push((format!("[{a}][{b}][Frame]"), unit));
        }
    }

    let mut walked_two_or_more = 0usize;
    for (name, unit) in &units {
        let ours = wz_steps(unit);
        let theirs = unsafe { pico_steps(&pico, unit) };
        assert_eq!(
            ours, theirs,
            "{name}: the two walks diverge -- from the first difference on, the \
             implementations are reading different messages out of the same bytes"
        );
        if ours.iter().filter(|s| !matches!(s, Step::Stop)).count() >= 2 {
            walked_two_or_more += 1;
        }
    }

    assert!(
        walked_two_or_more >= units.len() / 2,
        "most units must actually be WALKED past their first message, or this \
         test agrees about nothing: {walked_two_or_more} of {}",
        units.len()
    );
}
