// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael
//
//! R311y628 (§1.1g) — THE DRIVING ORACLE, first increment: wz and the REAL
//! `libzenohpico.so` are handed the SAME generated bytes and their ACCEPT /
//! REJECT verdicts are compared.
//!
//! ## Why this exists, and why it is a different kind of test from every other
//!
//! wz's charter is "specification source + differential oracle". Until this
//! file, the oracle half was OBSERVE-ONLY: wz read traffic that two cooperating
//! stock nodes happened to produce, and every defect the analyzer rounds found
//! had to be reached by a fixture someone imagined first. The register carries
//! that limitation as §1.4a — "a fixture can make a defect unreachable" — with
//! SEVEN recorded instances, one of them added in the round before this one. A
//! hand-authored corpus covers the state space someone thought of, and the
//! recurrence is structural rather than unlucky.
//!
//! A generator is the structural answer. The bytes below are not a corpus
//! someone believed to be interesting; they are produced by walking the wire
//! vocabulary and mutating it, and the verdict is not this workspace's opinion
//! — it is whether UPSTREAM's compiled decoder agrees.
//!
//! ## The anchor rule, unchanged
//!
//! wz is never its own oracle. Nothing here asserts that wz is right; it asserts
//! that wz and pico AGREE. A disagreement is one of three things — a wz defect,
//! a pico defect, or a wire spec that does not decide the case — and only the
//! third is invisible to both implementations' own test suites, which is the one
//! a specification source exists to find.
//!
//! ## Why ACCEPT/REJECT and not field-by-field
//!
//! Deliberate, and it is what keeps the ABI surface small enough to be honest.
//! Comparing decoded FIELDS would mean reconstructing `_z_transport_message_t`'s
//! layout in Rust — a union of per-MID bodies that changes with pico's own
//! configuration — and a layout error would produce differences that look like
//! protocol findings. The result code needs none of that: the message slot is
//! opaque and over-sized, written only by pico, read only by `_z_t_msg_clear`.
//!
//! The verdict is also the property that matters most. Two implementations that
//! disagree about WHETHER a byte string is a valid message disagree about the
//! protocol's boundary, which is where interop breaks and where a spec is
//! ambiguous. Field-level comparison is a later increment with a bigger ABI
//! bill.
//!
//! ## Why `#[ignore]`
//!
//! Same contract as `pico_pure_function_oracle`: the oracle is a CMake build
//! product, its absence is a hard FAIL rather than a skip, and Layer E is the
//! lane that provisions it. A comparison with nothing to compare against must
//! not report green.

use std::path::PathBuf;

use libloading::{Library, Symbol};
use wz_integration_tests::common::zenoh_pico_shared_library;

/// An 8-byte-aligned, over-sized slot for a pico struct this file never reads.
///
/// The same device `pico_pure_function_oracle` uses and for the same reason:
/// these structs hold POINTERS, so an unaligned buffer is undefined behaviour.
/// OVER-sized on purpose — pico writes `sizeof(T)` bytes and the excess is
/// untouched, so the slot needs a lower bound rather than the exact figure, and
/// a lower bound is a claim that cannot rot when pico's configuration changes.
#[repr(C, align(8))]
struct Slot<const N: usize>([u8; N]);

impl<const N: usize> Slot<N> {
    fn zeroed() -> Self {
        Self([0u8; N])
    }
    fn as_mut_ptr(&mut self) -> *mut u8 {
        self.0.as_mut_ptr()
    }
}

/// Far larger than either struct this file passes to pico.
///
/// `_z_transport_message_t` is a header byte, an ext vector and a union of the
/// per-MID bodies; `_z_zbuf_t` is an iosli plus a refcounted slice. Both are
/// well under a kilobyte in every configuration pico ships. The cost of being
/// generous is one page of stack.
const SLOT: usize = 4096;

/// `_z_iosli_t`, which is the FIRST member of `_z_zbuf_t`
/// (`protocol/iobuf.h:111-114`), so its fields sit at offset 0 of the zbuf.
///
/// This is the ONLY pico layout this file reproduces, and it is the stable part:
/// three `size_t`, a pointer, a `bool`
/// (`protocol/iobuf.h:35-41`). The refcounted `_slice` that follows it is never
/// touched — `_z_zbuf_make` fills it and `_z_zbuf_clear` frees it.
const IOS_R_POS: usize = 0;
const IOS_W_POS: usize = 8;
const IOS_CAPACITY: usize = 16;
const IOS_BUF: usize = 24;

/// Open a library in its OWN namespace, so wz's `z_*` and pico's `z_*` cannot
/// resolve to whichever was loaded first.
unsafe fn open(path: &PathBuf) -> Library {
    unsafe { Library::new(path) }.unwrap_or_else(|e| panic!("dlopen {}: {e}", path.display()))
}

/// Hand `bytes` to the REAL pico transport decoder and report whether it
/// ACCEPTED them.
///
/// # Safety
///
/// `lib` must be `libzenohpico.so`. The two slots are opaque to this function;
/// only pico writes them, and `_z_t_msg_clear` / `_z_zbuf_clear` free whatever
/// it allocated inside.
unsafe fn pico_accepts(lib: &Library, bytes: &[u8]) -> bool {
    unsafe {
        let zbuf_make: Symbol<unsafe extern "C" fn(*mut u8, usize)> = lib
            .get(b"_z_zbuf_make\0")
            .expect("_z_zbuf_make is exported");
        let zbuf_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_zbuf_clear\0")
            .expect("_z_zbuf_clear is exported");
        let decode: Symbol<unsafe extern "C" fn(*mut u8, *mut u8) -> i8> = lib
            .get(b"_z_transport_message_decode\0")
            .expect("_z_transport_message_decode is exported");
        let msg_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_t_msg_clear\0")
            .expect("_z_t_msg_clear is exported");

        // `_z_zbuf_make` returns by value; the sret pointer is the first
        // argument under the SysV ABI for a struct this size.
        let mut zbuf = Slot::<SLOT>::zeroed();
        zbuf_make(zbuf.as_mut_ptr(), bytes.len().max(1));

        // Fill the buffer through the iosli prefix: copy the bytes into the
        // allocation pico just made, then declare them written.
        let base = zbuf.as_mut_ptr();
        let buf = base.add(IOS_BUF).cast::<*mut u8>().read();
        let capacity = base.add(IOS_CAPACITY).cast::<usize>().read();
        assert!(
            !buf.is_null() && capacity >= bytes.len(),
            "pico gave a {capacity}-byte buffer for {} bytes",
            bytes.len()
        );
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, bytes.len());
        base.add(IOS_R_POS).cast::<usize>().write(0);
        base.add(IOS_W_POS).cast::<usize>().write(bytes.len());

        let mut msg = Slot::<SLOT>::zeroed();
        let rc = decode(msg.as_mut_ptr(), base);
        msg_clear(msg.as_mut_ptr());
        zbuf_clear(base);
        rc == 0
    }
}

/// What wz made of the same bytes — FOUR answers, not two.
///
/// R311y628 — the first cut of this file compared `parse_inbound(..).is_ok()`
/// against pico's result code and reported hundreds of disagreements, ALL of
/// them the same thing: wz answers `InboundFrame::Unknown { mid }` for a MID it
/// cannot name, which is an `Ok` in the `Result` sense and is NOT the claim
/// "this is a valid transport message". pico is a PARTICIPANT and rejects an
/// unknown MID; wz is an OBSERVER and names its own reach limit instead. Two
/// different contracts, and lumping them made the oracle report a design
/// decision as a protocol finding.
///
/// R311y630 — the SAME shape a second time, and this time the resolution was a
/// missing implementation rather than a missing distinction. Eighteen of the
/// twenty-seven pinned divergences were chains carrying an extension with the
/// MANDATORY bit set and an identity the message's extension space does not
/// define; both upstreams refuse the whole message on that
/// (`zenoh-codec-1.5.0/src/common/extension.rs:33-36`, pico
/// `_z_msg_ext_unknown_error`) and wz had no such rule anywhere. It has one now
/// ([`wz_session_core::ext_admit`]), and a decode wz can read but a participant
/// must refuse is its own answer here rather than being folded into either
/// neighbour: folding it into `Named` reports agreement wz has not earned, and
/// folding it into `Refused` erases the fact that the analyzer CAN read the
/// frame and say what is wrong with it.
///
/// The comparison that means something is ADMISSIBLE against ACCEPTED.
/// `Unnamed` is reported separately, because it is a census of this build's
/// reach rather than a disagreement about the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WzVerdict {
    /// wz decoded it as a specific transport message AND a participant may act
    /// on it.
    Named,
    /// wz decoded it as a specific transport message and a conforming
    /// PARTICIPANT must refuse it — the chain carries a mandatory extension
    /// this message's space does not define.
    Inadmissible,
    /// wz read a message and could not name its MID.
    Unnamed,
    /// wz refused the bytes.
    Refused,
}

fn wz_verdict(bytes: &[u8]) -> WzVerdict {
    use wz_session_core::ext_admit::ExtAdmission;
    use wz_session_core::inbound::{parse_inbound, InboundFrame};
    match parse_inbound(bytes) {
        Ok(InboundFrame::Unknown { .. }) => WzVerdict::Unnamed,
        Ok(frame) => match frame.ext_admission() {
            ExtAdmission::UnknownMandatory { .. } => WzVerdict::Inadmissible,
            // `Unjudged` cannot occur on a named frame — every variant
            // `parse_inbound` produces other than `Unknown` has an extension
            // space — and treating it as admissible here would be the exact
            // reach-limit-as-agreement error the enum above exists to prevent.
            ExtAdmission::Admissible | ExtAdmission::Unjudged => WzVerdict::Named,
        },
        Err(_) => WzVerdict::Refused,
    }
}

/// The generated corpus: every transport MID, at every flag combination its
/// header byte can carry, over a small ladder of body lengths.
///
/// NOT a list of interesting cases. The point of a driving oracle is that the
/// input space is walked rather than imagined — this is the whole 8-bit header
/// space against a body ladder, which is 256 x |ladder| strings and includes
/// every reserved-flag and unknown-MID combination without anyone having
/// thought of them.
///
/// The bodies are pseudo-random rather than zeroes for the reason R311y610
/// measured on a different fixture: low-entropy bodies make length prefixes and
/// VLE reads collapse to small values, so a corpus of zeroes never reaches the
/// arms that read a large field.
fn corpus() -> Vec<Vec<u8>> {
    let mut out = Vec::new();
    for header in 0u16..=0xFF {
        for body_len in [0usize, 1, 2, 4, 9, 32] {
            let mut wire = vec![header as u8];
            let mut x = 0x2545_F491u32.wrapping_add(header as u32);
            for _ in 0..body_len {
                x = x.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                wire.push((x >> 16) as u8);
            }
            out.push(wire);
        }
    }
    out
}

/// R311y628 (§1.1g) — THE DIVERGENCE LEDGER, and it is a PIN rather than a
/// silencer.
///
/// The first honest run of this oracle found 27 disagreements in 1536 generated
/// strings, and they were ONE family by symptom: every single one had the `Z`
/// bit set, so every one was about where the EXT CHAIN's boundary lies.
///
/// R311y630 TRIAGED them, which is the step the pin existed to make possible,
/// and by mechanism they were TWO families with two different owners:
///
/// - **Eighteen were a wz defect** and are gone from this list. The chain
///   carried an extension with the MANDATORY bit set and an identity the
///   message's space does not define; both upstreams refuse the message on that
///   and wz had no such rule. [`wz_session_core::ext_admit`] is the rule, the
///   participant seam consults it, and the oracle now compares ADMISSIBLE
///   against ACCEPTED.
/// - **Nine were a pico defect** and are the whole of what remains — plus SEVEN
///   MORE the wz defect had been hiding. Every one is `T_MID_CLOSE` with `Z`
///   set. `_z_close_decode` (`src/protocol/codec/transport.c:345-353`) opens
///   with `(void)(header);` and reads only the reason byte — it never looks at
///   the extension chain the header announced. zenoh's own Close codec does
///   (`zenoh-codec-1.5.0/src/transport/close.rs:80-83`,
///   `extension::skip_all(reader, "Close")?`), and wz agrees with zenoh. pico
///   is not being lenient about a chain it read; it is accepting bytes it never
///   read, which is why `close_acceptance_by_pico_does_not_depend_on_the_chain`
///   below can witness the mechanism directly rather than infer it.
///
/// TWO DEFECTS CAN CANCEL INTO APPARENT AGREEMENT, and that is the finding this
/// round would not have made by reading either implementation. Seven CLOSE
/// strings carried a mandatory-unknown extension over a chain that DID
/// terminate: pico accepted them because it never read the chain, wz accepted
/// them because it had no mandatory rule, and the oracle saw two decoders
/// agreeing. Fixing wz's side made pico's side visible — which is the shape to
/// expect whenever a differential is quiet in a region where both sides are
/// weak, and the reason the pin GREW while a defect was being closed.
///
/// Pinned as a SET with the drift check running BOTH WAYS, which is the pattern
/// this workspace ratified for Mnemosyne's orphan ledger: a NEW divergence fails
/// because the boundary moved somewhere nobody looked, and a pinned entry that
/// no longer diverges ALSO fails, because a set that can quietly shrink is a set
/// nobody has to justify shrinking. Neither direction can be absorbed silently.
/// The eighteen left this list by that second rule, deliberately and with a fix
/// under them, rather than by being deleted.
const KNOWN_DIVERGENCES: &[(u8, usize)] = &[
    // T_MID_CLOSE with Z, chain TRUNCATED: pico accepts, wz refuses the bytes.
    (0x83, 1),
    (0x83, 2),
    (0x83, 4),
    (0x83, 9),
    (0x83, 32),
    (0xA3, 1),
    (0xA3, 2),
    (0xC3, 1),
    (0xE3, 1),
    // T_MID_CLOSE with Z, chain TERMINATES but carries a mandatory extension
    // CLOSE's (empty) space does not define: pico accepts, wz reads the frame
    // and rules it inadmissible. R311y630 — these seven were invisible until
    // wz gained the mandatory rule, because until then both sides accepted
    // them for two different wrong reasons.
    (0xA3, 4),
    (0xA3, 9),
    (0xA3, 32),
    (0xE3, 2),
    (0xE3, 4),
    (0xE3, 9),
    (0xE3, 32),
];

/// ANTI-VACUITY, and it comes first because every other assertion in this file
/// is worthless without it: the two decoders must actually RUN and must not
/// answer the same thing for everything.
///
/// A harness that always answered `false` on both sides would report perfect
/// agreement over the whole corpus. The two counts below are what make the
/// agreement a measurement — a corpus that is entirely rejected, or entirely
/// accepted, by both proves nothing about either.
// wz-proves: none -- harness control: it proves the two decoders RUN and that
// the corpus reaches every verdict, which is what keeps the oracle below from
// being vacuous. It adjudicates no atom of its own.
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn both_decoders_run_and_the_corpus_reaches_both_verdicts() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let cases = corpus();
    assert!(
        cases.len() > 1_000,
        "the walk must be a walk: {}",
        cases.len()
    );

    let mut named = 0usize;
    let mut inadmissible = 0usize;
    let mut unnamed = 0usize;
    let mut refused = 0usize;
    let mut pico_yes = 0usize;
    for bytes in &cases {
        match wz_verdict(bytes) {
            WzVerdict::Named => named += 1,
            WzVerdict::Inadmissible => inadmissible += 1,
            WzVerdict::Unnamed => unnamed += 1,
            WzVerdict::Refused => refused += 1,
        }
        if unsafe { pico_accepts(&pico, bytes) } {
            pico_yes += 1;
        }
    }
    // All FOUR of wz's answers must occur, or the classifier is not
    // classifying and the oracle below is comparing against a constant.
    // R311y630 — `inadmissible` joined this conjunction the round the answer
    // was added, and it is the one that keeps the new rule from becoming
    // decorative: a `judge_ext_chain` that returned `Admissible` for
    // everything would leave the oracle green (the eighteen would simply be
    // NEW divergences again) but would fail HERE, naming the cause.
    assert!(
        named > 0 && inadmissible > 0 && unnamed > 0 && refused > 0,
        "wz answered named={named} inadmissible={inadmissible} unnamed={unnamed} \
         refused={refused} over {} cases, which is not a classification",
        cases.len()
    );
    assert!(
        pico_yes > 0 && pico_yes < cases.len(),
        "pico accepted {pico_yes} of {}, which is not a decision",
        cases.len()
    );
    println!(
        "corpus {}: wz named={named} inadmissible={inadmissible} unnamed={unnamed} \
         refused={refused}; pico accepted={pico_yes}",
        cases.len()
    );
}

/// R311y630 (§14.1) — THE MECHANISM WITNESS for the sixteen surviving
/// divergences: pico's verdict on a `T_MID_CLOSE` does not depend on the
/// extension chain at all.
///
/// The triage read `_z_close_decode` and found `(void)(header);` with no
/// `_z_msg_ext_*` call in the body, which is an explanation. This is the
/// measurement of it, and the two are not the same thing — a source reading
/// says what one build of one file does, while this says what the linked
/// library in front of us actually decides. Four chains that a decoder reading
/// them could not possibly rate alike — a well-formed non-mandatory extension,
/// a mandatory extension nothing defines, a chain that claims a successor and
/// has none, and a chain truncated inside a length-prefixed body — all get the
/// same answer after a CLOSE header.
///
/// The control leg is what makes that a measurement rather than a tautology:
/// the SAME four chains after a `T_MID_KEEP_ALIVE` header, which pico DOES
/// read, must NOT all get the same answer. Without it, a harness that always
/// returned `accept` would pass the first leg perfectly.
// wz-proves: codec-close codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn close_acceptance_by_pico_does_not_depend_on_the_chain() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };

    // Four extension chains, deliberately spanning what a reader can tell
    // apart. Each is the ext-chain tail on its own; the caller prepends the
    // transport header and (for CLOSE) the reason byte.
    let chains: [(&str, &[u8]); 4] = [
        // id 0x4, UNIT, not mandatory, terminates the chain.
        ("well-formed non-mandatory", &[0x04]),
        // The same, with the mandatory marker set: a participant must refuse.
        ("mandatory and undefined", &[0x14]),
        // Claims a successor that is not there.
        ("continues past the end", &[0x84]),
        // ZBUF encoding announcing 9 body bytes, with 2 present.
        ("truncated inside a body", &[0x44, 0x09, 0xAA, 0xBB]),
    ];

    let close = |chain: &[u8]| {
        // Z | CLOSE, reason byte, then the chain.
        let mut wire = alloc_wire(0x80 | 0x03, &[0x00]);
        wire.extend_from_slice(chain);
        wire
    };
    let keep_alive = |chain: &[u8]| {
        // Z | KEEP_ALIVE — no body at all, the chain follows the header.
        let mut wire = alloc_wire(0x80 | 0x04, &[]);
        wire.extend_from_slice(chain);
        wire
    };

    let close_verdicts: Vec<(&str, bool)> = chains
        .iter()
        .map(|(name, chain)| (*name, unsafe { pico_accepts(&pico, &close(chain)) }))
        .collect();
    let keep_alive_verdicts: Vec<(&str, bool)> = chains
        .iter()
        .map(|(name, chain)| (*name, unsafe { pico_accepts(&pico, &keep_alive(chain)) }))
        .collect();

    // The control FIRST: if pico cannot be seen distinguishing these chains
    // anywhere, the leg below says nothing about CLOSE.
    assert!(
        keep_alive_verdicts.iter().any(|(_, v)| *v) && keep_alive_verdicts.iter().any(|(_, v)| !*v),
        "pico must be seen READING a chain somewhere or this test proves \
         nothing: KEEP_ALIVE verdicts {keep_alive_verdicts:?}"
    );

    // The finding: after a CLOSE header, every one of them is accepted.
    assert!(
        close_verdicts.iter().all(|(_, v)| *v),
        "pico's CLOSE verdict is supposed to be chain-INDEPENDENT (it never \
         reads the chain); got {close_verdicts:?}"
    );

    // And wz, which does read it, tells them apart — the other half of the
    // disagreement, asserted here so the divergence is not one-sided hearsay.
    let wz: Vec<(&str, WzVerdict)> = chains
        .iter()
        .map(|(name, chain)| (*name, wz_verdict(&close(chain))))
        .collect();
    assert!(
        wz.iter().filter(|(_, v)| *v == WzVerdict::Named).count() == 1,
        "exactly the well-formed chain may be admissible to wz: {wz:?}"
    );
    println!("pico CLOSE {close_verdicts:?}; KEEP_ALIVE {keep_alive_verdicts:?}; wz {wz:?}");
}

/// Header byte + body prefix, as a fresh buffer the caller appends to.
fn alloc_wire(header: u8, body: &[u8]) -> Vec<u8> {
    let mut wire = Vec::with_capacity(1 + body.len() + 8);
    wire.push(header);
    wire.extend_from_slice(body);
    wire
}

/// THE ORACLE. The two implementations must agree on WHETHER each generated
/// byte string is a transport message.
///
/// A failure here is not automatically a wz bug. It is a disagreement about the
/// protocol's boundary, and it is exactly the finding neither implementation's
/// own suite can produce: pico's tests encode what pico believes and wz's encode
/// what wz believes, so a case both read differently and neither writes is
/// invisible to both.
///
/// The report names the header byte and the length, because those two are what
/// a person needs to reproduce it by hand.
// The transport MIDs the generated corpus actually drives through both
// decoders. `partial` on every line and deliberately so: this compares the
// ACCEPT/REJECT verdict, not decoded fields, so it adjudicates each codec's
// BOUNDARY and not its contents.
// wz-proves: codec-init-body codec-parity partial
// wz-proves: codec-open-body codec-parity partial
// wz-proves: codec-close codec-parity partial
// wz-proves: codec-keep-alive codec-parity partial
// wz-proves: codec-frame codec-parity partial
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn wz_and_pico_agree_on_what_is_a_transport_message() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let mut divergences: Vec<((u8, usize), String)> = Vec::new();

    let mut unnamed_but_accepted = 0usize;
    for bytes in corpus() {
        let mine = wz_verdict(&bytes);
        let theirs = unsafe { pico_accepts(&pico, &bytes) };
        match (mine, theirs) {
            // The comparison that means something. `Inadmissible` sits on the
            // REFUSAL side of it: wz can read the frame, but it has said no
            // conforming participant may act on it, so pico accepting it is a
            // disagreement about the protocol's boundary exactly as a refusal
            // would be.
            (WzVerdict::Named, false)
            | (WzVerdict::Refused, true)
            | (WzVerdict::Inadmissible, true) => divergences.push((
                (bytes[0], bytes.len() - 1),
                format!(
                    "header 0x{:02X}, {} body byte(s): wz={mine:?} pico={}",
                    bytes[0],
                    bytes.len() - 1,
                    if theirs { "accept" } else { "reject" },
                ),
            )),
            // A MID this build cannot name, which pico CAN: a reach gap, not a
            // disagreement about the wire. Counted so it can never be zero by
            // accident and never mistaken for agreement.
            (WzVerdict::Unnamed, true) => unnamed_but_accepted += 1,
            _ => {}
        }
    }

    // BOTH directions of drift. `new` is a boundary that moved somewhere nobody
    // looked; `resolved` is a pinned entry that stopped diverging, which must be
    // taken off the list deliberately rather than left to rot into a claim
    // nobody checks.
    let pinned: std::collections::BTreeSet<(u8, usize)> =
        KNOWN_DIVERGENCES.iter().copied().collect();
    let new: Vec<&String> = divergences
        .iter()
        .filter(|(k, _)| !pinned.contains(k))
        .map(|(_, m)| m)
        .collect();
    let seen: std::collections::BTreeSet<(u8, usize)> =
        divergences.iter().map(|(k, _)| *k).collect();
    let resolved: Vec<&(u8, usize)> = KNOWN_DIVERGENCES
        .iter()
        .filter(|k| !seen.contains(k))
        .collect();

    assert!(
        new.is_empty(),
        "{} NEW disagreement(s) about the protocol's boundary \
         ({unnamed_but_accepted} unnamed-but-valid, reported separately):\n  {}",
        new.len(),
        new.iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );
    assert!(
        resolved.is_empty(),
        "{} pinned divergence(s) no longer diverge and must be removed from \
         KNOWN_DIVERGENCES: {:?}",
        resolved.len(),
        resolved
    );
    println!(
        "{} pinned divergence(s) hold; {unnamed_but_accepted} MID(s) pico names \
         and this build does not",
        KNOWN_DIVERGENCES.len()
    );
}
