// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael
//
//! R311y628 (§1.1g) — THE DRIVING ORACLE, first increment: wz and the REAL
//! `libzenohpico.so` are handed the SAME generated bytes and their ACCEPT /
//! REJECT verdicts are compared.
//!
//! ## Why this exists, and why it is a different kind of test from every other
//!
//! wz's charter is "specification source + differential oracle". Until this
//! file, the oracle half was OBSERVE-ONLY: wz read traffic that two cooperating
//! stock nodes happened to produce, and every defect the analyzer rounds found
//! had to be reached by a fixture someone imagined first. The register carries
//! that limitation as §1.4a — "a fixture can make a defect unreachable" — with
//! SEVEN recorded instances, one of them added in the round before this one. A
//! hand-authored corpus covers the state space someone thought of, and the
//! recurrence is structural rather than unlucky.
//!
//! A generator is the structural answer. The bytes below are not a corpus
//! someone believed to be interesting; they are produced by walking the wire
//! vocabulary and mutating it, and the verdict is not this workspace's opinion
//! — it is whether UPSTREAM's compiled decoder agrees.
//!
//! ## The anchor rule, unchanged
//!
//! wz is never its own oracle. Nothing here asserts that wz is right; it asserts
//! that wz and pico AGREE. A disagreement is one of three things — a wz defect,
//! a pico defect, or a wire spec that does not decide the case — and only the
//! third is invisible to both implementations' own test suites, which is the one
//! a specification source exists to find.
//!
//! ## Why ACCEPT/REJECT and not field-by-field
//!
//! Deliberate, and it is what keeps the ABI surface small enough to be honest.
//! Comparing decoded FIELDS would mean reconstructing `_z_transport_message_t`'s
//! layout in Rust — a union of per-MID bodies that changes with pico's own
//! configuration — and a layout error would produce differences that look like
//! protocol findings. The result code needs none of that: the message slot is
//! opaque and over-sized, written only by pico, read only by `_z_t_msg_clear`.
//!
//! The verdict is also the property that matters most. Two implementations that
//! disagree about WHETHER a byte string is a valid message disagree about the
//! protocol's boundary, which is where interop breaks and where a spec is
//! ambiguous. Field-level comparison is a later increment with a bigger ABI
//! bill.
//!
//! ## Why `#[ignore]`
//!
//! Same contract as `pico_pure_function_oracle`: the oracle is a CMake build
//! product, its absence is a hard FAIL rather than a skip, and Layer E is the
//! lane that provisions it. A comparison with nothing to compare against must
//! not report green.

use std::path::PathBuf;

use libloading::{Library, Symbol};
use wz_integration_tests::common::zenoh_pico_shared_library;

/// An 8-byte-aligned, over-sized slot for a pico struct this file never reads.
///
/// The same device `pico_pure_function_oracle` uses and for the same reason:
/// these structs hold POINTERS, so an unaligned buffer is undefined behaviour.
/// OVER-sized on purpose — pico writes `sizeof(T)` bytes and the excess is
/// untouched, so the slot needs a lower bound rather than the exact figure, and
/// a lower bound is a claim that cannot rot when pico's configuration changes.
#[repr(C, align(8))]
struct Slot<const N: usize>([u8; N]);

impl<const N: usize> Slot<N> {
    fn zeroed() -> Self {
        Self([0u8; N])
    }
    fn as_mut_ptr(&mut self) -> *mut u8 {
        self.0.as_mut_ptr()
    }
}

/// Far larger than either struct this file passes to pico.
///
/// `_z_transport_message_t` is a header byte, an ext vector and a union of the
/// per-MID bodies; `_z_zbuf_t` is an iosli plus a refcounted slice. Both are
/// well under a kilobyte in every configuration pico ships. The cost of being
/// generous is one page of stack.
const SLOT: usize = 4096;

/// `_z_iosli_t`, which is the FIRST member of `_z_zbuf_t`
/// (`protocol/iobuf.h:111-114`), so its fields sit at offset 0 of the zbuf.
///
/// This is the ONLY pico layout this file reproduces, and it is the stable part:
/// three `size_t`, a pointer, a `bool`
/// (`protocol/iobuf.h:35-41`). The refcounted `_slice` that follows it is never
/// touched — `_z_zbuf_make` fills it and `_z_zbuf_clear` frees it.
const IOS_R_POS: usize = 0;
const IOS_W_POS: usize = 8;
const IOS_CAPACITY: usize = 16;
const IOS_BUF: usize = 24;

/// Open a library in its OWN namespace, so wz's `z_*` and pico's `z_*` cannot
/// resolve to whichever was loaded first.
unsafe fn open(path: &PathBuf) -> Library {
    unsafe { Library::new(path) }.unwrap_or_else(|e| panic!("dlopen {}: {e}", path.display()))
}

/// Hand `bytes` to the REAL pico transport decoder and report whether it
/// ACCEPTED them.
///
/// # Safety
///
/// `lib` must be `libzenohpico.so`. The two slots are opaque to this function;
/// only pico writes them, and `_z_t_msg_clear` / `_z_zbuf_clear` free whatever
/// it allocated inside.
unsafe fn pico_accepts(lib: &Library, bytes: &[u8]) -> bool {
    unsafe {
        let zbuf_make: Symbol<unsafe extern "C" fn(*mut u8, usize)> = lib
            .get(b"_z_zbuf_make\0")
            .expect("_z_zbuf_make is exported");
        let zbuf_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_zbuf_clear\0")
            .expect("_z_zbuf_clear is exported");
        let decode: Symbol<unsafe extern "C" fn(*mut u8, *mut u8) -> i8> = lib
            .get(b"_z_transport_message_decode\0")
            .expect("_z_transport_message_decode is exported");
        let msg_clear: Symbol<unsafe extern "C" fn(*mut u8)> = lib
            .get(b"_z_t_msg_clear\0")
            .expect("_z_t_msg_clear is exported");

        // `_z_zbuf_make` returns by value; the sret pointer is the first
        // argument under the SysV ABI for a struct this size.
        let mut zbuf = Slot::<SLOT>::zeroed();
        zbuf_make(zbuf.as_mut_ptr(), bytes.len().max(1));

        // Fill the buffer through the iosli prefix: copy the bytes into the
        // allocation pico just made, then declare them written.
        let base = zbuf.as_mut_ptr();
        let buf = base.add(IOS_BUF).cast::<*mut u8>().read();
        let capacity = base.add(IOS_CAPACITY).cast::<usize>().read();
        assert!(
            !buf.is_null() && capacity >= bytes.len(),
            "pico gave a {capacity}-byte buffer for {} bytes",
            bytes.len()
        );
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, bytes.len());
        base.add(IOS_R_POS).cast::<usize>().write(0);
        base.add(IOS_W_POS).cast::<usize>().write(bytes.len());

        let mut msg = Slot::<SLOT>::zeroed();
        let rc = decode(msg.as_mut_ptr(), base);
        msg_clear(msg.as_mut_ptr());
        zbuf_clear(base);
        rc == 0
    }
}

/// What wz made of the same bytes — THREE answers, not two.
///
/// R311y628 — the first cut of this file compared `parse_inbound(..).is_ok()`
/// against pico's result code and reported hundreds of disagreements, ALL of
/// them the same thing: wz answers `InboundFrame::Unknown { mid }` for a MID it
/// cannot name, which is an `Ok` in the `Result` sense and is NOT the claim
/// "this is a valid transport message". pico is a PARTICIPANT and rejects an
/// unknown MID; wz is an OBSERVER and names its own reach limit instead. Two
/// different contracts, and lumping them made the oracle report a design
/// decision as a protocol finding.
///
/// The comparison that means something is NAMED against ACCEPTED. `Unnamed` is
/// reported separately, because it is a census of this build's reach rather
/// than a disagreement about the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WzVerdict {
    /// wz decoded it as a specific transport message.
    Named,
    /// wz read a message and could not name its MID.
    Unnamed,
    /// wz refused the bytes.
    Refused,
}

fn wz_verdict(bytes: &[u8]) -> WzVerdict {
    match wz_session_core::inbound::parse_inbound(bytes) {
        Ok(wz_session_core::inbound::InboundFrame::Unknown { .. }) => WzVerdict::Unnamed,
        Ok(_) => WzVerdict::Named,
        Err(_) => WzVerdict::Refused,
    }
}

/// The generated corpus: every transport MID, at every flag combination its
/// header byte can carry, over a small ladder of body lengths.
///
/// NOT a list of interesting cases. The point of a driving oracle is that the
/// input space is walked rather than imagined — this is the whole 8-bit header
/// space against a body ladder, which is 256 x |ladder| strings and includes
/// every reserved-flag and unknown-MID combination without anyone having
/// thought of them.
///
/// The bodies are pseudo-random rather than zeroes for the reason R311y610
/// measured on a different fixture: low-entropy bodies make length prefixes and
/// VLE reads collapse to small values, so a corpus of zeroes never reaches the
/// arms that read a large field.
fn corpus() -> Vec<Vec<u8>> {
    let mut out = Vec::new();
    for header in 0u16..=0xFF {
        for body_len in [0usize, 1, 2, 4, 9, 32] {
            let mut wire = vec![header as u8];
            let mut x = 0x2545_F491u32.wrapping_add(header as u32);
            for _ in 0..body_len {
                x = x.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                wire.push((x >> 16) as u8);
            }
            out.push(wire);
        }
    }
    out
}

/// R311y628 (§1.1g) — THE DIVERGENCE LEDGER, and it is a PIN rather than a
/// silencer.
///
/// The first honest run of this oracle found 27 disagreements in 1536 generated
/// strings, and they are ONE family: every single one has the `Z` bit set, so
/// every one is about where the EXT CHAIN's boundary lies. Two directions, which
/// is what makes it a real finding rather than a contract mismatch —
/// `T_MID_CLOSE` is a message pico accepts and wz refuses, while INIT, OPEN,
/// KEEP_ALIVE, FRAME and FRAGMENT are messages wz names and pico refuses.
///
/// Pinned as a SET with the drift check running BOTH WAYS, which is the pattern
/// this workspace ratified for Mnemosyne's orphan ledger: a NEW divergence fails
/// because the boundary moved somewhere nobody looked, and a pinned entry that
/// no longer diverges ALSO fails, because a set that can quietly shrink is a set
/// nobody has to justify shrinking. Neither direction can be absorbed silently.
///
/// What this is NOT is a verdict on who is right. Deciding that per case is the
/// triage this file makes possible and does not itself perform: each one is a wz
/// defect, a pico defect, or a wire spec that does not decide, and three
/// different remedies follow. Recording the set is what turns "somebody should
/// fuzz this someday" into a bounded list with an owner.
const KNOWN_DIVERGENCES: &[(u8, usize)] = &[
    // T_MID_CLOSE with Z: pico accepts, wz refuses.
    (0x83, 1),
    (0x83, 2),
    (0x83, 4),
    (0x83, 9),
    (0x83, 32),
    (0xA3, 1),
    (0xA3, 2),
    (0xC3, 1),
    (0xE3, 1),
    // T_MID_INIT / OPEN with Z: wz names, pico refuses.
    (0x81, 32),
    (0x82, 32),
    // T_MID_KEEP_ALIVE with Z: wz names, pico refuses.
    (0x84, 4),
    (0x84, 9),
    (0x84, 32),
    (0xE4, 2),
    (0xE4, 4),
    (0xE4, 9),
    (0xE4, 32),
    // T_MID_FRAME with Z: wz names, pico refuses.
    (0xA5, 4),
    (0xA5, 9),
    (0xA5, 32),
    (0xC5, 2),
    (0xC5, 4),
    (0xC5, 9),
    (0xC5, 32),
    // T_MID_FRAGMENT with Z: wz names, pico refuses.
    (0xC6, 9),
    (0xC6, 32),
];

/// ANTI-VACUITY, and it comes first because every other assertion in this file
/// is worthless without it: the two decoders must actually RUN and must not
/// answer the same thing for everything.
///
/// A harness that always answered `false` on both sides would report perfect
/// agreement over the whole corpus. The two counts below are what make the
/// agreement a measurement — a corpus that is entirely rejected, or entirely
/// accepted, by both proves nothing about either.
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn both_decoders_run_and_the_corpus_reaches_both_verdicts() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let cases = corpus();
    assert!(
        cases.len() > 1_000,
        "the walk must be a walk: {}",
        cases.len()
    );

    let mut named = 0usize;
    let mut unnamed = 0usize;
    let mut refused = 0usize;
    let mut pico_yes = 0usize;
    for bytes in &cases {
        match wz_verdict(bytes) {
            WzVerdict::Named => named += 1,
            WzVerdict::Unnamed => unnamed += 1,
            WzVerdict::Refused => refused += 1,
        }
        if unsafe { pico_accepts(&pico, bytes) } {
            pico_yes += 1;
        }
    }
    // All THREE of wz's answers must occur, or the classifier is not
    // classifying and the oracle below is comparing against a constant.
    assert!(
        named > 0 && unnamed > 0 && refused > 0,
        "wz answered named={named} unnamed={unnamed} refused={refused} over {} \
         cases, which is not a classification",
        cases.len()
    );
    assert!(
        pico_yes > 0 && pico_yes < cases.len(),
        "pico accepted {pico_yes} of {}, which is not a decision",
        cases.len()
    );
    println!(
        "corpus {}: wz named={named} unnamed={unnamed} refused={refused}; \
         pico accepted={pico_yes}",
        cases.len()
    );
}

/// THE ORACLE. The two implementations must agree on WHETHER each generated
/// byte string is a transport message.
///
/// A failure here is not automatically a wz bug. It is a disagreement about the
/// protocol's boundary, and it is exactly the finding neither implementation's
/// own suite can produce: pico's tests encode what pico believes and wz's encode
/// what wz believes, so a case both read differently and neither writes is
/// invisible to both.
///
/// The report names the header byte and the length, because those two are what
/// a person needs to reproduce it by hand.
#[test]
#[ignore = "needs libzenohpico.so (CMake build product); Layer E runs via --ignored"]
fn wz_and_pico_agree_on_what_is_a_transport_message() {
    let pico = unsafe { open(&zenoh_pico_shared_library()) };
    let mut divergences: Vec<((u8, usize), String)> = Vec::new();

    let mut unnamed_but_accepted = 0usize;
    for bytes in corpus() {
        let mine = wz_verdict(&bytes);
        let theirs = unsafe { pico_accepts(&pico, &bytes) };
        match (mine, theirs) {
            // The comparison that means something.
            (WzVerdict::Named, false) | (WzVerdict::Refused, true) => divergences.push((
                (bytes[0], bytes.len() - 1),
                format!(
                    "header 0x{:02X}, {} body byte(s): wz={mine:?} pico={}",
                    bytes[0],
                    bytes.len() - 1,
                    if theirs { "accept" } else { "reject" },
                ),
            )),
            // A MID this build cannot name, which pico CAN: a reach gap, not a
            // disagreement about the wire. Counted so it can never be zero by
            // accident and never mistaken for agreement.
            (WzVerdict::Unnamed, true) => unnamed_but_accepted += 1,
            _ => {}
        }
    }

    // BOTH directions of drift. `new` is a boundary that moved somewhere nobody
    // looked; `resolved` is a pinned entry that stopped diverging, which must be
    // taken off the list deliberately rather than left to rot into a claim
    // nobody checks.
    let pinned: std::collections::BTreeSet<(u8, usize)> =
        KNOWN_DIVERGENCES.iter().copied().collect();
    let new: Vec<&String> = divergences
        .iter()
        .filter(|(k, _)| !pinned.contains(k))
        .map(|(_, m)| m)
        .collect();
    let seen: std::collections::BTreeSet<(u8, usize)> =
        divergences.iter().map(|(k, _)| *k).collect();
    let resolved: Vec<&(u8, usize)> = KNOWN_DIVERGENCES
        .iter()
        .filter(|k| !seen.contains(k))
        .collect();

    assert!(
        new.is_empty(),
        "{} NEW disagreement(s) about the protocol's boundary \
         ({unnamed_but_accepted} unnamed-but-valid, reported separately):\n  {}",
        new.len(),
        new.iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );
    assert!(
        resolved.is_empty(),
        "{} pinned divergence(s) no longer diverge and must be removed from \
         KNOWN_DIVERGENCES: {:?}",
        resolved.len(),
        resolved
    );
    println!(
        "{} pinned divergence(s) hold; {unnamed_but_accepted} MID(s) pico names \
         and this build does not",
        KNOWN_DIVERGENCES.len()
    );
}
