// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! xtask — the watching-zenoh codegen SSOT (R311y22).
//!
//! Regenerates the committed generated Rust under `out/**` from the SCXML
//! sources. It is the ONE place codegen is invoked; the per-crate `build.rs`
//! scripts stop running codegen and instead `include!` the committed files,
//! so a plain `cargo build` of the wz stack needs no libxml2/SCE toolchain.
//!
//! Faithfulness: each emit uses the SAME `sce_build::compile_forge_with_imports`
//! call (+ the SAME SCE-MAP strip) the pre-R311y22 `wz-codecs/build.rs` used,
//! so the regenerated bytes are byte-identical to the old build-time emit. The
//! CI regen-diff lane (`scripts/regen-codegen.sh` + `git diff --exit-code`)
//! enforces `committed == regenerated`, making the committed tree a verified
//! cache of the SCXML SSOT rather than a second source of truth.
//!
//! Usage: `cargo run --manifest-path xtask/Cargo.toml -- codecs`
//! (or `regen` / no arg = regenerate everything wired so far).

use std::path::{Path, PathBuf};

use sce_build::{
    compile_forge_with_imports, generator::Language, DocumentLabel, ForgeCompileOptions,
};

/// Codec SCXMLs to emit, in dependency order (leaves first, composers last) so
/// the importer validates each `<sce:import>` target before its composer. The
/// FULL superset — xtask emits every codec unconditionally; the per-codec
/// feature gate lives at the `#[cfg(feature = ...)]` on the `pub mod` in
/// `wz-codecs/src/lib.rs`, so a feature-off build still compiles zero of the
/// disabled codec (footprint honesty preserved) even though `out/` holds all.
/// Kept in sync with `wz-codecs/build.rs::CODECS` (the regen-diff lane catches
/// any drift between this list and what lib.rs `include!`s).
const CODECS: &[&str] = &[
    // Leaf codecs (no imports).
    "timestamp",
    "encoding",
    "ext_unit",
    "ext_zint",
    "ext_zbuf",
    "crc32",
    "serial_envelope",
    "cobs_encode",
    "cobs_decode",
    "stream_envelope",
    "close",
    "frame",
    "fragment",
    "scout",
    "init_body",
    "open_body",
    "join",
    "locator",
    "linkstate_link",
    "linkstate_weight",
    "keep_alive",
    "decl_final",
    "undecl_kexpr",
    "undecl_subscriber",
    "undecl_queryable",
    "undecl_token",
    // Composing codecs.
    "hello",
    "ext_entry",
    "ext_envelope",
    "msg_put",
    "msg_del",
    "wireexpr_local",
    "wireexpr_nonlocal",
    "wireexpr",
    "query",
    "request",
    "push",
    "response_final",
    "oam",
    "interest_body",
    "interest",
    "reply",
    "err",
    "response",
    "decl_kexpr",
    "decl_subscriber",
    "decl_queryable",
    "decl_token",
    "declare",
    "linkstate",
    "linkstate_list",
];

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/xtask; the repo root is its parent.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask manifest has a parent (the repo root)")
        .to_path_buf()
}

/// Regenerate `out/wz-codecs/<stem>.rs` for every codec. Byte-faithful to the
/// old `wz-codecs/build.rs` emit: same compile call, same SCE-MAP strip,
/// same per-stem output file (`<stem>.rs`); the unconsumed `<stem>_test.rs`
/// SCE also emits is dropped (lib.rs never `include!`s it).
fn regen_codecs(root: &Path) {
    let resource_dir = root.join("sources/codecs");
    let out_dir = root.join("out/wz-codecs");
    std::fs::create_dir_all(&out_dir)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_dir.display()));

    let options = ForgeCompileOptions::default();
    let mut written = 0usize;

    for stem in CODECS {
        let scxml_path = resource_dir.join(format!("{stem}.scxml"));
        let content = std::fs::read_to_string(&scxml_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", scxml_path.display()));

        let output = compile_forge_with_imports(
            &content,
            DocumentLabel::symmetric(stem),
            Language::Rust,
            &resource_dir,
            &options,
        )
        .unwrap_or_else(|e| panic!("sce-build codegen failed for {stem}: {e}"));

        let target_name = format!("{stem}.rs");
        let code = output
            .files
            .iter()
            .find(|(filename, _)| filename == &target_name)
            .map(|(_, code)| code)
            .unwrap_or_else(|| panic!("sce-build emitted no {target_name} for {stem}"));

        // Same strip wz-codecs/build.rs applied: SCE emits a file-head
        // `#![doc = "SCE-MAP: stem:line"]` inner attribute (R40 carry) that is
        // illegal once the file is `include!`'d mid-module; the same SCE-MAP
        // info is on the next line as a regular `// SCE-MAP:` comment, so the
        // strip loses zero information. (The proper fix is SCE-upstream emitting
        // a regular comment; tracked separately.)
        let stripped = code
            .lines()
            .filter(|line| !line.starts_with("#![doc = \"SCE-MAP:"))
            .collect::<Vec<_>>()
            .join("\n");

        let target = out_dir.join(&target_name);
        std::fs::write(&target, &stripped)
            .unwrap_or_else(|e| panic!("write {}: {e}", target.display()));
        written += 1;
    }

    println!("xtask: regenerated {written} codec files into {}", out_dir.display());
}

fn main() {
    let root = repo_root();
    let what = std::env::args().nth(1).unwrap_or_else(|| "regen".to_string());
    match what.as_str() {
        "codecs" | "regen" => regen_codecs(&root),
        other => {
            eprintln!("xtask: unknown target '{other}' (expected: codecs | regen)");
            std::process::exit(2);
        }
    }
}
