// SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-watching-zenoh-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! xtask — the watching-zenoh codegen SSOT (R311y22).
//!
//! Regenerates the committed generated Rust under `out/**` from the SCXML
//! sources. It is the ONE place codegen is invoked; the per-crate `build.rs`
//! scripts stop running codegen and instead `include!` the committed files,
//! so a plain `cargo build` of the wz stack needs no libxml2/SCE toolchain.
//!
//! Faithfulness: each emit uses the SAME `sce_build::compile_forge_with_imports`
//! call (+ the SAME SCE-MAP strip) the pre-R311y22 `wz-codecs/build.rs` used,
//! so the regenerated bytes are byte-identical to the old build-time emit. The
//! CI regen-diff lane (`scripts/regen-codegen.sh` + `git diff --exit-code`)
//! enforces `committed == regenerated`, making the committed tree a verified
//! cache of the SCXML SSOT rather than a second source of truth.
//!
//! Usage: `cargo run --manifest-path xtask/Cargo.toml -- codecs`
//! (or `regen` / no arg = regenerate everything wired so far).

use std::path::{Path, PathBuf};
use std::process::Command;

use sce_build::{
    compile_forge_with_imports, generator::Language, DocumentLabel, ForgeCompileOptions,
};
use wz_switchboard_codegen::{
    generate, parse_codec_facts, parse_event_schema_facts, parse_machine_facts, GenInput,
};
use wz_switchboard_schema::SwitchboardSpec;

/// Codec SCXMLs to emit, in dependency order (leaves first, composers last) so
/// the importer validates each `<sce:import>` target before its composer. The
/// FULL superset — xtask emits every codec unconditionally; the per-codec
/// feature gate lives at the `#[cfg(feature = ...)]` on the `pub mod` in
/// `wz-codecs/src/lib.rs`, so a feature-off build still compiles zero of the
/// disabled codec (footprint honesty preserved) even though `out/` holds all.
/// This const IS the SSOT for the codec set (the former
/// `wz-codecs/build.rs::CODECS` it mirrored is deleted as of R311y22a); the
/// Layer B2 regen-diff lane catches drift between it and the committed out/,
/// and a `wz-codecs/src/lib.rs` include! of a stem absent here is a compile
/// error — so the two stay consistent.
const CODECS: &[&str] = &[
    // Leaf codecs (no imports).
    "timestamp",
    "encoding",
    "ext_unit",
    "ext_zint",
    "ext_zbuf",
    "crc32",
    "serial_envelope",
    "cobs_encode",
    "cobs_decode",
    "stream_envelope",
    "close",
    "frame",
    "fragment",
    "scout",
    "init_body",
    "open_body",
    "join",
    "locator",
    "linkstate_link",
    "linkstate_weight",
    "keep_alive",
    "decl_final",
    "undecl_kexpr",
    "undecl_subscriber",
    "undecl_queryable",
    "undecl_token",
    // Composing codecs.
    "hello",
    "ext_entry",
    "ext_envelope",
    "msg_put",
    "msg_del",
    "wireexpr_local",
    "wireexpr_nonlocal",
    "wireexpr",
    "query",
    "request",
    "push",
    "response_final",
    "oam",
    "interest_body",
    "interest",
    "reply",
    "err",
    "response",
    "decl_kexpr",
    "decl_subscriber",
    "decl_queryable",
    "decl_token",
    "declare",
    "linkstate",
    "linkstate_list",
];

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/xtask; the repo root is its parent.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask manifest has a parent (the repo root)")
        .to_path_buf()
}

/// Regenerate `out/wz-codecs/<stem>.rs` for every codec. Byte-faithful to the
/// old `wz-codecs/build.rs` emit: same compile call, same SCE-MAP strip,
/// same per-stem output file (`<stem>.rs`); the unconsumed `<stem>_test.rs`
/// SCE also emits is dropped (lib.rs never `include!`s it).
fn regen_codecs(root: &Path) {
    let resource_dir = root.join("sources/codecs");
    let out_dir = root.join("out/wz-codecs");
    std::fs::create_dir_all(&out_dir)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_dir.display()));

    let options = ForgeCompileOptions::default();
    let mut written = 0usize;

    for stem in CODECS {
        let scxml_path = resource_dir.join(format!("{stem}.scxml"));
        let content = std::fs::read_to_string(&scxml_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", scxml_path.display()));

        let output = compile_forge_with_imports(
            &content,
            DocumentLabel::symmetric(stem),
            Language::Rust,
            &resource_dir,
            &options,
        )
        .unwrap_or_else(|e| panic!("sce-build codegen failed for {stem}: {e}"));

        let target_name = format!("{stem}.rs");
        let code = output
            .files
            .iter()
            .find(|(filename, _)| filename == &target_name)
            .map(|(_, code)| code)
            .unwrap_or_else(|| panic!("sce-build emitted no {target_name} for {stem}"));

        // Same strip wz-codecs/build.rs applied: SCE emits a file-head
        // `#![doc = "SCE-MAP: stem:line"]` inner attribute (R40 carry) that is
        // illegal once the file is `include!`'d mid-module; the same SCE-MAP
        // info is on the next line as a regular `// SCE-MAP:` comment, so the
        // strip loses zero information. SCE itself tracks this as its
        // `traceability/sce-map-attribute-stripped` diagnostic and emits the
        // SCE-MAP info redundantly as both the inner attr AND the line comment
        // precisely so a mid-module `include!` consumer can drop the former
        // losslessly — so this strip consumes SCE's documented dual-marker
        // fallback, not a wz workaround. (Proper end-state: SCE emits only the
        // regular comment; then this strip becomes a no-op.)
        let stripped = code
            .lines()
            .filter(|line| !line.starts_with("#![doc = \"SCE-MAP:"))
            .collect::<Vec<_>>()
            .join("\n");

        let target = out_dir.join(&target_name);
        std::fs::write(&target, &stripped)
            .unwrap_or_else(|e| panic!("write {}: {e}", target.display()));
        written += 1;
    }

    println!(
        "xtask: regenerated {written} codec files into {}",
        out_dir.display()
    );
}

/// Regenerate the binary-path statecharts + buffer-pools (R311y22b) via the
/// SAME `wz_codegen_build::Codegen` the per-crate build.rs scripts used, so the
/// committed bytes are byte-identical to the old build-time emit (same
/// sce-codegen binary, same `emit_statechart` strip_inner_attrs /
/// `emit_buffer_pool` strip+cut_generated_tests). Requires the vendored
/// sce-codegen binary (run `scripts/build-sce.sh`); `Codegen::from_manifest`
/// panics with that directive if absent.
///
/// Emits the FULL superset (every feature-gated statechart/pool), one
/// directory per consuming crate, mirroring each build.rs's emits:
///   wz-session-core  : reassembly_slot, scouting, session_fsm_unicast,
///                      session_fsm_multicast, multicast_peer (statecharts)
///   wz-runtime-tokio : reassembly_pool_ap (buffer-pool)
///   wz-runtime-coop  : reassembly_pool_mcu (buffer-pool)
///   wz-link-lwip     : scout_rx_pool_mcu, session_rx_pool_mcu,
///                      session_rx_pool_mcu_minimal,
///                      session_rx_pool_mcu_multicast (buffer-pools)
fn regen_statecharts_and_pools(root: &Path) {
    // `Codegen::from_manifest` derives the SCE workspace as
    // <manifest>/../../vendor/sce; any crates/* dir resolves to repo/vendor/sce.
    let codegen = wz_codegen_build::Codegen::from_manifest(&root.join("crates/wz-session-core"));
    // R311y517 — REPO-RELATIVE: these dirs are handed to SCE, which stamps the
    // path verbatim into the `// From:` header. See [`repo_relative`].
    let network = repo_relative(root, &root.join("sources/network"));
    let session = repo_relative(root, &root.join("sources/session"));

    // wz-session-core statecharts. reassembly_slot lives under sources/network;
    // the session FSMs under sources/session (mirrors build.rs resource_dirs).
    let sc_out = root.join("out/wz-session-core");
    mkdir(&sc_out);
    codegen.emit_statechart("reassembly_slot", &network, &sc_out);
    for stem in [
        "scouting",
        "session_fsm_unicast",
        "session_fsm_multicast",
        "multicast_peer",
    ] {
        codegen.emit_statechart(stem, &session, &sc_out);
    }

    // Buffer-pools — (stem, consuming-crate). All sourced from sources/network.
    let pools: &[(&str, &str)] = &[
        ("reassembly_pool_ap", "wz-runtime-tokio"),
        ("reassembly_pool_mcu", "wz-runtime-coop"),
        ("scout_rx_pool_mcu", "wz-link-lwip"),
        ("session_rx_pool_mcu", "wz-link-lwip"),
        ("session_rx_pool_mcu_minimal", "wz-link-lwip"),
        ("session_rx_pool_mcu_multicast", "wz-link-lwip"),
    ];
    for (stem, krate) in pools {
        let out = root.join("out").join(krate);
        mkdir(&out);
        codegen.emit_buffer_pool(stem, &network, &out);
    }

    // sce-codegen drops a `sce_sourcemap.json` side-artifact into the
    // --output-dir (overwritten per emit, emit-order-dependent, never
    // include!'d). The old build.rs left it in the ephemeral OUT_DIR
    // harmlessly; the committed tree must not carry it (it is not a consumed
    // artifact and its content depends on which stem was emitted last).
    for krate in [
        "wz-session-core",
        "wz-runtime-tokio",
        "wz-runtime-coop",
        "wz-link-lwip",
    ] {
        let _ = std::fs::remove_file(root.join("out").join(krate).join("sce_sourcemap.json"));
    }

    println!("xtask: regenerated 5 statecharts + 6 buffer-pools into out/{{wz-session-core,wz-runtime-tokio,wz-runtime-coop,wz-link-lwip}}");
}

fn mkdir(p: &Path) {
    std::fs::create_dir_all(p).unwrap_or_else(|e| panic!("create {}: {e}", p.display()));
}

/// R311y517 — hand SCE a REPO-RELATIVE SCXML source dir, so the `// From:`
/// provenance line it stamps into `out/**` is machine-independent.
///
/// Under SCE 43695e572 the header path is emitted **verbatim as the caller
/// named it**: `header_source_path` returns the argument unchanged when
/// `source_root` is `None` (`vendor/sce/sce-build/src/lib.rs:330-334`), and the
/// in-tree call site passes `None` (`:229`). The pre-bump SCE stripped the
/// process CWD instead — which is what R311y22e's CWD pin was built against.
/// That pin is still necessary (relative paths must resolve) but it is no
/// longer SUFFICIENT, and the y510 pin bump silently reverted every `// From:`
/// line to an absolute path. Two consequences, both shipped: the author's home
/// directory was committed into 8 generated files, and Layer B2 (committed
/// `out/**` == regenerated) went permanently red on any checkout whose path
/// differs from the one that last regenerated — i.e. every hosted CI run.
///
/// Safe because [`main`] pins the process CWD to the repo root before any
/// codegen runs; a path outside the root is passed through unchanged.
fn repo_relative(root: &Path, p: &Path) -> PathBuf {
    p.strip_prefix(root)
        .map_or_else(|_| p.to_path_buf(), Path::to_path_buf)
}

/// One switchboard 2-stage codegen target (R311y22c), mirroring each
/// switchboard build.rs: stage 1 = sce-codegen `--emit-ast` per source doc
/// (machine + schemas + codecs); stage 2 = `wz_switchboard_codegen::generate`
/// over the forge-ASTs + the `wz-switchboard.yaml` sidecar -> dispatch.
struct Switchboard {
    /// out/<krate> directory + the consuming crate's identity.
    krate: &'static str,
    /// Repo-relative manifest dir (holds sources/ + wz-switchboard.yaml).
    manifest: &'static str,
    /// `--no-std` emit (the heap-free mcu-noheap-probe profile).
    no_std: bool,
    /// Machine stem; emits the consumed `<machine>_sm.rs` + its forge-AST.
    machine: &'static str,
    /// Event-schema stems; contribute only their forge-AST (no consumed .rs).
    schemas: &'static [&'static str],
    /// Codec stems; each emits a consumed `<codec>.rs` + its forge-AST, and
    /// `parse_codec_facts` keys on the same stem.
    codecs: &'static [&'static str],
}

const SWITCHBOARDS: &[Switchboard] = &[
    Switchboard {
        krate: "wz-ap-demo-app",
        manifest: "crates/wz-ap-demo-app",
        no_std: false,
        machine: "sensor_monitor",
        schemas: &["temp_update_schema"],
        codecs: &["temp_payload"],
    },
    Switchboard {
        krate: "wz-switchboard-example",
        manifest: "crates/wz-switchboard-example",
        no_std: false,
        machine: "sensor_monitor",
        schemas: &["temp_update_schema", "humidity_update_schema"],
        codecs: &["temp_payload", "humidity_payload"],
    },
    Switchboard {
        krate: "mcu-noheap-probe",
        manifest: "deploy/mcu-noheap-probe",
        no_std: true,
        machine: "thermostat",
        schemas: &["temp_reading_schema"],
        codecs: &["temp_reading_codec"],
    },
];

/// Regenerate the switchboard 2-stage codegen for all 3 consumers into
/// out/<krate>/. Intermediates (the `.ast.json`, schema emits, sourcemap) go
/// to a temp dir; only the consumed `<machine>_sm.rs` + `<codec>.rs` +
/// `dispatch_switchboard.rs` land under out/. Byte-faithful to the build.rs:
/// same sce-codegen `--emit-ast` invocation (+ the same `#![...]` strip) and
/// the same `wz_switchboard_codegen::generate` call. SOURCE_DATE_EPOCH=0 (set
/// in `main`) keeps the machine/codec emit's `generated-at` byte-stable.
fn regen_switchboards(root: &Path) {
    let sce_workspace = root
        .join("vendor/sce")
        .canonicalize()
        .expect("canonicalize vendor/sce");
    let sce_codegen = wz_codegen_build::locate_sce_codegen(&sce_workspace);

    for sb in SWITCHBOARDS {
        let manifest = root.join(sb.manifest);
        // R311y517 — REPO-RELATIVE for the same reason as the statechart leg:
        // `emit_ast` passes this straight to sce-codegen, which stamps it
        // verbatim into the `// From:` header. See [`repo_relative`].
        let src = repo_relative(root, &manifest.join("sources"));
        let sidecar = manifest.join("wz-switchboard.yaml");
        // Intermediates land in a temp dir so only the consumed files reach out/.
        let tmp = std::env::temp_dir().join(format!("wz-xtask-sb-{}", sb.krate));
        let _ = std::fs::remove_dir_all(&tmp);
        mkdir(&tmp);

        // Stage 1 — --emit-ast each doc. Machine + codecs also emit a consumed
        // .rs (stripped for mid-module include!); schemas contribute only AST.
        let machine_ast = emit_ast(
            sb.machine,
            &src,
            &tmp,
            &sce_codegen,
            &sce_workspace,
            sb.no_std,
        );
        wz_codegen_build::strip_inner_attrs_file(&tmp.join(format!("{}_sm.rs", sb.machine)));
        let schema_asts: Vec<PathBuf> = sb
            .schemas
            .iter()
            .map(|s| emit_ast(s, &src, &tmp, &sce_codegen, &sce_workspace, sb.no_std))
            .collect();
        let codec_asts: Vec<PathBuf> = sb
            .codecs
            .iter()
            .map(|c| {
                let ast = emit_ast(c, &src, &tmp, &sce_codegen, &sce_workspace, sb.no_std);
                wz_codegen_build::strip_inner_attrs_file(&tmp.join(format!("{c}.rs")));
                ast
            })
            .collect();

        // Stage 2 — parse facts + sidecar, run the pure generator.
        let facts = parse_machine_facts(&read(&machine_ast)).expect("parse machine facts");
        let schemas: Vec<_> = schema_asts
            .iter()
            .map(|a| parse_event_schema_facts(&read(a)).expect("parse event-schema facts"))
            .collect();
        let codecs: Vec<_> = sb
            .codecs
            .iter()
            .zip(&codec_asts)
            // name is &&str from the slice iterator; parse_codec_facts takes &str.
            .map(|(name, a)| parse_codec_facts(&read(a), *name).expect("parse codec facts"))
            .collect();
        let spec: SwitchboardSpec =
            serde_yaml_ng::from_str(&read(&sidecar)).expect("parse wz-switchboard.yaml");
        let dispatch = generate(&GenInput {
            spec: &spec,
            facts: &facts,
            schemas: &schemas,
            codecs: &codecs,
            machine_module: sb.machine,
        })
        .expect("generate switchboard dispatch");

        // Write ONLY the consumed files to out/<krate>.
        let out = root.join("out").join(sb.krate);
        mkdir(&out);
        let machine_rs = format!("{}_sm.rs", sb.machine);
        std::fs::copy(tmp.join(&machine_rs), out.join(&machine_rs))
            .unwrap_or_else(|e| panic!("copy {machine_rs}: {e}"));
        for c in sb.codecs {
            let cr = format!("{c}.rs");
            std::fs::copy(tmp.join(&cr), out.join(&cr))
                .unwrap_or_else(|e| panic!("copy {cr}: {e}"));
        }
        std::fs::write(out.join("dispatch_switchboard.rs"), &dispatch)
            .unwrap_or_else(|e| panic!("write dispatch_switchboard.rs: {e}"));
        let _ = std::fs::remove_dir_all(&tmp);
    }
    println!("xtask: regenerated 3 switchboards into out/{{wz-ap-demo-app,wz-switchboard-example,mcu-noheap-probe}}");
}

/// `sce-codegen generate -l rust [--no-std] --emit-ast <ast>` for `<stem>.scxml`
/// (the SAME invocation the switchboard build.rs used). Returns the AST path.
fn emit_ast(
    stem: &str,
    src: &Path,
    out_dir: &Path,
    bin: &Path,
    workspace: &Path,
    no_std: bool,
) -> PathBuf {
    let scxml = src.join(format!("{stem}.scxml"));
    let ast = out_dir.join(format!("{stem}.ast.json"));
    let mut cmd = Command::new(bin);
    cmd.arg("--workspace-root")
        .arg(workspace)
        .arg("generate")
        .arg("--language")
        .arg("rust");
    if no_std {
        cmd.arg("--no-std");
    }
    cmd.arg("--emit-ast")
        .arg(&ast)
        .arg("--output-dir")
        .arg(out_dir)
        .arg(&scxml);
    let status = cmd
        .status()
        .unwrap_or_else(|e| panic!("invoke sce-codegen --emit-ast for {stem}: {e}"));
    if !status.success() {
        panic!("sce-codegen --emit-ast failed for {stem} (exit {status:?})");
    }
    ast
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn main() {
    // Deterministic codegen (R311y22b): sce-codegen's statechart/buffer-pool
    // emit stamps a `// generated-at: <unix secs>` provenance line that honors
    // SOURCE_DATE_EPOCH (vendor/sce/sce-build/src/forge/drift.rs:120 — the
    // reproducible-builds convention; the timestamp is informational and feeds
    // neither the source-hash nor the template-hash). Pinning it to 0 makes the
    // committed out/** byte-stable across regenerations so the CI regen-diff
    // gate (Layer B2) compares equal — this is SCE's intended determinism knob,
    // not a wz-side strip. The child sce-codegen process inherits this var.
    std::env::set_var("SOURCE_DATE_EPOCH", "0");

    let root = repo_root();

    // R311y22e — anchor the process CWD to the repo root before any codegen.
    // sce-codegen derives the `// From: <path>` provenance line by stripping the
    // current working directory from the (absolute) SCXML path
    // (vendor/sce/sce-build/src/lib.rs `resolve_source_path`). Pinning CWD to the
    // repo root makes that From-line a stable repo-relative path
    // (`sources/...`, `crates/...`, `deploy/...`) regardless of where the xtask
    // was launched — so the committed out/** regenerates byte-identically on any
    // contributor's machine + CI (the Layer B2 regen-diff gate cannot
    // false-positive), and no absolute checkout path leaks into committed source.
    // The child sce-codegen processes inherit this CWD.
    std::env::set_current_dir(&root)
        .unwrap_or_else(|e| panic!("set cwd to repo root {}: {e}", root.display()));

    let what = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "regen".to_string());
    match what.as_str() {
        "codecs" => regen_codecs(&root),
        "statecharts" => regen_statecharts_and_pools(&root),
        "switchboards" => regen_switchboards(&root),
        "regen" => {
            regen_codecs(&root);
            regen_statecharts_and_pools(&root);
            regen_switchboards(&root);
        }
        other => {
            eprintln!(
                "xtask: unknown target '{other}' (expected: codecs | statecharts | switchboards | regen)"
            );
            std::process::exit(2);
        }
    }
}
